Ext.define('MOBILEAPP.model.CierreCalleModel', {
	extend : 'Ext.data.Model',
	fields : [ 
				'idIncidencia',
				'idEvento',
				'tipoEvento',
				'subTipo',
				'fecHoraInicio',
				'fecHoraFin',
				'descripcion',
				'severidad',
				'calle',
				'tipoDireccion',
				'direccionFinal',
				'nombreCalleInicio',
				'nombreCalleFin',
				'fecRegistra',
				'fecModifica',
				'desUsuRegistra',
				'desUsuModifica',
				'desIpRegistra',
				'desIpModifica',
				'idTipoVia',
				'cuadraEvento',
				'idVia',
				'idCasoVoxiva',
				'tipoCasoVoxiva',
				'subTipoCasoVoxiva',
				'tipoIncidencia',
				'idViaCatastro',
				'idTipoViaCatastro',
				'detalleGeometria',
				'latitud',
				'longitud',
				'tipo',
				'nombreTipoEvento',
				'desTipoIncidencia',
				'desCallles'
	         ]
});


