package pe.gob.miraflores.mobile.dao.catalogo;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.catalogo.GrupoCatalogo;
import pe.gob.miraflores.mobile.domain.catalogo.GrupoCatalogoCriteria;


public interface GrupoCatalogoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmgpoele
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	long countByExample(GrupoCatalogoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmgpoele
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	int deleteByExample(GrupoCatalogoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmgpoele
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	int deleteByPrimaryKey(Integer ideGrupoElemento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmgpoele
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	int insert(GrupoCatalogo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmgpoele
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	int insertSelective(GrupoCatalogo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmgpoele
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	List<GrupoCatalogo> selectByExample(GrupoCatalogoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmgpoele
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	GrupoCatalogo selectByPrimaryKey(Integer ideGrupoElemento);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmgpoele
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	int updateByExampleSelective(@Param("record") GrupoCatalogo record,
			@Param("example") GrupoCatalogoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmgpoele
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	int updateByExample(@Param("record") GrupoCatalogo record, @Param("example") GrupoCatalogoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmgpoele
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	int updateByPrimaryKeySelective(GrupoCatalogo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmgpoele
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	int updateByPrimaryKey(GrupoCatalogo record);
}