package pe.gob.miraflores.mobile.dao.infovigilante;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.infovigilante.GeoInfoVigilante;
import pe.gob.miraflores.mobile.domain.infovigilante.GeoInfoVigilanteCriteria;



public interface GeoInfoVigilanteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    long countByExample(GeoInfoVigilanteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    int deleteByExample(GeoInfoVigilanteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    int insert(GeoInfoVigilante record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    int insertSelective(GeoInfoVigilante record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    List<GeoInfoVigilante> selectByExample(GeoInfoVigilanteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    GeoInfoVigilante selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    int updateByExampleSelective(@Param("record") GeoInfoVigilante record, @Param("example") GeoInfoVigilanteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    int updateByExample(@Param("record") GeoInfoVigilante record, @Param("example") GeoInfoVigilanteCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    int updateByPrimaryKeySelective(GeoInfoVigilante record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    int updateByPrimaryKey(GeoInfoVigilante record);
}