package pe.gob.miraflores.mobile.domain.catalogo;

import java.util.Date;

public class Catalogo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapa.ctlmelecgo.ide_elemento
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	private Integer ideElemento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapa.ctlmelecgo.ide_grupo
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	private Integer ideGrupo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapa.ctlmelecgo.cod_codigo
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	private String codCodigo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapa.ctlmelecgo.des_nombre
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	private String desNombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapa.ctlmelecgo.clv_abreviar
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	private String clvAbreviar;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapa.ctlmelecgo.ide_elemento1
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	private Integer ideElemento1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapa.ctlmelecgo.ind_estado
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	private String indEstado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapa.ctlmelecgo.fec_fecha_creacion
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	private Date fecFechaCreacion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapa.ctlmelecgo.referencia
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	private String referencia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapa.ctlmelecgo.referencia1
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	private String referencia1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mapa.ctlmelecgo.referencia2
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	private String referencia2;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapa.ctlmelecgo.ide_elemento
	 * @return  the value of mapa.ctlmelecgo.ide_elemento
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public Integer getIdeElemento() {
		return ideElemento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapa.ctlmelecgo.ide_elemento
	 * @param ideElemento  the value for mapa.ctlmelecgo.ide_elemento
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public void setIdeElemento(Integer ideElemento) {
		this.ideElemento = ideElemento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapa.ctlmelecgo.ide_grupo
	 * @return  the value of mapa.ctlmelecgo.ide_grupo
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public Integer getIdeGrupo() {
		return ideGrupo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapa.ctlmelecgo.ide_grupo
	 * @param ideGrupo  the value for mapa.ctlmelecgo.ide_grupo
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public void setIdeGrupo(Integer ideGrupo) {
		this.ideGrupo = ideGrupo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapa.ctlmelecgo.cod_codigo
	 * @return  the value of mapa.ctlmelecgo.cod_codigo
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public String getCodCodigo() {
		return codCodigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapa.ctlmelecgo.cod_codigo
	 * @param codCodigo  the value for mapa.ctlmelecgo.cod_codigo
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public void setCodCodigo(String codCodigo) {
		this.codCodigo = codCodigo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapa.ctlmelecgo.des_nombre
	 * @return  the value of mapa.ctlmelecgo.des_nombre
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public String getDesNombre() {
		return desNombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapa.ctlmelecgo.des_nombre
	 * @param desNombre  the value for mapa.ctlmelecgo.des_nombre
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public void setDesNombre(String desNombre) {
		this.desNombre = desNombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapa.ctlmelecgo.clv_abreviar
	 * @return  the value of mapa.ctlmelecgo.clv_abreviar
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public String getClvAbreviar() {
		return clvAbreviar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapa.ctlmelecgo.clv_abreviar
	 * @param clvAbreviar  the value for mapa.ctlmelecgo.clv_abreviar
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public void setClvAbreviar(String clvAbreviar) {
		this.clvAbreviar = clvAbreviar;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapa.ctlmelecgo.ide_elemento1
	 * @return  the value of mapa.ctlmelecgo.ide_elemento1
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public Integer getIdeElemento1() {
		return ideElemento1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapa.ctlmelecgo.ide_elemento1
	 * @param ideElemento1  the value for mapa.ctlmelecgo.ide_elemento1
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public void setIdeElemento1(Integer ideElemento1) {
		this.ideElemento1 = ideElemento1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapa.ctlmelecgo.ind_estado
	 * @return  the value of mapa.ctlmelecgo.ind_estado
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public String getIndEstado() {
		return indEstado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapa.ctlmelecgo.ind_estado
	 * @param indEstado  the value for mapa.ctlmelecgo.ind_estado
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public void setIndEstado(String indEstado) {
		this.indEstado = indEstado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapa.ctlmelecgo.fec_fecha_creacion
	 * @return  the value of mapa.ctlmelecgo.fec_fecha_creacion
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public Date getFecFechaCreacion() {
		return fecFechaCreacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapa.ctlmelecgo.fec_fecha_creacion
	 * @param fecFechaCreacion  the value for mapa.ctlmelecgo.fec_fecha_creacion
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public void setFecFechaCreacion(Date fecFechaCreacion) {
		this.fecFechaCreacion = fecFechaCreacion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapa.ctlmelecgo.referencia
	 * @return  the value of mapa.ctlmelecgo.referencia
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public String getReferencia() {
		return referencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapa.ctlmelecgo.referencia
	 * @param referencia  the value for mapa.ctlmelecgo.referencia
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapa.ctlmelecgo.referencia1
	 * @return  the value of mapa.ctlmelecgo.referencia1
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public String getReferencia1() {
		return referencia1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapa.ctlmelecgo.referencia1
	 * @param referencia1  the value for mapa.ctlmelecgo.referencia1
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public void setReferencia1(String referencia1) {
		this.referencia1 = referencia1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mapa.ctlmelecgo.referencia2
	 * @return  the value of mapa.ctlmelecgo.referencia2
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public String getReferencia2() {
		return referencia2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mapa.ctlmelecgo.referencia2
	 * @param referencia2  the value for mapa.ctlmelecgo.referencia2
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	public void setReferencia2(String referencia2) {
		this.referencia2 = referencia2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmelecgo
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Catalogo other = (Catalogo) that;
		return (this.getIdeElemento() == null ? other.getIdeElemento() == null
				: this.getIdeElemento().equals(other.getIdeElemento()))
				&& (this.getIdeGrupo() == null ? other.getIdeGrupo() == null
						: this.getIdeGrupo().equals(other.getIdeGrupo()))
				&& (this.getCodCodigo() == null ? other.getCodCodigo() == null
						: this.getCodCodigo().equals(other.getCodCodigo()))
				&& (this.getDesNombre() == null ? other.getDesNombre() == null
						: this.getDesNombre().equals(other.getDesNombre()))
				&& (this.getClvAbreviar() == null ? other.getClvAbreviar() == null
						: this.getClvAbreviar().equals(other.getClvAbreviar()))
				&& (this.getIdeElemento1() == null ? other.getIdeElemento1() == null
						: this.getIdeElemento1().equals(other.getIdeElemento1()))
				&& (this.getIndEstado() == null ? other.getIndEstado() == null
						: this.getIndEstado().equals(other.getIndEstado()))
				&& (this.getFecFechaCreacion() == null ? other.getFecFechaCreacion() == null
						: this.getFecFechaCreacion().equals(other.getFecFechaCreacion()))
				&& (this.getReferencia() == null ? other.getReferencia() == null
						: this.getReferencia().equals(other.getReferencia()))
				&& (this.getReferencia1() == null ? other.getReferencia1() == null
						: this.getReferencia1().equals(other.getReferencia1()))
				&& (this.getReferencia2() == null ? other.getReferencia2() == null
						: this.getReferencia2().equals(other.getReferencia2()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.ctlmelecgo
	 * @mbg.generated  Mon Jul 10 15:03:31 COT 2017
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getIdeElemento() == null) ? 0 : getIdeElemento().hashCode());
		result = prime * result + ((getIdeGrupo() == null) ? 0 : getIdeGrupo().hashCode());
		result = prime * result + ((getCodCodigo() == null) ? 0 : getCodCodigo().hashCode());
		result = prime * result + ((getDesNombre() == null) ? 0 : getDesNombre().hashCode());
		result = prime * result + ((getClvAbreviar() == null) ? 0 : getClvAbreviar().hashCode());
		result = prime * result + ((getIdeElemento1() == null) ? 0 : getIdeElemento1().hashCode());
		result = prime * result + ((getIndEstado() == null) ? 0 : getIndEstado().hashCode());
		result = prime * result + ((getFecFechaCreacion() == null) ? 0 : getFecFechaCreacion().hashCode());
		result = prime * result + ((getReferencia() == null) ? 0 : getReferencia().hashCode());
		result = prime * result + ((getReferencia1() == null) ? 0 : getReferencia1().hashCode());
		result = prime * result + ((getReferencia2() == null) ? 0 : getReferencia2().hashCode());
		return result;
	}
}