package pe.gob.miraflores.mobile.dao.parametrosistema;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.parametrosistema.ParametroSistema;
import pe.gob.miraflores.mobile.domain.parametrosistema.ParametroSistemaCriteria;

public interface ParametroSistemaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.parametro_sistema
     *
     * @mbg.generated Mon Jul 10 12:21:14 COT 2017
     */
    long countByExample(ParametroSistemaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.parametro_sistema
     *
     * @mbg.generated Mon Jul 10 12:21:14 COT 2017
     */
    int deleteByExample(ParametroSistemaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.parametro_sistema
     *
     * @mbg.generated Mon Jul 10 12:21:14 COT 2017
     */
    int deleteByPrimaryKey(String idparametrosistema);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.parametro_sistema
     *
     * @mbg.generated Mon Jul 10 12:21:14 COT 2017
     */
    int insert(ParametroSistema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.parametro_sistema
     *
     * @mbg.generated Mon Jul 10 12:21:14 COT 2017
     */
    int insertSelective(ParametroSistema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.parametro_sistema
     *
     * @mbg.generated Mon Jul 10 12:21:14 COT 2017
     */
    List<ParametroSistema> selectByExample(ParametroSistemaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.parametro_sistema
     *
     * @mbg.generated Mon Jul 10 12:21:14 COT 2017
     */
    ParametroSistema selectByPrimaryKey(String idparametrosistema);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.parametro_sistema
     *
     * @mbg.generated Mon Jul 10 12:21:14 COT 2017
     */
    int updateByExampleSelective(@Param("record") ParametroSistema record, @Param("example") ParametroSistemaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.parametro_sistema
     *
     * @mbg.generated Mon Jul 10 12:21:14 COT 2017
     */
    int updateByExample(@Param("record") ParametroSistema record, @Param("example") ParametroSistemaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.parametro_sistema
     *
     * @mbg.generated Mon Jul 10 12:21:14 COT 2017
     */
    int updateByPrimaryKeySelective(ParametroSistema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.parametro_sistema
     *
     * @mbg.generated Mon Jul 10 12:21:14 COT 2017
     */
    int updateByPrimaryKey(ParametroSistema record);
}