package pe.gob.miraflores.mobile.domain.mapaincidencias;

import java.util.ArrayList;
import java.util.List;

public class GeoInfoTetraCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    public GeoInfoTetraCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIssiIsNull() {
            addCriterion("issi is null");
            return (Criteria) this;
        }

        public Criteria andIssiIsNotNull() {
            addCriterion("issi is not null");
            return (Criteria) this;
        }

        public Criteria andIssiEqualTo(Integer value) {
            addCriterion("issi =", value, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiNotEqualTo(Integer value) {
            addCriterion("issi <>", value, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiGreaterThan(Integer value) {
            addCriterion("issi >", value, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiGreaterThanOrEqualTo(Integer value) {
            addCriterion("issi >=", value, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiLessThan(Integer value) {
            addCriterion("issi <", value, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiLessThanOrEqualTo(Integer value) {
            addCriterion("issi <=", value, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiIn(List<Integer> values) {
            addCriterion("issi in", values, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiNotIn(List<Integer> values) {
            addCriterion("issi not in", values, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiBetween(Integer value1, Integer value2) {
            addCriterion("issi between", value1, value2, "issi");
            return (Criteria) this;
        }

        public Criteria andIssiNotBetween(Integer value1, Integer value2) {
            addCriterion("issi not between", value1, value2, "issi");
            return (Criteria) this;
        }

        public Criteria andIdInfoIsNull() {
            addCriterion("id_info is null");
            return (Criteria) this;
        }

        public Criteria andIdInfoIsNotNull() {
            addCriterion("id_info is not null");
            return (Criteria) this;
        }

        public Criteria andIdInfoEqualTo(Integer value) {
            addCriterion("id_info =", value, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoNotEqualTo(Integer value) {
            addCriterion("id_info <>", value, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoGreaterThan(Integer value) {
            addCriterion("id_info >", value, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_info >=", value, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoLessThan(Integer value) {
            addCriterion("id_info <", value, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoLessThanOrEqualTo(Integer value) {
            addCriterion("id_info <=", value, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoIn(List<Integer> values) {
            addCriterion("id_info in", values, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoNotIn(List<Integer> values) {
            addCriterion("id_info not in", values, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoBetween(Integer value1, Integer value2) {
            addCriterion("id_info between", value1, value2, "idInfo");
            return (Criteria) this;
        }

        public Criteria andIdInfoNotBetween(Integer value1, Integer value2) {
            addCriterion("id_info not between", value1, value2, "idInfo");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionIsNull() {
            addCriterion("nro_asignacion is null");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionIsNotNull() {
            addCriterion("nro_asignacion is not null");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionEqualTo(Integer value) {
            addCriterion("nro_asignacion =", value, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionNotEqualTo(Integer value) {
            addCriterion("nro_asignacion <>", value, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionGreaterThan(Integer value) {
            addCriterion("nro_asignacion >", value, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionGreaterThanOrEqualTo(Integer value) {
            addCriterion("nro_asignacion >=", value, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionLessThan(Integer value) {
            addCriterion("nro_asignacion <", value, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionLessThanOrEqualTo(Integer value) {
            addCriterion("nro_asignacion <=", value, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionIn(List<Integer> values) {
            addCriterion("nro_asignacion in", values, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionNotIn(List<Integer> values) {
            addCriterion("nro_asignacion not in", values, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionBetween(Integer value1, Integer value2) {
            addCriterion("nro_asignacion between", value1, value2, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andNroAsignacionNotBetween(Integer value1, Integer value2) {
            addCriterion("nro_asignacion not between", value1, value2, "nroAsignacion");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andNroInternoIsNull() {
            addCriterion("nro_interno is null");
            return (Criteria) this;
        }

        public Criteria andNroInternoIsNotNull() {
            addCriterion("nro_interno is not null");
            return (Criteria) this;
        }

        public Criteria andNroInternoEqualTo(String value) {
            addCriterion("nro_interno =", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoNotEqualTo(String value) {
            addCriterion("nro_interno <>", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoGreaterThan(String value) {
            addCriterion("nro_interno >", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoGreaterThanOrEqualTo(String value) {
            addCriterion("nro_interno >=", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoLessThan(String value) {
            addCriterion("nro_interno <", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoLessThanOrEqualTo(String value) {
            addCriterion("nro_interno <=", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoLike(String value) {
            addCriterion("nro_interno like", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoNotLike(String value) {
            addCriterion("nro_interno not like", value, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoIn(List<String> values) {
            addCriterion("nro_interno in", values, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoNotIn(List<String> values) {
            addCriterion("nro_interno not in", values, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoBetween(String value1, String value2) {
            addCriterion("nro_interno between", value1, value2, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andNroInternoNotBetween(String value1, String value2) {
            addCriterion("nro_interno not between", value1, value2, "nroInterno");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoIsNull() {
            addCriterion("tipo_vehiculo is null");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoIsNotNull() {
            addCriterion("tipo_vehiculo is not null");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoEqualTo(String value) {
            addCriterion("tipo_vehiculo =", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoNotEqualTo(String value) {
            addCriterion("tipo_vehiculo <>", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoGreaterThan(String value) {
            addCriterion("tipo_vehiculo >", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoGreaterThanOrEqualTo(String value) {
            addCriterion("tipo_vehiculo >=", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoLessThan(String value) {
            addCriterion("tipo_vehiculo <", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoLessThanOrEqualTo(String value) {
            addCriterion("tipo_vehiculo <=", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoLike(String value) {
            addCriterion("tipo_vehiculo like", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoNotLike(String value) {
            addCriterion("tipo_vehiculo not like", value, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoIn(List<String> values) {
            addCriterion("tipo_vehiculo in", values, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoNotIn(List<String> values) {
            addCriterion("tipo_vehiculo not in", values, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoBetween(String value1, String value2) {
            addCriterion("tipo_vehiculo between", value1, value2, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoNotBetween(String value1, String value2) {
            addCriterion("tipo_vehiculo not between", value1, value2, "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoIsNull() {
            addCriterion("marca_vehiculo is null");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoIsNotNull() {
            addCriterion("marca_vehiculo is not null");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoEqualTo(String value) {
            addCriterion("marca_vehiculo =", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoNotEqualTo(String value) {
            addCriterion("marca_vehiculo <>", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoGreaterThan(String value) {
            addCriterion("marca_vehiculo >", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoGreaterThanOrEqualTo(String value) {
            addCriterion("marca_vehiculo >=", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoLessThan(String value) {
            addCriterion("marca_vehiculo <", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoLessThanOrEqualTo(String value) {
            addCriterion("marca_vehiculo <=", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoLike(String value) {
            addCriterion("marca_vehiculo like", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoNotLike(String value) {
            addCriterion("marca_vehiculo not like", value, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoIn(List<String> values) {
            addCriterion("marca_vehiculo in", values, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoNotIn(List<String> values) {
            addCriterion("marca_vehiculo not in", values, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoBetween(String value1, String value2) {
            addCriterion("marca_vehiculo between", value1, value2, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoNotBetween(String value1, String value2) {
            addCriterion("marca_vehiculo not between", value1, value2, "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoIsNull() {
            addCriterion("modelo_vehiculo is null");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoIsNotNull() {
            addCriterion("modelo_vehiculo is not null");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoEqualTo(String value) {
            addCriterion("modelo_vehiculo =", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoNotEqualTo(String value) {
            addCriterion("modelo_vehiculo <>", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoGreaterThan(String value) {
            addCriterion("modelo_vehiculo >", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoGreaterThanOrEqualTo(String value) {
            addCriterion("modelo_vehiculo >=", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoLessThan(String value) {
            addCriterion("modelo_vehiculo <", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoLessThanOrEqualTo(String value) {
            addCriterion("modelo_vehiculo <=", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoLike(String value) {
            addCriterion("modelo_vehiculo like", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoNotLike(String value) {
            addCriterion("modelo_vehiculo not like", value, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoIn(List<String> values) {
            addCriterion("modelo_vehiculo in", values, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoNotIn(List<String> values) {
            addCriterion("modelo_vehiculo not in", values, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoBetween(String value1, String value2) {
            addCriterion("modelo_vehiculo between", value1, value2, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoNotBetween(String value1, String value2) {
            addCriterion("modelo_vehiculo not between", value1, value2, "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andPlacaIsNull() {
            addCriterion("placa is null");
            return (Criteria) this;
        }

        public Criteria andPlacaIsNotNull() {
            addCriterion("placa is not null");
            return (Criteria) this;
        }

        public Criteria andPlacaEqualTo(String value) {
            addCriterion("placa =", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaNotEqualTo(String value) {
            addCriterion("placa <>", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaGreaterThan(String value) {
            addCriterion("placa >", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaGreaterThanOrEqualTo(String value) {
            addCriterion("placa >=", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaLessThan(String value) {
            addCriterion("placa <", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaLessThanOrEqualTo(String value) {
            addCriterion("placa <=", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaLike(String value) {
            addCriterion("placa like", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaNotLike(String value) {
            addCriterion("placa not like", value, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaIn(List<String> values) {
            addCriterion("placa in", values, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaNotIn(List<String> values) {
            addCriterion("placa not in", values, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaBetween(String value1, String value2) {
            addCriterion("placa between", value1, value2, "placa");
            return (Criteria) this;
        }

        public Criteria andPlacaNotBetween(String value1, String value2) {
            addCriterion("placa not between", value1, value2, "placa");
            return (Criteria) this;
        }

        public Criteria andTipoRadioIsNull() {
            addCriterion("tipo_radio is null");
            return (Criteria) this;
        }

        public Criteria andTipoRadioIsNotNull() {
            addCriterion("tipo_radio is not null");
            return (Criteria) this;
        }

        public Criteria andTipoRadioEqualTo(String value) {
            addCriterion("tipo_radio =", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioNotEqualTo(String value) {
            addCriterion("tipo_radio <>", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioGreaterThan(String value) {
            addCriterion("tipo_radio >", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioGreaterThanOrEqualTo(String value) {
            addCriterion("tipo_radio >=", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioLessThan(String value) {
            addCriterion("tipo_radio <", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioLessThanOrEqualTo(String value) {
            addCriterion("tipo_radio <=", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioLike(String value) {
            addCriterion("tipo_radio like", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioNotLike(String value) {
            addCriterion("tipo_radio not like", value, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioIn(List<String> values) {
            addCriterion("tipo_radio in", values, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioNotIn(List<String> values) {
            addCriterion("tipo_radio not in", values, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioBetween(String value1, String value2) {
            addCriterion("tipo_radio between", value1, value2, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andTipoRadioNotBetween(String value1, String value2) {
            addCriterion("tipo_radio not between", value1, value2, "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioIsNull() {
            addCriterion("modelo_radio is null");
            return (Criteria) this;
        }

        public Criteria andModeloRadioIsNotNull() {
            addCriterion("modelo_radio is not null");
            return (Criteria) this;
        }

        public Criteria andModeloRadioEqualTo(String value) {
            addCriterion("modelo_radio =", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioNotEqualTo(String value) {
            addCriterion("modelo_radio <>", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioGreaterThan(String value) {
            addCriterion("modelo_radio >", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioGreaterThanOrEqualTo(String value) {
            addCriterion("modelo_radio >=", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioLessThan(String value) {
            addCriterion("modelo_radio <", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioLessThanOrEqualTo(String value) {
            addCriterion("modelo_radio <=", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioLike(String value) {
            addCriterion("modelo_radio like", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioNotLike(String value) {
            addCriterion("modelo_radio not like", value, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioIn(List<String> values) {
            addCriterion("modelo_radio in", values, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioNotIn(List<String> values) {
            addCriterion("modelo_radio not in", values, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioBetween(String value1, String value2) {
            addCriterion("modelo_radio between", value1, value2, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioNotBetween(String value1, String value2) {
            addCriterion("modelo_radio not between", value1, value2, "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andZonaIsNull() {
            addCriterion("zona is null");
            return (Criteria) this;
        }

        public Criteria andZonaIsNotNull() {
            addCriterion("zona is not null");
            return (Criteria) this;
        }

        public Criteria andZonaEqualTo(String value) {
            addCriterion("zona =", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaNotEqualTo(String value) {
            addCriterion("zona <>", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaGreaterThan(String value) {
            addCriterion("zona >", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaGreaterThanOrEqualTo(String value) {
            addCriterion("zona >=", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaLessThan(String value) {
            addCriterion("zona <", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaLessThanOrEqualTo(String value) {
            addCriterion("zona <=", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaLike(String value) {
            addCriterion("zona like", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaNotLike(String value) {
            addCriterion("zona not like", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaIn(List<String> values) {
            addCriterion("zona in", values, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaNotIn(List<String> values) {
            addCriterion("zona not in", values, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaBetween(String value1, String value2) {
            addCriterion("zona between", value1, value2, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaNotBetween(String value1, String value2) {
            addCriterion("zona not between", value1, value2, "zona");
            return (Criteria) this;
        }

        public Criteria andSubZonaIsNull() {
            addCriterion("sub_zona is null");
            return (Criteria) this;
        }

        public Criteria andSubZonaIsNotNull() {
            addCriterion("sub_zona is not null");
            return (Criteria) this;
        }

        public Criteria andSubZonaEqualTo(String value) {
            addCriterion("sub_zona =", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotEqualTo(String value) {
            addCriterion("sub_zona <>", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaGreaterThan(String value) {
            addCriterion("sub_zona >", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaGreaterThanOrEqualTo(String value) {
            addCriterion("sub_zona >=", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLessThan(String value) {
            addCriterion("sub_zona <", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLessThanOrEqualTo(String value) {
            addCriterion("sub_zona <=", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLike(String value) {
            addCriterion("sub_zona like", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotLike(String value) {
            addCriterion("sub_zona not like", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaIn(List<String> values) {
            addCriterion("sub_zona in", values, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotIn(List<String> values) {
            addCriterion("sub_zona not in", values, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaBetween(String value1, String value2) {
            addCriterion("sub_zona between", value1, value2, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotBetween(String value1, String value2) {
            addCriterion("sub_zona not between", value1, value2, "subZona");
            return (Criteria) this;
        }

        public Criteria andAreaLikeInsensitive(String value) {
            addCriterion("upper(area) like", value.toUpperCase(), "area");
            return (Criteria) this;
        }

        public Criteria andNroInternoLikeInsensitive(String value) {
            addCriterion("upper(nro_interno) like", value.toUpperCase(), "nroInterno");
            return (Criteria) this;
        }

        public Criteria andTipoVehiculoLikeInsensitive(String value) {
            addCriterion("upper(tipo_vehiculo) like", value.toUpperCase(), "tipoVehiculo");
            return (Criteria) this;
        }

        public Criteria andMarcaVehiculoLikeInsensitive(String value) {
            addCriterion("upper(marca_vehiculo) like", value.toUpperCase(), "marcaVehiculo");
            return (Criteria) this;
        }

        public Criteria andModeloVehiculoLikeInsensitive(String value) {
            addCriterion("upper(modelo_vehiculo) like", value.toUpperCase(), "modeloVehiculo");
            return (Criteria) this;
        }

        public Criteria andPlacaLikeInsensitive(String value) {
            addCriterion("upper(placa) like", value.toUpperCase(), "placa");
            return (Criteria) this;
        }

        public Criteria andTipoRadioLikeInsensitive(String value) {
            addCriterion("upper(tipo_radio) like", value.toUpperCase(), "tipoRadio");
            return (Criteria) this;
        }

        public Criteria andModeloRadioLikeInsensitive(String value) {
            addCriterion("upper(modelo_radio) like", value.toUpperCase(), "modeloRadio");
            return (Criteria) this;
        }

        public Criteria andZonaLikeInsensitive(String value) {
            addCriterion("upper(zona) like", value.toUpperCase(), "zona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLikeInsensitive(String value) {
            addCriterion("upper(sub_zona) like", value.toUpperCase(), "subZona");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 12 14:43:42 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}