package pe.gob.miraflores.mobile.domain.mapaincidencias;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MapaEstadisticaCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    public MapaEstadisticaCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaIsNull() {
            addCriterion("id_incidencia is null");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaIsNotNull() {
            addCriterion("id_incidencia is not null");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaEqualTo(Integer value) {
            addCriterion("id_incidencia =", value, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaNotEqualTo(Integer value) {
            addCriterion("id_incidencia <>", value, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaGreaterThan(Integer value) {
            addCriterion("id_incidencia >", value, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_incidencia >=", value, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaLessThan(Integer value) {
            addCriterion("id_incidencia <", value, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaLessThanOrEqualTo(Integer value) {
            addCriterion("id_incidencia <=", value, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaIn(List<Integer> values) {
            addCriterion("id_incidencia in", values, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaNotIn(List<Integer> values) {
            addCriterion("id_incidencia not in", values, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaBetween(Integer value1, Integer value2) {
            addCriterion("id_incidencia between", value1, value2, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andIdIncidenciaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_incidencia not between", value1, value2, "idIncidencia");
            return (Criteria) this;
        }

        public Criteria andNroCasoVoxivaIsNull() {
            addCriterion("nro_caso_voxiva is null");
            return (Criteria) this;
        }

        public Criteria andNroCasoVoxivaIsNotNull() {
            addCriterion("nro_caso_voxiva is not null");
            return (Criteria) this;
        }

        public Criteria andNroCasoVoxivaEqualTo(Integer value) {
            addCriterion("nro_caso_voxiva =", value, "nroCasoVoxiva");
            return (Criteria) this;
        }

        public Criteria andNroCasoVoxivaNotEqualTo(Integer value) {
            addCriterion("nro_caso_voxiva <>", value, "nroCasoVoxiva");
            return (Criteria) this;
        }

        public Criteria andNroCasoVoxivaGreaterThan(Integer value) {
            addCriterion("nro_caso_voxiva >", value, "nroCasoVoxiva");
            return (Criteria) this;
        }

        public Criteria andNroCasoVoxivaGreaterThanOrEqualTo(Integer value) {
            addCriterion("nro_caso_voxiva >=", value, "nroCasoVoxiva");
            return (Criteria) this;
        }

        public Criteria andNroCasoVoxivaLessThan(Integer value) {
            addCriterion("nro_caso_voxiva <", value, "nroCasoVoxiva");
            return (Criteria) this;
        }

        public Criteria andNroCasoVoxivaLessThanOrEqualTo(Integer value) {
            addCriterion("nro_caso_voxiva <=", value, "nroCasoVoxiva");
            return (Criteria) this;
        }

        public Criteria andNroCasoVoxivaIn(List<Integer> values) {
            addCriterion("nro_caso_voxiva in", values, "nroCasoVoxiva");
            return (Criteria) this;
        }

        public Criteria andNroCasoVoxivaNotIn(List<Integer> values) {
            addCriterion("nro_caso_voxiva not in", values, "nroCasoVoxiva");
            return (Criteria) this;
        }

        public Criteria andNroCasoVoxivaBetween(Integer value1, Integer value2) {
            addCriterion("nro_caso_voxiva between", value1, value2, "nroCasoVoxiva");
            return (Criteria) this;
        }

        public Criteria andNroCasoVoxivaNotBetween(Integer value1, Integer value2) {
            addCriterion("nro_caso_voxiva not between", value1, value2, "nroCasoVoxiva");
            return (Criteria) this;
        }

        public Criteria andIdVoxivaIsNull() {
            addCriterion("id_voxiva is null");
            return (Criteria) this;
        }

        public Criteria andIdVoxivaIsNotNull() {
            addCriterion("id_voxiva is not null");
            return (Criteria) this;
        }

        public Criteria andIdVoxivaEqualTo(Integer value) {
            addCriterion("id_voxiva =", value, "idVoxiva");
            return (Criteria) this;
        }

        public Criteria andIdVoxivaNotEqualTo(Integer value) {
            addCriterion("id_voxiva <>", value, "idVoxiva");
            return (Criteria) this;
        }

        public Criteria andIdVoxivaGreaterThan(Integer value) {
            addCriterion("id_voxiva >", value, "idVoxiva");
            return (Criteria) this;
        }

        public Criteria andIdVoxivaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_voxiva >=", value, "idVoxiva");
            return (Criteria) this;
        }

        public Criteria andIdVoxivaLessThan(Integer value) {
            addCriterion("id_voxiva <", value, "idVoxiva");
            return (Criteria) this;
        }

        public Criteria andIdVoxivaLessThanOrEqualTo(Integer value) {
            addCriterion("id_voxiva <=", value, "idVoxiva");
            return (Criteria) this;
        }

        public Criteria andIdVoxivaIn(List<Integer> values) {
            addCriterion("id_voxiva in", values, "idVoxiva");
            return (Criteria) this;
        }

        public Criteria andIdVoxivaNotIn(List<Integer> values) {
            addCriterion("id_voxiva not in", values, "idVoxiva");
            return (Criteria) this;
        }

        public Criteria andIdVoxivaBetween(Integer value1, Integer value2) {
            addCriterion("id_voxiva between", value1, value2, "idVoxiva");
            return (Criteria) this;
        }

        public Criteria andIdVoxivaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_voxiva not between", value1, value2, "idVoxiva");
            return (Criteria) this;
        }

        public Criteria andCodUnidadIsNull() {
            addCriterion("cod_unidad is null");
            return (Criteria) this;
        }

        public Criteria andCodUnidadIsNotNull() {
            addCriterion("cod_unidad is not null");
            return (Criteria) this;
        }

        public Criteria andCodUnidadEqualTo(Integer value) {
            addCriterion("cod_unidad =", value, "codUnidad");
            return (Criteria) this;
        }

        public Criteria andCodUnidadNotEqualTo(Integer value) {
            addCriterion("cod_unidad <>", value, "codUnidad");
            return (Criteria) this;
        }

        public Criteria andCodUnidadGreaterThan(Integer value) {
            addCriterion("cod_unidad >", value, "codUnidad");
            return (Criteria) this;
        }

        public Criteria andCodUnidadGreaterThanOrEqualTo(Integer value) {
            addCriterion("cod_unidad >=", value, "codUnidad");
            return (Criteria) this;
        }

        public Criteria andCodUnidadLessThan(Integer value) {
            addCriterion("cod_unidad <", value, "codUnidad");
            return (Criteria) this;
        }

        public Criteria andCodUnidadLessThanOrEqualTo(Integer value) {
            addCriterion("cod_unidad <=", value, "codUnidad");
            return (Criteria) this;
        }

        public Criteria andCodUnidadIn(List<Integer> values) {
            addCriterion("cod_unidad in", values, "codUnidad");
            return (Criteria) this;
        }

        public Criteria andCodUnidadNotIn(List<Integer> values) {
            addCriterion("cod_unidad not in", values, "codUnidad");
            return (Criteria) this;
        }

        public Criteria andCodUnidadBetween(Integer value1, Integer value2) {
            addCriterion("cod_unidad between", value1, value2, "codUnidad");
            return (Criteria) this;
        }

        public Criteria andCodUnidadNotBetween(Integer value1, Integer value2) {
            addCriterion("cod_unidad not between", value1, value2, "codUnidad");
            return (Criteria) this;
        }

        public Criteria andCodCasoIsNull() {
            addCriterion("cod_caso is null");
            return (Criteria) this;
        }

        public Criteria andCodCasoIsNotNull() {
            addCriterion("cod_caso is not null");
            return (Criteria) this;
        }

        public Criteria andCodCasoEqualTo(Integer value) {
            addCriterion("cod_caso =", value, "codCaso");
            return (Criteria) this;
        }

        public Criteria andCodCasoNotEqualTo(Integer value) {
            addCriterion("cod_caso <>", value, "codCaso");
            return (Criteria) this;
        }

        public Criteria andCodCasoGreaterThan(Integer value) {
            addCriterion("cod_caso >", value, "codCaso");
            return (Criteria) this;
        }

        public Criteria andCodCasoGreaterThanOrEqualTo(Integer value) {
            addCriterion("cod_caso >=", value, "codCaso");
            return (Criteria) this;
        }

        public Criteria andCodCasoLessThan(Integer value) {
            addCriterion("cod_caso <", value, "codCaso");
            return (Criteria) this;
        }

        public Criteria andCodCasoLessThanOrEqualTo(Integer value) {
            addCriterion("cod_caso <=", value, "codCaso");
            return (Criteria) this;
        }

        public Criteria andCodCasoIn(List<Integer> values) {
            addCriterion("cod_caso in", values, "codCaso");
            return (Criteria) this;
        }

        public Criteria andCodCasoNotIn(List<Integer> values) {
            addCriterion("cod_caso not in", values, "codCaso");
            return (Criteria) this;
        }

        public Criteria andCodCasoBetween(Integer value1, Integer value2) {
            addCriterion("cod_caso between", value1, value2, "codCaso");
            return (Criteria) this;
        }

        public Criteria andCodCasoNotBetween(Integer value1, Integer value2) {
            addCriterion("cod_caso not between", value1, value2, "codCaso");
            return (Criteria) this;
        }

        public Criteria andCodSubcasoIsNull() {
            addCriterion("cod_subcaso is null");
            return (Criteria) this;
        }

        public Criteria andCodSubcasoIsNotNull() {
            addCriterion("cod_subcaso is not null");
            return (Criteria) this;
        }

        public Criteria andCodSubcasoEqualTo(Integer value) {
            addCriterion("cod_subcaso =", value, "codSubcaso");
            return (Criteria) this;
        }

        public Criteria andCodSubcasoNotEqualTo(Integer value) {
            addCriterion("cod_subcaso <>", value, "codSubcaso");
            return (Criteria) this;
        }

        public Criteria andCodSubcasoGreaterThan(Integer value) {
            addCriterion("cod_subcaso >", value, "codSubcaso");
            return (Criteria) this;
        }

        public Criteria andCodSubcasoGreaterThanOrEqualTo(Integer value) {
            addCriterion("cod_subcaso >=", value, "codSubcaso");
            return (Criteria) this;
        }

        public Criteria andCodSubcasoLessThan(Integer value) {
            addCriterion("cod_subcaso <", value, "codSubcaso");
            return (Criteria) this;
        }

        public Criteria andCodSubcasoLessThanOrEqualTo(Integer value) {
            addCriterion("cod_subcaso <=", value, "codSubcaso");
            return (Criteria) this;
        }

        public Criteria andCodSubcasoIn(List<Integer> values) {
            addCriterion("cod_subcaso in", values, "codSubcaso");
            return (Criteria) this;
        }

        public Criteria andCodSubcasoNotIn(List<Integer> values) {
            addCriterion("cod_subcaso not in", values, "codSubcaso");
            return (Criteria) this;
        }

        public Criteria andCodSubcasoBetween(Integer value1, Integer value2) {
            addCriterion("cod_subcaso between", value1, value2, "codSubcaso");
            return (Criteria) this;
        }

        public Criteria andCodSubcasoNotBetween(Integer value1, Integer value2) {
            addCriterion("cod_subcaso not between", value1, value2, "codSubcaso");
            return (Criteria) this;
        }

        public Criteria andFechaIsNull() {
            addCriterion("fecha is null");
            return (Criteria) this;
        }

        public Criteria andFechaIsNotNull() {
            addCriterion("fecha is not null");
            return (Criteria) this;
        }

        public Criteria andFechaEqualTo(Date value) {
            addCriterion("fecha =", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotEqualTo(Date value) {
            addCriterion("fecha <>", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThan(Date value) {
            addCriterion("fecha >", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha >=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThan(Date value) {
            addCriterion("fecha <", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaLessThanOrEqualTo(Date value) {
            addCriterion("fecha <=", value, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaIn(List<Date> values) {
            addCriterion("fecha in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotIn(List<Date> values) {
            addCriterion("fecha not in", values, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaBetween(Date value1, Date value2) {
            addCriterion("fecha between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andFechaNotBetween(Date value1, Date value2) {
            addCriterion("fecha not between", value1, value2, "fecha");
            return (Criteria) this;
        }

        public Criteria andHoraIsNull() {
            addCriterion("hora is null");
            return (Criteria) this;
        }

        public Criteria andHoraIsNotNull() {
            addCriterion("hora is not null");
            return (Criteria) this;
        }

        public Criteria andHoraEqualTo(Integer value) {
            addCriterion("hora =", value, "hora");
            return (Criteria) this;
        }

        public Criteria andHoraNotEqualTo(Integer value) {
            addCriterion("hora <>", value, "hora");
            return (Criteria) this;
        }

        public Criteria andHoraGreaterThan(Integer value) {
            addCriterion("hora >", value, "hora");
            return (Criteria) this;
        }

        public Criteria andHoraGreaterThanOrEqualTo(Integer value) {
            addCriterion("hora >=", value, "hora");
            return (Criteria) this;
        }

        public Criteria andHoraLessThan(Integer value) {
            addCriterion("hora <", value, "hora");
            return (Criteria) this;
        }

        public Criteria andHoraLessThanOrEqualTo(Integer value) {
            addCriterion("hora <=", value, "hora");
            return (Criteria) this;
        }

        public Criteria andHoraIn(List<Integer> values) {
            addCriterion("hora in", values, "hora");
            return (Criteria) this;
        }

        public Criteria andHoraNotIn(List<Integer> values) {
            addCriterion("hora not in", values, "hora");
            return (Criteria) this;
        }

        public Criteria andHoraBetween(Integer value1, Integer value2) {
            addCriterion("hora between", value1, value2, "hora");
            return (Criteria) this;
        }

        public Criteria andHoraNotBetween(Integer value1, Integer value2) {
            addCriterion("hora not between", value1, value2, "hora");
            return (Criteria) this;
        }

        public Criteria andDiaIsNull() {
            addCriterion("dia is null");
            return (Criteria) this;
        }

        public Criteria andDiaIsNotNull() {
            addCriterion("dia is not null");
            return (Criteria) this;
        }

        public Criteria andDiaEqualTo(Integer value) {
            addCriterion("dia =", value, "dia");
            return (Criteria) this;
        }

        public Criteria andDiaNotEqualTo(Integer value) {
            addCriterion("dia <>", value, "dia");
            return (Criteria) this;
        }

        public Criteria andDiaGreaterThan(Integer value) {
            addCriterion("dia >", value, "dia");
            return (Criteria) this;
        }

        public Criteria andDiaGreaterThanOrEqualTo(Integer value) {
            addCriterion("dia >=", value, "dia");
            return (Criteria) this;
        }

        public Criteria andDiaLessThan(Integer value) {
            addCriterion("dia <", value, "dia");
            return (Criteria) this;
        }

        public Criteria andDiaLessThanOrEqualTo(Integer value) {
            addCriterion("dia <=", value, "dia");
            return (Criteria) this;
        }

        public Criteria andDiaIn(List<Integer> values) {
            addCriterion("dia in", values, "dia");
            return (Criteria) this;
        }

        public Criteria andDiaNotIn(List<Integer> values) {
            addCriterion("dia not in", values, "dia");
            return (Criteria) this;
        }

        public Criteria andDiaBetween(Integer value1, Integer value2) {
            addCriterion("dia between", value1, value2, "dia");
            return (Criteria) this;
        }

        public Criteria andDiaNotBetween(Integer value1, Integer value2) {
            addCriterion("dia not between", value1, value2, "dia");
            return (Criteria) this;
        }

        public Criteria andMesIsNull() {
            addCriterion("mes is null");
            return (Criteria) this;
        }

        public Criteria andMesIsNotNull() {
            addCriterion("mes is not null");
            return (Criteria) this;
        }

        public Criteria andMesEqualTo(Integer value) {
            addCriterion("mes =", value, "mes");
            return (Criteria) this;
        }

        public Criteria andMesNotEqualTo(Integer value) {
            addCriterion("mes <>", value, "mes");
            return (Criteria) this;
        }

        public Criteria andMesGreaterThan(Integer value) {
            addCriterion("mes >", value, "mes");
            return (Criteria) this;
        }

        public Criteria andMesGreaterThanOrEqualTo(Integer value) {
            addCriterion("mes >=", value, "mes");
            return (Criteria) this;
        }

        public Criteria andMesLessThan(Integer value) {
            addCriterion("mes <", value, "mes");
            return (Criteria) this;
        }

        public Criteria andMesLessThanOrEqualTo(Integer value) {
            addCriterion("mes <=", value, "mes");
            return (Criteria) this;
        }

        public Criteria andMesIn(List<Integer> values) {
            addCriterion("mes in", values, "mes");
            return (Criteria) this;
        }

        public Criteria andMesNotIn(List<Integer> values) {
            addCriterion("mes not in", values, "mes");
            return (Criteria) this;
        }

        public Criteria andMesBetween(Integer value1, Integer value2) {
            addCriterion("mes between", value1, value2, "mes");
            return (Criteria) this;
        }

        public Criteria andMesNotBetween(Integer value1, Integer value2) {
            addCriterion("mes not between", value1, value2, "mes");
            return (Criteria) this;
        }

        public Criteria andAnioIsNull() {
            addCriterion("anio is null");
            return (Criteria) this;
        }

        public Criteria andAnioIsNotNull() {
            addCriterion("anio is not null");
            return (Criteria) this;
        }

        public Criteria andAnioEqualTo(Integer value) {
            addCriterion("anio =", value, "anio");
            return (Criteria) this;
        }

        public Criteria andAnioNotEqualTo(Integer value) {
            addCriterion("anio <>", value, "anio");
            return (Criteria) this;
        }

        public Criteria andAnioGreaterThan(Integer value) {
            addCriterion("anio >", value, "anio");
            return (Criteria) this;
        }

        public Criteria andAnioGreaterThanOrEqualTo(Integer value) {
            addCriterion("anio >=", value, "anio");
            return (Criteria) this;
        }

        public Criteria andAnioLessThan(Integer value) {
            addCriterion("anio <", value, "anio");
            return (Criteria) this;
        }

        public Criteria andAnioLessThanOrEqualTo(Integer value) {
            addCriterion("anio <=", value, "anio");
            return (Criteria) this;
        }

        public Criteria andAnioIn(List<Integer> values) {
            addCriterion("anio in", values, "anio");
            return (Criteria) this;
        }

        public Criteria andAnioNotIn(List<Integer> values) {
            addCriterion("anio not in", values, "anio");
            return (Criteria) this;
        }

        public Criteria andAnioBetween(Integer value1, Integer value2) {
            addCriterion("anio between", value1, value2, "anio");
            return (Criteria) this;
        }

        public Criteria andAnioNotBetween(Integer value1, Integer value2) {
            addCriterion("anio not between", value1, value2, "anio");
            return (Criteria) this;
        }

        public Criteria andNombDiaIsNull() {
            addCriterion("nomb_dia is null");
            return (Criteria) this;
        }

        public Criteria andNombDiaIsNotNull() {
            addCriterion("nomb_dia is not null");
            return (Criteria) this;
        }

        public Criteria andNombDiaEqualTo(String value) {
            addCriterion("nomb_dia =", value, "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombDiaNotEqualTo(String value) {
            addCriterion("nomb_dia <>", value, "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombDiaGreaterThan(String value) {
            addCriterion("nomb_dia >", value, "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombDiaGreaterThanOrEqualTo(String value) {
            addCriterion("nomb_dia >=", value, "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombDiaLessThan(String value) {
            addCriterion("nomb_dia <", value, "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombDiaLessThanOrEqualTo(String value) {
            addCriterion("nomb_dia <=", value, "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombDiaLike(String value) {
            addCriterion("nomb_dia like", value, "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombDiaNotLike(String value) {
            addCriterion("nomb_dia not like", value, "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombDiaIn(List<String> values) {
            addCriterion("nomb_dia in", values, "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombDiaNotIn(List<String> values) {
            addCriterion("nomb_dia not in", values, "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombDiaBetween(String value1, String value2) {
            addCriterion("nomb_dia between", value1, value2, "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombDiaNotBetween(String value1, String value2) {
            addCriterion("nomb_dia not between", value1, value2, "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombMesIsNull() {
            addCriterion("nomb_mes is null");
            return (Criteria) this;
        }

        public Criteria andNombMesIsNotNull() {
            addCriterion("nomb_mes is not null");
            return (Criteria) this;
        }

        public Criteria andNombMesEqualTo(String value) {
            addCriterion("nomb_mes =", value, "nombMes");
            return (Criteria) this;
        }

        public Criteria andNombMesNotEqualTo(String value) {
            addCriterion("nomb_mes <>", value, "nombMes");
            return (Criteria) this;
        }

        public Criteria andNombMesGreaterThan(String value) {
            addCriterion("nomb_mes >", value, "nombMes");
            return (Criteria) this;
        }

        public Criteria andNombMesGreaterThanOrEqualTo(String value) {
            addCriterion("nomb_mes >=", value, "nombMes");
            return (Criteria) this;
        }

        public Criteria andNombMesLessThan(String value) {
            addCriterion("nomb_mes <", value, "nombMes");
            return (Criteria) this;
        }

        public Criteria andNombMesLessThanOrEqualTo(String value) {
            addCriterion("nomb_mes <=", value, "nombMes");
            return (Criteria) this;
        }

        public Criteria andNombMesLike(String value) {
            addCriterion("nomb_mes like", value, "nombMes");
            return (Criteria) this;
        }

        public Criteria andNombMesNotLike(String value) {
            addCriterion("nomb_mes not like", value, "nombMes");
            return (Criteria) this;
        }

        public Criteria andNombMesIn(List<String> values) {
            addCriterion("nomb_mes in", values, "nombMes");
            return (Criteria) this;
        }

        public Criteria andNombMesNotIn(List<String> values) {
            addCriterion("nomb_mes not in", values, "nombMes");
            return (Criteria) this;
        }

        public Criteria andNombMesBetween(String value1, String value2) {
            addCriterion("nomb_mes between", value1, value2, "nombMes");
            return (Criteria) this;
        }

        public Criteria andNombMesNotBetween(String value1, String value2) {
            addCriterion("nomb_mes not between", value1, value2, "nombMes");
            return (Criteria) this;
        }

        public Criteria andValorIsNull() {
            addCriterion("valor is null");
            return (Criteria) this;
        }

        public Criteria andValorIsNotNull() {
            addCriterion("valor is not null");
            return (Criteria) this;
        }

        public Criteria andValorEqualTo(Integer value) {
            addCriterion("valor =", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorNotEqualTo(Integer value) {
            addCriterion("valor <>", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorGreaterThan(Integer value) {
            addCriterion("valor >", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorGreaterThanOrEqualTo(Integer value) {
            addCriterion("valor >=", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorLessThan(Integer value) {
            addCriterion("valor <", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorLessThanOrEqualTo(Integer value) {
            addCriterion("valor <=", value, "valor");
            return (Criteria) this;
        }

        public Criteria andValorIn(List<Integer> values) {
            addCriterion("valor in", values, "valor");
            return (Criteria) this;
        }

        public Criteria andValorNotIn(List<Integer> values) {
            addCriterion("valor not in", values, "valor");
            return (Criteria) this;
        }

        public Criteria andValorBetween(Integer value1, Integer value2) {
            addCriterion("valor between", value1, value2, "valor");
            return (Criteria) this;
        }

        public Criteria andValorNotBetween(Integer value1, Integer value2) {
            addCriterion("valor not between", value1, value2, "valor");
            return (Criteria) this;
        }

        public Criteria andCodEstadoIsNull() {
            addCriterion("cod_estado is null");
            return (Criteria) this;
        }

        public Criteria andCodEstadoIsNotNull() {
            addCriterion("cod_estado is not null");
            return (Criteria) this;
        }

        public Criteria andCodEstadoEqualTo(Integer value) {
            addCriterion("cod_estado =", value, "codEstado");
            return (Criteria) this;
        }

        public Criteria andCodEstadoNotEqualTo(Integer value) {
            addCriterion("cod_estado <>", value, "codEstado");
            return (Criteria) this;
        }

        public Criteria andCodEstadoGreaterThan(Integer value) {
            addCriterion("cod_estado >", value, "codEstado");
            return (Criteria) this;
        }

        public Criteria andCodEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("cod_estado >=", value, "codEstado");
            return (Criteria) this;
        }

        public Criteria andCodEstadoLessThan(Integer value) {
            addCriterion("cod_estado <", value, "codEstado");
            return (Criteria) this;
        }

        public Criteria andCodEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("cod_estado <=", value, "codEstado");
            return (Criteria) this;
        }

        public Criteria andCodEstadoIn(List<Integer> values) {
            addCriterion("cod_estado in", values, "codEstado");
            return (Criteria) this;
        }

        public Criteria andCodEstadoNotIn(List<Integer> values) {
            addCriterion("cod_estado not in", values, "codEstado");
            return (Criteria) this;
        }

        public Criteria andCodEstadoBetween(Integer value1, Integer value2) {
            addCriterion("cod_estado between", value1, value2, "codEstado");
            return (Criteria) this;
        }

        public Criteria andCodEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("cod_estado not between", value1, value2, "codEstado");
            return (Criteria) this;
        }

        public Criteria andCodSubestadoIsNull() {
            addCriterion("cod_subestado is null");
            return (Criteria) this;
        }

        public Criteria andCodSubestadoIsNotNull() {
            addCriterion("cod_subestado is not null");
            return (Criteria) this;
        }

        public Criteria andCodSubestadoEqualTo(Integer value) {
            addCriterion("cod_subestado =", value, "codSubestado");
            return (Criteria) this;
        }

        public Criteria andCodSubestadoNotEqualTo(Integer value) {
            addCriterion("cod_subestado <>", value, "codSubestado");
            return (Criteria) this;
        }

        public Criteria andCodSubestadoGreaterThan(Integer value) {
            addCriterion("cod_subestado >", value, "codSubestado");
            return (Criteria) this;
        }

        public Criteria andCodSubestadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("cod_subestado >=", value, "codSubestado");
            return (Criteria) this;
        }

        public Criteria andCodSubestadoLessThan(Integer value) {
            addCriterion("cod_subestado <", value, "codSubestado");
            return (Criteria) this;
        }

        public Criteria andCodSubestadoLessThanOrEqualTo(Integer value) {
            addCriterion("cod_subestado <=", value, "codSubestado");
            return (Criteria) this;
        }

        public Criteria andCodSubestadoIn(List<Integer> values) {
            addCriterion("cod_subestado in", values, "codSubestado");
            return (Criteria) this;
        }

        public Criteria andCodSubestadoNotIn(List<Integer> values) {
            addCriterion("cod_subestado not in", values, "codSubestado");
            return (Criteria) this;
        }

        public Criteria andCodSubestadoBetween(Integer value1, Integer value2) {
            addCriterion("cod_subestado between", value1, value2, "codSubestado");
            return (Criteria) this;
        }

        public Criteria andCodSubestadoNotBetween(Integer value1, Integer value2) {
            addCriterion("cod_subestado not between", value1, value2, "codSubestado");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andZonaIsNull() {
            addCriterion("zona is null");
            return (Criteria) this;
        }

        public Criteria andZonaIsNotNull() {
            addCriterion("zona is not null");
            return (Criteria) this;
        }

        public Criteria andZonaEqualTo(String value) {
            addCriterion("zona =", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaNotEqualTo(String value) {
            addCriterion("zona <>", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaGreaterThan(String value) {
            addCriterion("zona >", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaGreaterThanOrEqualTo(String value) {
            addCriterion("zona >=", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaLessThan(String value) {
            addCriterion("zona <", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaLessThanOrEqualTo(String value) {
            addCriterion("zona <=", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaLike(String value) {
            addCriterion("zona like", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaNotLike(String value) {
            addCriterion("zona not like", value, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaIn(List<String> values) {
            addCriterion("zona in", values, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaNotIn(List<String> values) {
            addCriterion("zona not in", values, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaBetween(String value1, String value2) {
            addCriterion("zona between", value1, value2, "zona");
            return (Criteria) this;
        }

        public Criteria andZonaNotBetween(String value1, String value2) {
            addCriterion("zona not between", value1, value2, "zona");
            return (Criteria) this;
        }

        public Criteria andSubzonaIsNull() {
            addCriterion("subzona is null");
            return (Criteria) this;
        }

        public Criteria andSubzonaIsNotNull() {
            addCriterion("subzona is not null");
            return (Criteria) this;
        }

        public Criteria andSubzonaEqualTo(String value) {
            addCriterion("subzona =", value, "subzona");
            return (Criteria) this;
        }

        public Criteria andSubzonaNotEqualTo(String value) {
            addCriterion("subzona <>", value, "subzona");
            return (Criteria) this;
        }

        public Criteria andSubzonaGreaterThan(String value) {
            addCriterion("subzona >", value, "subzona");
            return (Criteria) this;
        }

        public Criteria andSubzonaGreaterThanOrEqualTo(String value) {
            addCriterion("subzona >=", value, "subzona");
            return (Criteria) this;
        }

        public Criteria andSubzonaLessThan(String value) {
            addCriterion("subzona <", value, "subzona");
            return (Criteria) this;
        }

        public Criteria andSubzonaLessThanOrEqualTo(String value) {
            addCriterion("subzona <=", value, "subzona");
            return (Criteria) this;
        }

        public Criteria andSubzonaLike(String value) {
            addCriterion("subzona like", value, "subzona");
            return (Criteria) this;
        }

        public Criteria andSubzonaNotLike(String value) {
            addCriterion("subzona not like", value, "subzona");
            return (Criteria) this;
        }

        public Criteria andSubzonaIn(List<String> values) {
            addCriterion("subzona in", values, "subzona");
            return (Criteria) this;
        }

        public Criteria andSubzonaNotIn(List<String> values) {
            addCriterion("subzona not in", values, "subzona");
            return (Criteria) this;
        }

        public Criteria andSubzonaBetween(String value1, String value2) {
            addCriterion("subzona between", value1, value2, "subzona");
            return (Criteria) this;
        }

        public Criteria andSubzonaNotBetween(String value1, String value2) {
            addCriterion("subzona not between", value1, value2, "subzona");
            return (Criteria) this;
        }

        public Criteria andTpoViaIsNull() {
            addCriterion("tpo_via is null");
            return (Criteria) this;
        }

        public Criteria andTpoViaIsNotNull() {
            addCriterion("tpo_via is not null");
            return (Criteria) this;
        }

        public Criteria andTpoViaEqualTo(String value) {
            addCriterion("tpo_via =", value, "tpoVia");
            return (Criteria) this;
        }

        public Criteria andTpoViaNotEqualTo(String value) {
            addCriterion("tpo_via <>", value, "tpoVia");
            return (Criteria) this;
        }

        public Criteria andTpoViaGreaterThan(String value) {
            addCriterion("tpo_via >", value, "tpoVia");
            return (Criteria) this;
        }

        public Criteria andTpoViaGreaterThanOrEqualTo(String value) {
            addCriterion("tpo_via >=", value, "tpoVia");
            return (Criteria) this;
        }

        public Criteria andTpoViaLessThan(String value) {
            addCriterion("tpo_via <", value, "tpoVia");
            return (Criteria) this;
        }

        public Criteria andTpoViaLessThanOrEqualTo(String value) {
            addCriterion("tpo_via <=", value, "tpoVia");
            return (Criteria) this;
        }

        public Criteria andTpoViaLike(String value) {
            addCriterion("tpo_via like", value, "tpoVia");
            return (Criteria) this;
        }

        public Criteria andTpoViaNotLike(String value) {
            addCriterion("tpo_via not like", value, "tpoVia");
            return (Criteria) this;
        }

        public Criteria andTpoViaIn(List<String> values) {
            addCriterion("tpo_via in", values, "tpoVia");
            return (Criteria) this;
        }

        public Criteria andTpoViaNotIn(List<String> values) {
            addCriterion("tpo_via not in", values, "tpoVia");
            return (Criteria) this;
        }

        public Criteria andTpoViaBetween(String value1, String value2) {
            addCriterion("tpo_via between", value1, value2, "tpoVia");
            return (Criteria) this;
        }

        public Criteria andTpoViaNotBetween(String value1, String value2) {
            addCriterion("tpo_via not between", value1, value2, "tpoVia");
            return (Criteria) this;
        }

        public Criteria andNombViaIsNull() {
            addCriterion("nomb_via is null");
            return (Criteria) this;
        }

        public Criteria andNombViaIsNotNull() {
            addCriterion("nomb_via is not null");
            return (Criteria) this;
        }

        public Criteria andNombViaEqualTo(String value) {
            addCriterion("nomb_via =", value, "nombVia");
            return (Criteria) this;
        }

        public Criteria andNombViaNotEqualTo(String value) {
            addCriterion("nomb_via <>", value, "nombVia");
            return (Criteria) this;
        }

        public Criteria andNombViaGreaterThan(String value) {
            addCriterion("nomb_via >", value, "nombVia");
            return (Criteria) this;
        }

        public Criteria andNombViaGreaterThanOrEqualTo(String value) {
            addCriterion("nomb_via >=", value, "nombVia");
            return (Criteria) this;
        }

        public Criteria andNombViaLessThan(String value) {
            addCriterion("nomb_via <", value, "nombVia");
            return (Criteria) this;
        }

        public Criteria andNombViaLessThanOrEqualTo(String value) {
            addCriterion("nomb_via <=", value, "nombVia");
            return (Criteria) this;
        }

        public Criteria andNombViaLike(String value) {
            addCriterion("nomb_via like", value, "nombVia");
            return (Criteria) this;
        }

        public Criteria andNombViaNotLike(String value) {
            addCriterion("nomb_via not like", value, "nombVia");
            return (Criteria) this;
        }

        public Criteria andNombViaIn(List<String> values) {
            addCriterion("nomb_via in", values, "nombVia");
            return (Criteria) this;
        }

        public Criteria andNombViaNotIn(List<String> values) {
            addCriterion("nomb_via not in", values, "nombVia");
            return (Criteria) this;
        }

        public Criteria andNombViaBetween(String value1, String value2) {
            addCriterion("nomb_via between", value1, value2, "nombVia");
            return (Criteria) this;
        }

        public Criteria andNombViaNotBetween(String value1, String value2) {
            addCriterion("nomb_via not between", value1, value2, "nombVia");
            return (Criteria) this;
        }

        public Criteria andCdraIsNull() {
            addCriterion("cdra is null");
            return (Criteria) this;
        }

        public Criteria andCdraIsNotNull() {
            addCriterion("cdra is not null");
            return (Criteria) this;
        }

        public Criteria andCdraEqualTo(String value) {
            addCriterion("cdra =", value, "cdra");
            return (Criteria) this;
        }

        public Criteria andCdraNotEqualTo(String value) {
            addCriterion("cdra <>", value, "cdra");
            return (Criteria) this;
        }

        public Criteria andCdraGreaterThan(String value) {
            addCriterion("cdra >", value, "cdra");
            return (Criteria) this;
        }

        public Criteria andCdraGreaterThanOrEqualTo(String value) {
            addCriterion("cdra >=", value, "cdra");
            return (Criteria) this;
        }

        public Criteria andCdraLessThan(String value) {
            addCriterion("cdra <", value, "cdra");
            return (Criteria) this;
        }

        public Criteria andCdraLessThanOrEqualTo(String value) {
            addCriterion("cdra <=", value, "cdra");
            return (Criteria) this;
        }

        public Criteria andCdraLike(String value) {
            addCriterion("cdra like", value, "cdra");
            return (Criteria) this;
        }

        public Criteria andCdraNotLike(String value) {
            addCriterion("cdra not like", value, "cdra");
            return (Criteria) this;
        }

        public Criteria andCdraIn(List<String> values) {
            addCriterion("cdra in", values, "cdra");
            return (Criteria) this;
        }

        public Criteria andCdraNotIn(List<String> values) {
            addCriterion("cdra not in", values, "cdra");
            return (Criteria) this;
        }

        public Criteria andCdraBetween(String value1, String value2) {
            addCriterion("cdra between", value1, value2, "cdra");
            return (Criteria) this;
        }

        public Criteria andCdraNotBetween(String value1, String value2) {
            addCriterion("cdra not between", value1, value2, "cdra");
            return (Criteria) this;
        }

        public Criteria andCoordenadasIsNull() {
            addCriterion("coordenadas is null");
            return (Criteria) this;
        }

        public Criteria andCoordenadasIsNotNull() {
            addCriterion("coordenadas is not null");
            return (Criteria) this;
        }

        public Criteria andCoordenadasEqualTo(String value) {
            addCriterion("coordenadas =", value, "coordenadas");
            return (Criteria) this;
        }

        public Criteria andCoordenadasNotEqualTo(String value) {
            addCriterion("coordenadas <>", value, "coordenadas");
            return (Criteria) this;
        }

        public Criteria andCoordenadasGreaterThan(String value) {
            addCriterion("coordenadas >", value, "coordenadas");
            return (Criteria) this;
        }

        public Criteria andCoordenadasGreaterThanOrEqualTo(String value) {
            addCriterion("coordenadas >=", value, "coordenadas");
            return (Criteria) this;
        }

        public Criteria andCoordenadasLessThan(String value) {
            addCriterion("coordenadas <", value, "coordenadas");
            return (Criteria) this;
        }

        public Criteria andCoordenadasLessThanOrEqualTo(String value) {
            addCriterion("coordenadas <=", value, "coordenadas");
            return (Criteria) this;
        }

        public Criteria andCoordenadasLike(String value) {
            addCriterion("coordenadas like", value, "coordenadas");
            return (Criteria) this;
        }

        public Criteria andCoordenadasNotLike(String value) {
            addCriterion("coordenadas not like", value, "coordenadas");
            return (Criteria) this;
        }

        public Criteria andCoordenadasIn(List<String> values) {
            addCriterion("coordenadas in", values, "coordenadas");
            return (Criteria) this;
        }

        public Criteria andCoordenadasNotIn(List<String> values) {
            addCriterion("coordenadas not in", values, "coordenadas");
            return (Criteria) this;
        }

        public Criteria andCoordenadasBetween(String value1, String value2) {
            addCriterion("coordenadas between", value1, value2, "coordenadas");
            return (Criteria) this;
        }

        public Criteria andCoordenadasNotBetween(String value1, String value2) {
            addCriterion("coordenadas not between", value1, value2, "coordenadas");
            return (Criteria) this;
        }

        public Criteria andLongitudIsNull() {
            addCriterion("longitud is null");
            return (Criteria) this;
        }

        public Criteria andLongitudIsNotNull() {
            addCriterion("longitud is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudEqualTo(String value) {
            addCriterion("longitud =", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotEqualTo(String value) {
            addCriterion("longitud <>", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudGreaterThan(String value) {
            addCriterion("longitud >", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudGreaterThanOrEqualTo(String value) {
            addCriterion("longitud >=", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudLessThan(String value) {
            addCriterion("longitud <", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudLessThanOrEqualTo(String value) {
            addCriterion("longitud <=", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudLike(String value) {
            addCriterion("longitud like", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotLike(String value) {
            addCriterion("longitud not like", value, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudIn(List<String> values) {
            addCriterion("longitud in", values, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotIn(List<String> values) {
            addCriterion("longitud not in", values, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudBetween(String value1, String value2) {
            addCriterion("longitud between", value1, value2, "longitud");
            return (Criteria) this;
        }

        public Criteria andLongitudNotBetween(String value1, String value2) {
            addCriterion("longitud not between", value1, value2, "longitud");
            return (Criteria) this;
        }

        public Criteria andLatitudIsNull() {
            addCriterion("latitud is null");
            return (Criteria) this;
        }

        public Criteria andLatitudIsNotNull() {
            addCriterion("latitud is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudEqualTo(String value) {
            addCriterion("latitud =", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotEqualTo(String value) {
            addCriterion("latitud <>", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudGreaterThan(String value) {
            addCriterion("latitud >", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudGreaterThanOrEqualTo(String value) {
            addCriterion("latitud >=", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudLessThan(String value) {
            addCriterion("latitud <", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudLessThanOrEqualTo(String value) {
            addCriterion("latitud <=", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudLike(String value) {
            addCriterion("latitud like", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotLike(String value) {
            addCriterion("latitud not like", value, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudIn(List<String> values) {
            addCriterion("latitud in", values, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotIn(List<String> values) {
            addCriterion("latitud not in", values, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudBetween(String value1, String value2) {
            addCriterion("latitud between", value1, value2, "latitud");
            return (Criteria) this;
        }

        public Criteria andLatitudNotBetween(String value1, String value2) {
            addCriterion("latitud not between", value1, value2, "latitud");
            return (Criteria) this;
        }

        public Criteria andDescUnidadIsNull() {
            addCriterion("desc_unidad is null");
            return (Criteria) this;
        }

        public Criteria andDescUnidadIsNotNull() {
            addCriterion("desc_unidad is not null");
            return (Criteria) this;
        }

        public Criteria andDescUnidadEqualTo(String value) {
            addCriterion("desc_unidad =", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadNotEqualTo(String value) {
            addCriterion("desc_unidad <>", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadGreaterThan(String value) {
            addCriterion("desc_unidad >", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadGreaterThanOrEqualTo(String value) {
            addCriterion("desc_unidad >=", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadLessThan(String value) {
            addCriterion("desc_unidad <", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadLessThanOrEqualTo(String value) {
            addCriterion("desc_unidad <=", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadLike(String value) {
            addCriterion("desc_unidad like", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadNotLike(String value) {
            addCriterion("desc_unidad not like", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadIn(List<String> values) {
            addCriterion("desc_unidad in", values, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadNotIn(List<String> values) {
            addCriterion("desc_unidad not in", values, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadBetween(String value1, String value2) {
            addCriterion("desc_unidad between", value1, value2, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadNotBetween(String value1, String value2) {
            addCriterion("desc_unidad not between", value1, value2, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescCasoIsNull() {
            addCriterion("desc_caso is null");
            return (Criteria) this;
        }

        public Criteria andDescCasoIsNotNull() {
            addCriterion("desc_caso is not null");
            return (Criteria) this;
        }

        public Criteria andDescCasoEqualTo(String value) {
            addCriterion("desc_caso =", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoNotEqualTo(String value) {
            addCriterion("desc_caso <>", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoGreaterThan(String value) {
            addCriterion("desc_caso >", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoGreaterThanOrEqualTo(String value) {
            addCriterion("desc_caso >=", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoLessThan(String value) {
            addCriterion("desc_caso <", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoLessThanOrEqualTo(String value) {
            addCriterion("desc_caso <=", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoLike(String value) {
            addCriterion("desc_caso like", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoNotLike(String value) {
            addCriterion("desc_caso not like", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoIn(List<String> values) {
            addCriterion("desc_caso in", values, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoNotIn(List<String> values) {
            addCriterion("desc_caso not in", values, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoBetween(String value1, String value2) {
            addCriterion("desc_caso between", value1, value2, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoNotBetween(String value1, String value2) {
            addCriterion("desc_caso not between", value1, value2, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoIsNull() {
            addCriterion("desc_subcaso is null");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoIsNotNull() {
            addCriterion("desc_subcaso is not null");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoEqualTo(String value) {
            addCriterion("desc_subcaso =", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoNotEqualTo(String value) {
            addCriterion("desc_subcaso <>", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoGreaterThan(String value) {
            addCriterion("desc_subcaso >", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoGreaterThanOrEqualTo(String value) {
            addCriterion("desc_subcaso >=", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoLessThan(String value) {
            addCriterion("desc_subcaso <", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoLessThanOrEqualTo(String value) {
            addCriterion("desc_subcaso <=", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoLike(String value) {
            addCriterion("desc_subcaso like", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoNotLike(String value) {
            addCriterion("desc_subcaso not like", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoIn(List<String> values) {
            addCriterion("desc_subcaso in", values, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoNotIn(List<String> values) {
            addCriterion("desc_subcaso not in", values, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoBetween(String value1, String value2) {
            addCriterion("desc_subcaso between", value1, value2, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoNotBetween(String value1, String value2) {
            addCriterion("desc_subcaso not between", value1, value2, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andNombDiaLikeInsensitive(String value) {
            addCriterion("upper(nomb_dia) like", value.toUpperCase(), "nombDia");
            return (Criteria) this;
        }

        public Criteria andNombMesLikeInsensitive(String value) {
            addCriterion("upper(nomb_mes) like", value.toUpperCase(), "nombMes");
            return (Criteria) this;
        }

        public Criteria andAreaLikeInsensitive(String value) {
            addCriterion("upper(area) like", value.toUpperCase(), "area");
            return (Criteria) this;
        }

        public Criteria andZonaLikeInsensitive(String value) {
            addCriterion("upper(zona) like", value.toUpperCase(), "zona");
            return (Criteria) this;
        }

        public Criteria andSubzonaLikeInsensitive(String value) {
            addCriterion("upper(subzona) like", value.toUpperCase(), "subzona");
            return (Criteria) this;
        }

        public Criteria andTpoViaLikeInsensitive(String value) {
            addCriterion("upper(tpo_via) like", value.toUpperCase(), "tpoVia");
            return (Criteria) this;
        }

        public Criteria andNombViaLikeInsensitive(String value) {
            addCriterion("upper(nomb_via) like", value.toUpperCase(), "nombVia");
            return (Criteria) this;
        }

        public Criteria andCdraLikeInsensitive(String value) {
            addCriterion("upper(cdra) like", value.toUpperCase(), "cdra");
            return (Criteria) this;
        }

        public Criteria andCoordenadasLikeInsensitive(String value) {
            addCriterion("upper(coordenadas) like", value.toUpperCase(), "coordenadas");
            return (Criteria) this;
        }

        public Criteria andLongitudLikeInsensitive(String value) {
            addCriterion("upper(longitud) like", value.toUpperCase(), "longitud");
            return (Criteria) this;
        }

        public Criteria andLatitudLikeInsensitive(String value) {
            addCriterion("upper(latitud) like", value.toUpperCase(), "latitud");
            return (Criteria) this;
        }

        public Criteria andDescUnidadLikeInsensitive(String value) {
            addCriterion("upper(desc_unidad) like", value.toUpperCase(), "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescCasoLikeInsensitive(String value) {
            addCriterion("upper(desc_caso) like", value.toUpperCase(), "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoLikeInsensitive(String value) {
            addCriterion("upper(desc_subcaso) like", value.toUpperCase(), "descSubcaso");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 16 14:03:03 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}