package pe.gob.miraflores.mobile.domain.mapaincidencias;

import java.util.ArrayList;
import java.util.List;

public class MapaCasoCriteria {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	public MapaCasoCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCodCasoIsNull() {
			addCriterion("cod_caso is null");
			return (Criteria) this;
		}

		public Criteria andCodCasoIsNotNull() {
			addCriterion("cod_caso is not null");
			return (Criteria) this;
		}

		public Criteria andCodCasoEqualTo(Integer value) {
			addCriterion("cod_caso =", value, "codCaso");
			return (Criteria) this;
		}

		public Criteria andCodCasoNotEqualTo(Integer value) {
			addCriterion("cod_caso <>", value, "codCaso");
			return (Criteria) this;
		}

		public Criteria andCodCasoGreaterThan(Integer value) {
			addCriterion("cod_caso >", value, "codCaso");
			return (Criteria) this;
		}

		public Criteria andCodCasoGreaterThanOrEqualTo(Integer value) {
			addCriterion("cod_caso >=", value, "codCaso");
			return (Criteria) this;
		}

		public Criteria andCodCasoLessThan(Integer value) {
			addCriterion("cod_caso <", value, "codCaso");
			return (Criteria) this;
		}

		public Criteria andCodCasoLessThanOrEqualTo(Integer value) {
			addCriterion("cod_caso <=", value, "codCaso");
			return (Criteria) this;
		}

		public Criteria andCodCasoIn(List<Integer> values) {
			addCriterion("cod_caso in", values, "codCaso");
			return (Criteria) this;
		}

		public Criteria andCodCasoNotIn(List<Integer> values) {
			addCriterion("cod_caso not in", values, "codCaso");
			return (Criteria) this;
		}

		public Criteria andCodCasoBetween(Integer value1, Integer value2) {
			addCriterion("cod_caso between", value1, value2, "codCaso");
			return (Criteria) this;
		}

		public Criteria andCodCasoNotBetween(Integer value1, Integer value2) {
			addCriterion("cod_caso not between", value1, value2, "codCaso");
			return (Criteria) this;
		}

		public Criteria andCodUnidadIsNull() {
			addCriterion("cod_unidad is null");
			return (Criteria) this;
		}

		public Criteria andCodUnidadIsNotNull() {
			addCriterion("cod_unidad is not null");
			return (Criteria) this;
		}

		public Criteria andCodUnidadEqualTo(Integer value) {
			addCriterion("cod_unidad =", value, "codUnidad");
			return (Criteria) this;
		}

		public Criteria andCodUnidadNotEqualTo(Integer value) {
			addCriterion("cod_unidad <>", value, "codUnidad");
			return (Criteria) this;
		}

		public Criteria andCodUnidadGreaterThan(Integer value) {
			addCriterion("cod_unidad >", value, "codUnidad");
			return (Criteria) this;
		}

		public Criteria andCodUnidadGreaterThanOrEqualTo(Integer value) {
			addCriterion("cod_unidad >=", value, "codUnidad");
			return (Criteria) this;
		}

		public Criteria andCodUnidadLessThan(Integer value) {
			addCriterion("cod_unidad <", value, "codUnidad");
			return (Criteria) this;
		}

		public Criteria andCodUnidadLessThanOrEqualTo(Integer value) {
			addCriterion("cod_unidad <=", value, "codUnidad");
			return (Criteria) this;
		}

		public Criteria andCodUnidadIn(List<Integer> values) {
			addCriterion("cod_unidad in", values, "codUnidad");
			return (Criteria) this;
		}

		public Criteria andCodUnidadNotIn(List<Integer> values) {
			addCriterion("cod_unidad not in", values, "codUnidad");
			return (Criteria) this;
		}

		public Criteria andCodUnidadBetween(Integer value1, Integer value2) {
			addCriterion("cod_unidad between", value1, value2, "codUnidad");
			return (Criteria) this;
		}

		public Criteria andCodUnidadNotBetween(Integer value1, Integer value2) {
			addCriterion("cod_unidad not between", value1, value2, "codUnidad");
			return (Criteria) this;
		}

		public Criteria andDescCasoIsNull() {
			addCriterion("desc_caso is null");
			return (Criteria) this;
		}

		public Criteria andDescCasoIsNotNull() {
			addCriterion("desc_caso is not null");
			return (Criteria) this;
		}

		public Criteria andDescCasoEqualTo(String value) {
			addCriterion("desc_caso =", value, "descCaso");
			return (Criteria) this;
		}

		public Criteria andDescCasoNotEqualTo(String value) {
			addCriterion("desc_caso <>", value, "descCaso");
			return (Criteria) this;
		}

		public Criteria andDescCasoGreaterThan(String value) {
			addCriterion("desc_caso >", value, "descCaso");
			return (Criteria) this;
		}

		public Criteria andDescCasoGreaterThanOrEqualTo(String value) {
			addCriterion("desc_caso >=", value, "descCaso");
			return (Criteria) this;
		}

		public Criteria andDescCasoLessThan(String value) {
			addCriterion("desc_caso <", value, "descCaso");
			return (Criteria) this;
		}

		public Criteria andDescCasoLessThanOrEqualTo(String value) {
			addCriterion("desc_caso <=", value, "descCaso");
			return (Criteria) this;
		}

		public Criteria andDescCasoLike(String value) {
			addCriterion("desc_caso like", value, "descCaso");
			return (Criteria) this;
		}

		public Criteria andDescCasoNotLike(String value) {
			addCriterion("desc_caso not like", value, "descCaso");
			return (Criteria) this;
		}

		public Criteria andDescCasoIn(List<String> values) {
			addCriterion("desc_caso in", values, "descCaso");
			return (Criteria) this;
		}

		public Criteria andDescCasoNotIn(List<String> values) {
			addCriterion("desc_caso not in", values, "descCaso");
			return (Criteria) this;
		}

		public Criteria andDescCasoBetween(String value1, String value2) {
			addCriterion("desc_caso between", value1, value2, "descCaso");
			return (Criteria) this;
		}

		public Criteria andDescCasoNotBetween(String value1, String value2) {
			addCriterion("desc_caso not between", value1, value2, "descCaso");
			return (Criteria) this;
		}

		public Criteria andEstRegIsNull() {
			addCriterion("est_reg is null");
			return (Criteria) this;
		}

		public Criteria andEstRegIsNotNull() {
			addCriterion("est_reg is not null");
			return (Criteria) this;
		}

		public Criteria andEstRegEqualTo(String value) {
			addCriterion("est_reg =", value, "estReg");
			return (Criteria) this;
		}

		public Criteria andEstRegNotEqualTo(String value) {
			addCriterion("est_reg <>", value, "estReg");
			return (Criteria) this;
		}

		public Criteria andEstRegGreaterThan(String value) {
			addCriterion("est_reg >", value, "estReg");
			return (Criteria) this;
		}

		public Criteria andEstRegGreaterThanOrEqualTo(String value) {
			addCriterion("est_reg >=", value, "estReg");
			return (Criteria) this;
		}

		public Criteria andEstRegLessThan(String value) {
			addCriterion("est_reg <", value, "estReg");
			return (Criteria) this;
		}

		public Criteria andEstRegLessThanOrEqualTo(String value) {
			addCriterion("est_reg <=", value, "estReg");
			return (Criteria) this;
		}

		public Criteria andEstRegLike(String value) {
			addCriterion("est_reg like", value, "estReg");
			return (Criteria) this;
		}

		public Criteria andEstRegNotLike(String value) {
			addCriterion("est_reg not like", value, "estReg");
			return (Criteria) this;
		}

		public Criteria andEstRegIn(List<String> values) {
			addCriterion("est_reg in", values, "estReg");
			return (Criteria) this;
		}

		public Criteria andEstRegNotIn(List<String> values) {
			addCriterion("est_reg not in", values, "estReg");
			return (Criteria) this;
		}

		public Criteria andEstRegBetween(String value1, String value2) {
			addCriterion("est_reg between", value1, value2, "estReg");
			return (Criteria) this;
		}

		public Criteria andEstRegNotBetween(String value1, String value2) {
			addCriterion("est_reg not between", value1, value2, "estReg");
			return (Criteria) this;
		}

		public Criteria andDescCasoLikeInsensitive(String value) {
			addCriterion("upper(desc_caso) like", value.toUpperCase(), "descCaso");
			return (Criteria) this;
		}

		public Criteria andEstRegLikeInsensitive(String value) {
			addCriterion("upper(est_reg) like", value.toUpperCase(), "estReg");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.geo_map_caso
     *
     * @mbg.generated do_not_delete_during_merge Sat Jul 08 16:57:38 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}