package pe.gob.miraflores.mobile.domain.mapaincidencias;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PreInscripcionCierreCalleCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    public PreInscripcionCierreCalleCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDireccionIsNull() {
            addCriterion("direccion is null");
            return (Criteria) this;
        }

        public Criteria andDireccionIsNotNull() {
            addCriterion("direccion is not null");
            return (Criteria) this;
        }

        public Criteria andDireccionEqualTo(String value) {
            addCriterion("direccion =", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionNotEqualTo(String value) {
            addCriterion("direccion <>", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionGreaterThan(String value) {
            addCriterion("direccion >", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionGreaterThanOrEqualTo(String value) {
            addCriterion("direccion >=", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionLessThan(String value) {
            addCriterion("direccion <", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionLessThanOrEqualTo(String value) {
            addCriterion("direccion <=", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionLike(String value) {
            addCriterion("direccion like", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionNotLike(String value) {
            addCriterion("direccion not like", value, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionIn(List<String> values) {
            addCriterion("direccion in", values, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionNotIn(List<String> values) {
            addCriterion("direccion not in", values, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionBetween(String value1, String value2) {
            addCriterion("direccion between", value1, value2, "direccion");
            return (Criteria) this;
        }

        public Criteria andDireccionNotBetween(String value1, String value2) {
            addCriterion("direccion not between", value1, value2, "direccion");
            return (Criteria) this;
        }

        public Criteria andCuadraIsNull() {
            addCriterion("cuadra is null");
            return (Criteria) this;
        }

        public Criteria andCuadraIsNotNull() {
            addCriterion("cuadra is not null");
            return (Criteria) this;
        }

        public Criteria andCuadraEqualTo(String value) {
            addCriterion("cuadra =", value, "cuadra");
            return (Criteria) this;
        }

        public Criteria andCuadraNotEqualTo(String value) {
            addCriterion("cuadra <>", value, "cuadra");
            return (Criteria) this;
        }

        public Criteria andCuadraGreaterThan(String value) {
            addCriterion("cuadra >", value, "cuadra");
            return (Criteria) this;
        }

        public Criteria andCuadraGreaterThanOrEqualTo(String value) {
            addCriterion("cuadra >=", value, "cuadra");
            return (Criteria) this;
        }

        public Criteria andCuadraLessThan(String value) {
            addCriterion("cuadra <", value, "cuadra");
            return (Criteria) this;
        }

        public Criteria andCuadraLessThanOrEqualTo(String value) {
            addCriterion("cuadra <=", value, "cuadra");
            return (Criteria) this;
        }

        public Criteria andCuadraLike(String value) {
            addCriterion("cuadra like", value, "cuadra");
            return (Criteria) this;
        }

        public Criteria andCuadraNotLike(String value) {
            addCriterion("cuadra not like", value, "cuadra");
            return (Criteria) this;
        }

        public Criteria andCuadraIn(List<String> values) {
            addCriterion("cuadra in", values, "cuadra");
            return (Criteria) this;
        }

        public Criteria andCuadraNotIn(List<String> values) {
            addCriterion("cuadra not in", values, "cuadra");
            return (Criteria) this;
        }

        public Criteria andCuadraBetween(String value1, String value2) {
            addCriterion("cuadra between", value1, value2, "cuadra");
            return (Criteria) this;
        }

        public Criteria andCuadraNotBetween(String value1, String value2) {
            addCriterion("cuadra not between", value1, value2, "cuadra");
            return (Criteria) this;
        }

        public Criteria andMotivoIsNull() {
            addCriterion("motivo is null");
            return (Criteria) this;
        }

        public Criteria andMotivoIsNotNull() {
            addCriterion("motivo is not null");
            return (Criteria) this;
        }

        public Criteria andMotivoEqualTo(String value) {
            addCriterion("motivo =", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoNotEqualTo(String value) {
            addCriterion("motivo <>", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoGreaterThan(String value) {
            addCriterion("motivo >", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoGreaterThanOrEqualTo(String value) {
            addCriterion("motivo >=", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoLessThan(String value) {
            addCriterion("motivo <", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoLessThanOrEqualTo(String value) {
            addCriterion("motivo <=", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoLike(String value) {
            addCriterion("motivo like", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoNotLike(String value) {
            addCriterion("motivo not like", value, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoIn(List<String> values) {
            addCriterion("motivo in", values, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoNotIn(List<String> values) {
            addCriterion("motivo not in", values, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoBetween(String value1, String value2) {
            addCriterion("motivo between", value1, value2, "motivo");
            return (Criteria) this;
        }

        public Criteria andMotivoNotBetween(String value1, String value2) {
            addCriterion("motivo not between", value1, value2, "motivo");
            return (Criteria) this;
        }

        public Criteria andEmpresaIsNull() {
            addCriterion("empresa is null");
            return (Criteria) this;
        }

        public Criteria andEmpresaIsNotNull() {
            addCriterion("empresa is not null");
            return (Criteria) this;
        }

        public Criteria andEmpresaEqualTo(String value) {
            addCriterion("empresa =", value, "empresa");
            return (Criteria) this;
        }

        public Criteria andEmpresaNotEqualTo(String value) {
            addCriterion("empresa <>", value, "empresa");
            return (Criteria) this;
        }

        public Criteria andEmpresaGreaterThan(String value) {
            addCriterion("empresa >", value, "empresa");
            return (Criteria) this;
        }

        public Criteria andEmpresaGreaterThanOrEqualTo(String value) {
            addCriterion("empresa >=", value, "empresa");
            return (Criteria) this;
        }

        public Criteria andEmpresaLessThan(String value) {
            addCriterion("empresa <", value, "empresa");
            return (Criteria) this;
        }

        public Criteria andEmpresaLessThanOrEqualTo(String value) {
            addCriterion("empresa <=", value, "empresa");
            return (Criteria) this;
        }

        public Criteria andEmpresaLike(String value) {
            addCriterion("empresa like", value, "empresa");
            return (Criteria) this;
        }

        public Criteria andEmpresaNotLike(String value) {
            addCriterion("empresa not like", value, "empresa");
            return (Criteria) this;
        }

        public Criteria andEmpresaIn(List<String> values) {
            addCriterion("empresa in", values, "empresa");
            return (Criteria) this;
        }

        public Criteria andEmpresaNotIn(List<String> values) {
            addCriterion("empresa not in", values, "empresa");
            return (Criteria) this;
        }

        public Criteria andEmpresaBetween(String value1, String value2) {
            addCriterion("empresa between", value1, value2, "empresa");
            return (Criteria) this;
        }

        public Criteria andEmpresaNotBetween(String value1, String value2) {
            addCriterion("empresa not between", value1, value2, "empresa");
            return (Criteria) this;
        }

        public Criteria andIdentGrupoIsNull() {
            addCriterion("ident_grupo is null");
            return (Criteria) this;
        }

        public Criteria andIdentGrupoIsNotNull() {
            addCriterion("ident_grupo is not null");
            return (Criteria) this;
        }

        public Criteria andIdentGrupoEqualTo(Integer value) {
            addCriterion("ident_grupo =", value, "identGrupo");
            return (Criteria) this;
        }

        public Criteria andIdentGrupoNotEqualTo(Integer value) {
            addCriterion("ident_grupo <>", value, "identGrupo");
            return (Criteria) this;
        }

        public Criteria andIdentGrupoGreaterThan(Integer value) {
            addCriterion("ident_grupo >", value, "identGrupo");
            return (Criteria) this;
        }

        public Criteria andIdentGrupoGreaterThanOrEqualTo(Integer value) {
            addCriterion("ident_grupo >=", value, "identGrupo");
            return (Criteria) this;
        }

        public Criteria andIdentGrupoLessThan(Integer value) {
            addCriterion("ident_grupo <", value, "identGrupo");
            return (Criteria) this;
        }

        public Criteria andIdentGrupoLessThanOrEqualTo(Integer value) {
            addCriterion("ident_grupo <=", value, "identGrupo");
            return (Criteria) this;
        }

        public Criteria andIdentGrupoIn(List<Integer> values) {
            addCriterion("ident_grupo in", values, "identGrupo");
            return (Criteria) this;
        }

        public Criteria andIdentGrupoNotIn(List<Integer> values) {
            addCriterion("ident_grupo not in", values, "identGrupo");
            return (Criteria) this;
        }

        public Criteria andIdentGrupoBetween(Integer value1, Integer value2) {
            addCriterion("ident_grupo between", value1, value2, "identGrupo");
            return (Criteria) this;
        }

        public Criteria andIdentGrupoNotBetween(Integer value1, Integer value2) {
            addCriterion("ident_grupo not between", value1, value2, "identGrupo");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("estado is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("estado is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(Integer value) {
            addCriterion("estado =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(Integer value) {
            addCriterion("estado <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(Integer value) {
            addCriterion("estado >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(Integer value) {
            addCriterion("estado >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(Integer value) {
            addCriterion("estado <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(Integer value) {
            addCriterion("estado <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<Integer> values) {
            addCriterion("estado in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<Integer> values) {
            addCriterion("estado not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(Integer value1, Integer value2) {
            addCriterion("estado between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(Integer value1, Integer value2) {
            addCriterion("estado not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andFecRegistroIsNull() {
            addCriterion("fec_registro is null");
            return (Criteria) this;
        }

        public Criteria andFecRegistroIsNotNull() {
            addCriterion("fec_registro is not null");
            return (Criteria) this;
        }

        public Criteria andFecRegistroEqualTo(Date value) {
            addCriterion("fec_registro =", value, "fecRegistro");
            return (Criteria) this;
        }

        public Criteria andFecRegistroNotEqualTo(Date value) {
            addCriterion("fec_registro <>", value, "fecRegistro");
            return (Criteria) this;
        }

        public Criteria andFecRegistroGreaterThan(Date value) {
            addCriterion("fec_registro >", value, "fecRegistro");
            return (Criteria) this;
        }

        public Criteria andFecRegistroGreaterThanOrEqualTo(Date value) {
            addCriterion("fec_registro >=", value, "fecRegistro");
            return (Criteria) this;
        }

        public Criteria andFecRegistroLessThan(Date value) {
            addCriterion("fec_registro <", value, "fecRegistro");
            return (Criteria) this;
        }

        public Criteria andFecRegistroLessThanOrEqualTo(Date value) {
            addCriterion("fec_registro <=", value, "fecRegistro");
            return (Criteria) this;
        }

        public Criteria andFecRegistroIn(List<Date> values) {
            addCriterion("fec_registro in", values, "fecRegistro");
            return (Criteria) this;
        }

        public Criteria andFecRegistroNotIn(List<Date> values) {
            addCriterion("fec_registro not in", values, "fecRegistro");
            return (Criteria) this;
        }

        public Criteria andFecRegistroBetween(Date value1, Date value2) {
            addCriterion("fec_registro between", value1, value2, "fecRegistro");
            return (Criteria) this;
        }

        public Criteria andFecRegistroNotBetween(Date value1, Date value2) {
            addCriterion("fec_registro not between", value1, value2, "fecRegistro");
            return (Criteria) this;
        }

        public Criteria andFecModificacionIsNull() {
            addCriterion("fec_modificacion is null");
            return (Criteria) this;
        }

        public Criteria andFecModificacionIsNotNull() {
            addCriterion("fec_modificacion is not null");
            return (Criteria) this;
        }

        public Criteria andFecModificacionEqualTo(Date value) {
            addCriterion("fec_modificacion =", value, "fecModificacion");
            return (Criteria) this;
        }

        public Criteria andFecModificacionNotEqualTo(Date value) {
            addCriterion("fec_modificacion <>", value, "fecModificacion");
            return (Criteria) this;
        }

        public Criteria andFecModificacionGreaterThan(Date value) {
            addCriterion("fec_modificacion >", value, "fecModificacion");
            return (Criteria) this;
        }

        public Criteria andFecModificacionGreaterThanOrEqualTo(Date value) {
            addCriterion("fec_modificacion >=", value, "fecModificacion");
            return (Criteria) this;
        }

        public Criteria andFecModificacionLessThan(Date value) {
            addCriterion("fec_modificacion <", value, "fecModificacion");
            return (Criteria) this;
        }

        public Criteria andFecModificacionLessThanOrEqualTo(Date value) {
            addCriterion("fec_modificacion <=", value, "fecModificacion");
            return (Criteria) this;
        }

        public Criteria andFecModificacionIn(List<Date> values) {
            addCriterion("fec_modificacion in", values, "fecModificacion");
            return (Criteria) this;
        }

        public Criteria andFecModificacionNotIn(List<Date> values) {
            addCriterion("fec_modificacion not in", values, "fecModificacion");
            return (Criteria) this;
        }

        public Criteria andFecModificacionBetween(Date value1, Date value2) {
            addCriterion("fec_modificacion between", value1, value2, "fecModificacion");
            return (Criteria) this;
        }

        public Criteria andFecModificacionNotBetween(Date value1, Date value2) {
            addCriterion("fec_modificacion not between", value1, value2, "fecModificacion");
            return (Criteria) this;
        }

        public Criteria andIpRegistroIsNull() {
            addCriterion("ip_registro is null");
            return (Criteria) this;
        }

        public Criteria andIpRegistroIsNotNull() {
            addCriterion("ip_registro is not null");
            return (Criteria) this;
        }

        public Criteria andIpRegistroEqualTo(String value) {
            addCriterion("ip_registro =", value, "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpRegistroNotEqualTo(String value) {
            addCriterion("ip_registro <>", value, "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpRegistroGreaterThan(String value) {
            addCriterion("ip_registro >", value, "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpRegistroGreaterThanOrEqualTo(String value) {
            addCriterion("ip_registro >=", value, "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpRegistroLessThan(String value) {
            addCriterion("ip_registro <", value, "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpRegistroLessThanOrEqualTo(String value) {
            addCriterion("ip_registro <=", value, "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpRegistroLike(String value) {
            addCriterion("ip_registro like", value, "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpRegistroNotLike(String value) {
            addCriterion("ip_registro not like", value, "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpRegistroIn(List<String> values) {
            addCriterion("ip_registro in", values, "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpRegistroNotIn(List<String> values) {
            addCriterion("ip_registro not in", values, "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpRegistroBetween(String value1, String value2) {
            addCriterion("ip_registro between", value1, value2, "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpRegistroNotBetween(String value1, String value2) {
            addCriterion("ip_registro not between", value1, value2, "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpModificacionIsNull() {
            addCriterion("ip_modificacion is null");
            return (Criteria) this;
        }

        public Criteria andIpModificacionIsNotNull() {
            addCriterion("ip_modificacion is not null");
            return (Criteria) this;
        }

        public Criteria andIpModificacionEqualTo(String value) {
            addCriterion("ip_modificacion =", value, "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andIpModificacionNotEqualTo(String value) {
            addCriterion("ip_modificacion <>", value, "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andIpModificacionGreaterThan(String value) {
            addCriterion("ip_modificacion >", value, "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andIpModificacionGreaterThanOrEqualTo(String value) {
            addCriterion("ip_modificacion >=", value, "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andIpModificacionLessThan(String value) {
            addCriterion("ip_modificacion <", value, "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andIpModificacionLessThanOrEqualTo(String value) {
            addCriterion("ip_modificacion <=", value, "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andIpModificacionLike(String value) {
            addCriterion("ip_modificacion like", value, "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andIpModificacionNotLike(String value) {
            addCriterion("ip_modificacion not like", value, "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andIpModificacionIn(List<String> values) {
            addCriterion("ip_modificacion in", values, "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andIpModificacionNotIn(List<String> values) {
            addCriterion("ip_modificacion not in", values, "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andIpModificacionBetween(String value1, String value2) {
            addCriterion("ip_modificacion between", value1, value2, "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andIpModificacionNotBetween(String value1, String value2) {
            addCriterion("ip_modificacion not between", value1, value2, "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteIsNull() {
            addCriterion("num_expediente is null");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteIsNotNull() {
            addCriterion("num_expediente is not null");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteEqualTo(String value) {
            addCriterion("num_expediente =", value, "numExpediente");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteNotEqualTo(String value) {
            addCriterion("num_expediente <>", value, "numExpediente");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteGreaterThan(String value) {
            addCriterion("num_expediente >", value, "numExpediente");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteGreaterThanOrEqualTo(String value) {
            addCriterion("num_expediente >=", value, "numExpediente");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteLessThan(String value) {
            addCriterion("num_expediente <", value, "numExpediente");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteLessThanOrEqualTo(String value) {
            addCriterion("num_expediente <=", value, "numExpediente");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteLike(String value) {
            addCriterion("num_expediente like", value, "numExpediente");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteNotLike(String value) {
            addCriterion("num_expediente not like", value, "numExpediente");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteIn(List<String> values) {
            addCriterion("num_expediente in", values, "numExpediente");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteNotIn(List<String> values) {
            addCriterion("num_expediente not in", values, "numExpediente");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteBetween(String value1, String value2) {
            addCriterion("num_expediente between", value1, value2, "numExpediente");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteNotBetween(String value1, String value2) {
            addCriterion("num_expediente not between", value1, value2, "numExpediente");
            return (Criteria) this;
        }

        public Criteria andAnioExpedienteIsNull() {
            addCriterion("anio_expediente is null");
            return (Criteria) this;
        }

        public Criteria andAnioExpedienteIsNotNull() {
            addCriterion("anio_expediente is not null");
            return (Criteria) this;
        }

        public Criteria andAnioExpedienteEqualTo(Integer value) {
            addCriterion("anio_expediente =", value, "anioExpediente");
            return (Criteria) this;
        }

        public Criteria andAnioExpedienteNotEqualTo(Integer value) {
            addCriterion("anio_expediente <>", value, "anioExpediente");
            return (Criteria) this;
        }

        public Criteria andAnioExpedienteGreaterThan(Integer value) {
            addCriterion("anio_expediente >", value, "anioExpediente");
            return (Criteria) this;
        }

        public Criteria andAnioExpedienteGreaterThanOrEqualTo(Integer value) {
            addCriterion("anio_expediente >=", value, "anioExpediente");
            return (Criteria) this;
        }

        public Criteria andAnioExpedienteLessThan(Integer value) {
            addCriterion("anio_expediente <", value, "anioExpediente");
            return (Criteria) this;
        }

        public Criteria andAnioExpedienteLessThanOrEqualTo(Integer value) {
            addCriterion("anio_expediente <=", value, "anioExpediente");
            return (Criteria) this;
        }

        public Criteria andAnioExpedienteIn(List<Integer> values) {
            addCriterion("anio_expediente in", values, "anioExpediente");
            return (Criteria) this;
        }

        public Criteria andAnioExpedienteNotIn(List<Integer> values) {
            addCriterion("anio_expediente not in", values, "anioExpediente");
            return (Criteria) this;
        }

        public Criteria andAnioExpedienteBetween(Integer value1, Integer value2) {
            addCriterion("anio_expediente between", value1, value2, "anioExpediente");
            return (Criteria) this;
        }

        public Criteria andAnioExpedienteNotBetween(Integer value1, Integer value2) {
            addCriterion("anio_expediente not between", value1, value2, "anioExpediente");
            return (Criteria) this;
        }

        public Criteria andIdReferenciaIsNull() {
            addCriterion("id_referencia is null");
            return (Criteria) this;
        }

        public Criteria andIdReferenciaIsNotNull() {
            addCriterion("id_referencia is not null");
            return (Criteria) this;
        }

        public Criteria andIdReferenciaEqualTo(Integer value) {
            addCriterion("id_referencia =", value, "idReferencia");
            return (Criteria) this;
        }

        public Criteria andIdReferenciaNotEqualTo(Integer value) {
            addCriterion("id_referencia <>", value, "idReferencia");
            return (Criteria) this;
        }

        public Criteria andIdReferenciaGreaterThan(Integer value) {
            addCriterion("id_referencia >", value, "idReferencia");
            return (Criteria) this;
        }

        public Criteria andIdReferenciaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_referencia >=", value, "idReferencia");
            return (Criteria) this;
        }

        public Criteria andIdReferenciaLessThan(Integer value) {
            addCriterion("id_referencia <", value, "idReferencia");
            return (Criteria) this;
        }

        public Criteria andIdReferenciaLessThanOrEqualTo(Integer value) {
            addCriterion("id_referencia <=", value, "idReferencia");
            return (Criteria) this;
        }

        public Criteria andIdReferenciaIn(List<Integer> values) {
            addCriterion("id_referencia in", values, "idReferencia");
            return (Criteria) this;
        }

        public Criteria andIdReferenciaNotIn(List<Integer> values) {
            addCriterion("id_referencia not in", values, "idReferencia");
            return (Criteria) this;
        }

        public Criteria andIdReferenciaBetween(Integer value1, Integer value2) {
            addCriterion("id_referencia between", value1, value2, "idReferencia");
            return (Criteria) this;
        }

        public Criteria andIdReferenciaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_referencia not between", value1, value2, "idReferencia");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionIsNull() {
            addCriterion("mas_una_direccion is null");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionIsNotNull() {
            addCriterion("mas_una_direccion is not null");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionEqualTo(String value) {
            addCriterion("mas_una_direccion =", value, "masUnaDireccion");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionNotEqualTo(String value) {
            addCriterion("mas_una_direccion <>", value, "masUnaDireccion");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionGreaterThan(String value) {
            addCriterion("mas_una_direccion >", value, "masUnaDireccion");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionGreaterThanOrEqualTo(String value) {
            addCriterion("mas_una_direccion >=", value, "masUnaDireccion");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionLessThan(String value) {
            addCriterion("mas_una_direccion <", value, "masUnaDireccion");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionLessThanOrEqualTo(String value) {
            addCriterion("mas_una_direccion <=", value, "masUnaDireccion");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionLike(String value) {
            addCriterion("mas_una_direccion like", value, "masUnaDireccion");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionNotLike(String value) {
            addCriterion("mas_una_direccion not like", value, "masUnaDireccion");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionIn(List<String> values) {
            addCriterion("mas_una_direccion in", values, "masUnaDireccion");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionNotIn(List<String> values) {
            addCriterion("mas_una_direccion not in", values, "masUnaDireccion");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionBetween(String value1, String value2) {
            addCriterion("mas_una_direccion between", value1, value2, "masUnaDireccion");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionNotBetween(String value1, String value2) {
            addCriterion("mas_una_direccion not between", value1, value2, "masUnaDireccion");
            return (Criteria) this;
        }

        public Criteria andGidIsNull() {
            addCriterion("gid is null");
            return (Criteria) this;
        }

        public Criteria andGidIsNotNull() {
            addCriterion("gid is not null");
            return (Criteria) this;
        }

        public Criteria andGidEqualTo(Integer value) {
            addCriterion("gid =", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotEqualTo(Integer value) {
            addCriterion("gid <>", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThan(Integer value) {
            addCriterion("gid >", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThanOrEqualTo(Integer value) {
            addCriterion("gid >=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThan(Integer value) {
            addCriterion("gid <", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThanOrEqualTo(Integer value) {
            addCriterion("gid <=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidIn(List<Integer> values) {
            addCriterion("gid in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotIn(List<Integer> values) {
            addCriterion("gid not in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidBetween(Integer value1, Integer value2) {
            addCriterion("gid between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotBetween(Integer value1, Integer value2) {
            addCriterion("gid not between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andDireccionLikeInsensitive(String value) {
            addCriterion("upper(direccion) like", value.toUpperCase(), "direccion");
            return (Criteria) this;
        }

        public Criteria andCuadraLikeInsensitive(String value) {
            addCriterion("upper(cuadra) like", value.toUpperCase(), "cuadra");
            return (Criteria) this;
        }

        public Criteria andMotivoLikeInsensitive(String value) {
            addCriterion("upper(motivo) like", value.toUpperCase(), "motivo");
            return (Criteria) this;
        }

        public Criteria andEmpresaLikeInsensitive(String value) {
            addCriterion("upper(empresa) like", value.toUpperCase(), "empresa");
            return (Criteria) this;
        }

        public Criteria andIpRegistroLikeInsensitive(String value) {
            addCriterion("upper(ip_registro) like", value.toUpperCase(), "ipRegistro");
            return (Criteria) this;
        }

        public Criteria andIpModificacionLikeInsensitive(String value) {
            addCriterion("upper(ip_modificacion) like", value.toUpperCase(), "ipModificacion");
            return (Criteria) this;
        }

        public Criteria andNumExpedienteLikeInsensitive(String value) {
            addCriterion("upper(num_expediente) like", value.toUpperCase(), "numExpediente");
            return (Criteria) this;
        }

        public Criteria andMasUnaDireccionLikeInsensitive(String value) {
            addCriterion("upper(mas_una_direccion) like", value.toUpperCase(), "masUnaDireccion");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 07 21:46:28 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}