package pe.gob.miraflores.mobile.domain.mapaincidencias;

import java.util.ArrayList;
import java.util.List;

public class TipificacionCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    public TipificacionCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUnidadIsNull() {
            addCriterion("unidad is null");
            return (Criteria) this;
        }

        public Criteria andUnidadIsNotNull() {
            addCriterion("unidad is not null");
            return (Criteria) this;
        }

        public Criteria andUnidadEqualTo(Integer value) {
            addCriterion("unidad =", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadNotEqualTo(Integer value) {
            addCriterion("unidad <>", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadGreaterThan(Integer value) {
            addCriterion("unidad >", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadGreaterThanOrEqualTo(Integer value) {
            addCriterion("unidad >=", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadLessThan(Integer value) {
            addCriterion("unidad <", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadLessThanOrEqualTo(Integer value) {
            addCriterion("unidad <=", value, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadIn(List<Integer> values) {
            addCriterion("unidad in", values, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadNotIn(List<Integer> values) {
            addCriterion("unidad not in", values, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadBetween(Integer value1, Integer value2) {
            addCriterion("unidad between", value1, value2, "unidad");
            return (Criteria) this;
        }

        public Criteria andUnidadNotBetween(Integer value1, Integer value2) {
            addCriterion("unidad not between", value1, value2, "unidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadIsNull() {
            addCriterion("desc_unidad is null");
            return (Criteria) this;
        }

        public Criteria andDescUnidadIsNotNull() {
            addCriterion("desc_unidad is not null");
            return (Criteria) this;
        }

        public Criteria andDescUnidadEqualTo(String value) {
            addCriterion("desc_unidad =", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadNotEqualTo(String value) {
            addCriterion("desc_unidad <>", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadGreaterThan(String value) {
            addCriterion("desc_unidad >", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadGreaterThanOrEqualTo(String value) {
            addCriterion("desc_unidad >=", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadLessThan(String value) {
            addCriterion("desc_unidad <", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadLessThanOrEqualTo(String value) {
            addCriterion("desc_unidad <=", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadLike(String value) {
            addCriterion("desc_unidad like", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadNotLike(String value) {
            addCriterion("desc_unidad not like", value, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadIn(List<String> values) {
            addCriterion("desc_unidad in", values, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadNotIn(List<String> values) {
            addCriterion("desc_unidad not in", values, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadBetween(String value1, String value2) {
            addCriterion("desc_unidad between", value1, value2, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescUnidadNotBetween(String value1, String value2) {
            addCriterion("desc_unidad not between", value1, value2, "descUnidad");
            return (Criteria) this;
        }

        public Criteria andCasoIsNull() {
            addCriterion("caso is null");
            return (Criteria) this;
        }

        public Criteria andCasoIsNotNull() {
            addCriterion("caso is not null");
            return (Criteria) this;
        }

        public Criteria andCasoEqualTo(Integer value) {
            addCriterion("caso =", value, "caso");
            return (Criteria) this;
        }

        public Criteria andCasoNotEqualTo(Integer value) {
            addCriterion("caso <>", value, "caso");
            return (Criteria) this;
        }

        public Criteria andCasoGreaterThan(Integer value) {
            addCriterion("caso >", value, "caso");
            return (Criteria) this;
        }

        public Criteria andCasoGreaterThanOrEqualTo(Integer value) {
            addCriterion("caso >=", value, "caso");
            return (Criteria) this;
        }

        public Criteria andCasoLessThan(Integer value) {
            addCriterion("caso <", value, "caso");
            return (Criteria) this;
        }

        public Criteria andCasoLessThanOrEqualTo(Integer value) {
            addCriterion("caso <=", value, "caso");
            return (Criteria) this;
        }

        public Criteria andCasoIn(List<Integer> values) {
            addCriterion("caso in", values, "caso");
            return (Criteria) this;
        }

        public Criteria andCasoNotIn(List<Integer> values) {
            addCriterion("caso not in", values, "caso");
            return (Criteria) this;
        }

        public Criteria andCasoBetween(Integer value1, Integer value2) {
            addCriterion("caso between", value1, value2, "caso");
            return (Criteria) this;
        }

        public Criteria andCasoNotBetween(Integer value1, Integer value2) {
            addCriterion("caso not between", value1, value2, "caso");
            return (Criteria) this;
        }

        public Criteria andDescCasoIsNull() {
            addCriterion("desc_caso is null");
            return (Criteria) this;
        }

        public Criteria andDescCasoIsNotNull() {
            addCriterion("desc_caso is not null");
            return (Criteria) this;
        }

        public Criteria andDescCasoEqualTo(String value) {
            addCriterion("desc_caso =", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoNotEqualTo(String value) {
            addCriterion("desc_caso <>", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoGreaterThan(String value) {
            addCriterion("desc_caso >", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoGreaterThanOrEqualTo(String value) {
            addCriterion("desc_caso >=", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoLessThan(String value) {
            addCriterion("desc_caso <", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoLessThanOrEqualTo(String value) {
            addCriterion("desc_caso <=", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoLike(String value) {
            addCriterion("desc_caso like", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoNotLike(String value) {
            addCriterion("desc_caso not like", value, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoIn(List<String> values) {
            addCriterion("desc_caso in", values, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoNotIn(List<String> values) {
            addCriterion("desc_caso not in", values, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoBetween(String value1, String value2) {
            addCriterion("desc_caso between", value1, value2, "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescCasoNotBetween(String value1, String value2) {
            addCriterion("desc_caso not between", value1, value2, "descCaso");
            return (Criteria) this;
        }

        public Criteria andSubcasoIsNull() {
            addCriterion("subcaso is null");
            return (Criteria) this;
        }

        public Criteria andSubcasoIsNotNull() {
            addCriterion("subcaso is not null");
            return (Criteria) this;
        }

        public Criteria andSubcasoEqualTo(Integer value) {
            addCriterion("subcaso =", value, "subcaso");
            return (Criteria) this;
        }

        public Criteria andSubcasoNotEqualTo(Integer value) {
            addCriterion("subcaso <>", value, "subcaso");
            return (Criteria) this;
        }

        public Criteria andSubcasoGreaterThan(Integer value) {
            addCriterion("subcaso >", value, "subcaso");
            return (Criteria) this;
        }

        public Criteria andSubcasoGreaterThanOrEqualTo(Integer value) {
            addCriterion("subcaso >=", value, "subcaso");
            return (Criteria) this;
        }

        public Criteria andSubcasoLessThan(Integer value) {
            addCriterion("subcaso <", value, "subcaso");
            return (Criteria) this;
        }

        public Criteria andSubcasoLessThanOrEqualTo(Integer value) {
            addCriterion("subcaso <=", value, "subcaso");
            return (Criteria) this;
        }

        public Criteria andSubcasoIn(List<Integer> values) {
            addCriterion("subcaso in", values, "subcaso");
            return (Criteria) this;
        }

        public Criteria andSubcasoNotIn(List<Integer> values) {
            addCriterion("subcaso not in", values, "subcaso");
            return (Criteria) this;
        }

        public Criteria andSubcasoBetween(Integer value1, Integer value2) {
            addCriterion("subcaso between", value1, value2, "subcaso");
            return (Criteria) this;
        }

        public Criteria andSubcasoNotBetween(Integer value1, Integer value2) {
            addCriterion("subcaso not between", value1, value2, "subcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoIsNull() {
            addCriterion("desc_subcaso is null");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoIsNotNull() {
            addCriterion("desc_subcaso is not null");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoEqualTo(String value) {
            addCriterion("desc_subcaso =", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoNotEqualTo(String value) {
            addCriterion("desc_subcaso <>", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoGreaterThan(String value) {
            addCriterion("desc_subcaso >", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoGreaterThanOrEqualTo(String value) {
            addCriterion("desc_subcaso >=", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoLessThan(String value) {
            addCriterion("desc_subcaso <", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoLessThanOrEqualTo(String value) {
            addCriterion("desc_subcaso <=", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoLike(String value) {
            addCriterion("desc_subcaso like", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoNotLike(String value) {
            addCriterion("desc_subcaso not like", value, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoIn(List<String> values) {
            addCriterion("desc_subcaso in", values, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoNotIn(List<String> values) {
            addCriterion("desc_subcaso not in", values, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoBetween(String value1, String value2) {
            addCriterion("desc_subcaso between", value1, value2, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoNotBetween(String value1, String value2) {
            addCriterion("desc_subcaso not between", value1, value2, "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andTipifIsNull() {
            addCriterion("tipif is null");
            return (Criteria) this;
        }

        public Criteria andTipifIsNotNull() {
            addCriterion("tipif is not null");
            return (Criteria) this;
        }

        public Criteria andTipifEqualTo(Integer value) {
            addCriterion("tipif =", value, "tipif");
            return (Criteria) this;
        }

        public Criteria andTipifNotEqualTo(Integer value) {
            addCriterion("tipif <>", value, "tipif");
            return (Criteria) this;
        }

        public Criteria andTipifGreaterThan(Integer value) {
            addCriterion("tipif >", value, "tipif");
            return (Criteria) this;
        }

        public Criteria andTipifGreaterThanOrEqualTo(Integer value) {
            addCriterion("tipif >=", value, "tipif");
            return (Criteria) this;
        }

        public Criteria andTipifLessThan(Integer value) {
            addCriterion("tipif <", value, "tipif");
            return (Criteria) this;
        }

        public Criteria andTipifLessThanOrEqualTo(Integer value) {
            addCriterion("tipif <=", value, "tipif");
            return (Criteria) this;
        }

        public Criteria andTipifIn(List<Integer> values) {
            addCriterion("tipif in", values, "tipif");
            return (Criteria) this;
        }

        public Criteria andTipifNotIn(List<Integer> values) {
            addCriterion("tipif not in", values, "tipif");
            return (Criteria) this;
        }

        public Criteria andTipifBetween(Integer value1, Integer value2) {
            addCriterion("tipif between", value1, value2, "tipif");
            return (Criteria) this;
        }

        public Criteria andTipifNotBetween(Integer value1, Integer value2) {
            addCriterion("tipif not between", value1, value2, "tipif");
            return (Criteria) this;
        }

        public Criteria andTipifVoxIsNull() {
            addCriterion("tipif_vox is null");
            return (Criteria) this;
        }

        public Criteria andTipifVoxIsNotNull() {
            addCriterion("tipif_vox is not null");
            return (Criteria) this;
        }

        public Criteria andTipifVoxEqualTo(String value) {
            addCriterion("tipif_vox =", value, "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifVoxNotEqualTo(String value) {
            addCriterion("tipif_vox <>", value, "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifVoxGreaterThan(String value) {
            addCriterion("tipif_vox >", value, "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifVoxGreaterThanOrEqualTo(String value) {
            addCriterion("tipif_vox >=", value, "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifVoxLessThan(String value) {
            addCriterion("tipif_vox <", value, "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifVoxLessThanOrEqualTo(String value) {
            addCriterion("tipif_vox <=", value, "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifVoxLike(String value) {
            addCriterion("tipif_vox like", value, "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifVoxNotLike(String value) {
            addCriterion("tipif_vox not like", value, "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifVoxIn(List<String> values) {
            addCriterion("tipif_vox in", values, "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifVoxNotIn(List<String> values) {
            addCriterion("tipif_vox not in", values, "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifVoxBetween(String value1, String value2) {
            addCriterion("tipif_vox between", value1, value2, "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifVoxNotBetween(String value1, String value2) {
            addCriterion("tipif_vox not between", value1, value2, "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifReachIsNull() {
            addCriterion("tipif_reach is null");
            return (Criteria) this;
        }

        public Criteria andTipifReachIsNotNull() {
            addCriterion("tipif_reach is not null");
            return (Criteria) this;
        }

        public Criteria andTipifReachEqualTo(String value) {
            addCriterion("tipif_reach =", value, "tipifReach");
            return (Criteria) this;
        }

        public Criteria andTipifReachNotEqualTo(String value) {
            addCriterion("tipif_reach <>", value, "tipifReach");
            return (Criteria) this;
        }

        public Criteria andTipifReachGreaterThan(String value) {
            addCriterion("tipif_reach >", value, "tipifReach");
            return (Criteria) this;
        }

        public Criteria andTipifReachGreaterThanOrEqualTo(String value) {
            addCriterion("tipif_reach >=", value, "tipifReach");
            return (Criteria) this;
        }

        public Criteria andTipifReachLessThan(String value) {
            addCriterion("tipif_reach <", value, "tipifReach");
            return (Criteria) this;
        }

        public Criteria andTipifReachLessThanOrEqualTo(String value) {
            addCriterion("tipif_reach <=", value, "tipifReach");
            return (Criteria) this;
        }

        public Criteria andTipifReachLike(String value) {
            addCriterion("tipif_reach like", value, "tipifReach");
            return (Criteria) this;
        }

        public Criteria andTipifReachNotLike(String value) {
            addCriterion("tipif_reach not like", value, "tipifReach");
            return (Criteria) this;
        }

        public Criteria andTipifReachIn(List<String> values) {
            addCriterion("tipif_reach in", values, "tipifReach");
            return (Criteria) this;
        }

        public Criteria andTipifReachNotIn(List<String> values) {
            addCriterion("tipif_reach not in", values, "tipifReach");
            return (Criteria) this;
        }

        public Criteria andTipifReachBetween(String value1, String value2) {
            addCriterion("tipif_reach between", value1, value2, "tipifReach");
            return (Criteria) this;
        }

        public Criteria andTipifReachNotBetween(String value1, String value2) {
            addCriterion("tipif_reach not between", value1, value2, "tipifReach");
            return (Criteria) this;
        }

        public Criteria andDescUnidadLikeInsensitive(String value) {
            addCriterion("upper(desc_unidad) like", value.toUpperCase(), "descUnidad");
            return (Criteria) this;
        }

        public Criteria andDescCasoLikeInsensitive(String value) {
            addCriterion("upper(desc_caso) like", value.toUpperCase(), "descCaso");
            return (Criteria) this;
        }

        public Criteria andDescSubcasoLikeInsensitive(String value) {
            addCriterion("upper(desc_subcaso) like", value.toUpperCase(), "descSubcaso");
            return (Criteria) this;
        }

        public Criteria andTipifVoxLikeInsensitive(String value) {
            addCriterion("upper(tipif_vox) like", value.toUpperCase(), "tipifVox");
            return (Criteria) this;
        }

        public Criteria andTipifReachLikeInsensitive(String value) {
            addCriterion("upper(tipif_reach) like", value.toUpperCase(), "tipifReach");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 08 15:37:35 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}