package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.AuditoriaIncidencia;
import pe.gob.miraflores.mobile.domain.mapaincidencias.AuditoriaIncidenciaCriteria;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaRegistro;

public interface AuditoriaIncidenciaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_auditoria
     *
     * @mbg.generated Fri Nov 03 10:32:59 COT 2017
     */
    long countByExample(AuditoriaIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_auditoria
     *
     * @mbg.generated Fri Nov 03 10:32:59 COT 2017
     */
    int deleteByExample(AuditoriaIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_auditoria
     *
     * @mbg.generated Fri Nov 03 10:32:59 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_auditoria
     *
     * @mbg.generated Fri Nov 03 10:32:59 COT 2017
     */
    int insert(AuditoriaIncidencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_auditoria
     *
     * @mbg.generated Fri Nov 03 10:32:59 COT 2017
     */
    int insertSelective(AuditoriaIncidencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_auditoria
     *
     * @mbg.generated Fri Nov 03 10:32:59 COT 2017
     */
    List<AuditoriaIncidencia> selectByExample(AuditoriaIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_auditoria
     *
     * @mbg.generated Fri Nov 03 10:32:59 COT 2017
     */
    AuditoriaIncidencia selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_auditoria
     *
     * @mbg.generated Fri Nov 03 10:32:59 COT 2017
     */
    int updateByExampleSelective(@Param("record") AuditoriaIncidencia record, @Param("example") AuditoriaIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_auditoria
     *
     * @mbg.generated Fri Nov 03 10:32:59 COT 2017
     */
    int updateByExample(@Param("record") AuditoriaIncidencia record, @Param("example") AuditoriaIncidenciaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_auditoria
     *
     * @mbg.generated Fri Nov 03 10:32:59 COT 2017
     */
    int updateByPrimaryKeySelective(AuditoriaIncidencia record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_auditoria
     *
     * @mbg.generated Fri Nov 03 10:32:59 COT 2017
     */
    int updateByPrimaryKey(AuditoriaIncidencia record);
    
    
    public List<AuditoriaIncidencia> selectBandejaAuditoriaPaginada(Map<String, Object> params);
 	public int countBandejaAuditoriaPaginada(Map<String, Object> params);
    
}