package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.GeoInfoCambista;
import pe.gob.miraflores.mobile.domain.mapaincidencias.GeoInfoCambistaCriteria;

public interface GeoInfoCambistaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.cambiasta_map
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    long countByExample(GeoInfoCambistaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.cambiasta_map
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int deleteByExample(GeoInfoCambistaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.cambiasta_map
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.cambiasta_map
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int insert(GeoInfoCambista record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.cambiasta_map
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int insertSelective(GeoInfoCambista record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.cambiasta_map
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    List<GeoInfoCambista> selectByExample(GeoInfoCambistaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.cambiasta_map
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    GeoInfoCambista selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.cambiasta_map
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByExampleSelective(@Param("record") GeoInfoCambista record, @Param("example") GeoInfoCambistaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.cambiasta_map
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByExample(@Param("record") GeoInfoCambista record, @Param("example") GeoInfoCambistaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.cambiasta_map
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByPrimaryKeySelective(GeoInfoCambista record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.cambiasta_map
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByPrimaryKey(GeoInfoCambista record);
}