package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.GeoInfoTetra;
import pe.gob.miraflores.mobile.domain.mapaincidencias.GeoInfoTetraCriteria;

public interface GeoInfoTetraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    long countByExample(GeoInfoTetraCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    int deleteByExample(GeoInfoTetraCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    int deleteByPrimaryKey(Integer issi);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    int insert(GeoInfoTetra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    int insertSelective(GeoInfoTetra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    List<GeoInfoTetra> selectByExample(GeoInfoTetraCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    GeoInfoTetra selectByPrimaryKey(Integer issi);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    int updateByExampleSelective(@Param("record") GeoInfoTetra record, @Param("example") GeoInfoTetraCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    int updateByExample(@Param("record") GeoInfoTetra record, @Param("example") GeoInfoTetraCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    int updateByPrimaryKeySelective(GeoInfoTetra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_tetra
     *
     * @mbg.generated Tue Dec 12 14:43:42 COT 2017
     */
    int updateByPrimaryKey(GeoInfoTetra record);
    
    
    public List<GeoInfoTetra> selectTetraList();
    public List<GeoInfoTetra> selectTetraListPrueba(Map<String, Object> p);
    
}