package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.GeoInfoPos;
import pe.gob.miraflores.mobile.domain.mapaincidencias.GeoInfoPosCriteria;

public interface GeoInfoPosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_pos
     *
     * @mbg.generated Mon Nov 20 21:08:58 COT 2017
     */
    long countByExample(GeoInfoPosCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_pos
     *
     * @mbg.generated Mon Nov 20 21:08:58 COT 2017
     */
    int deleteByExample(GeoInfoPosCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_pos
     *
     * @mbg.generated Mon Nov 20 21:08:58 COT 2017
     */
    int deleteByPrimaryKey(Integer idPos);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_pos
     *
     * @mbg.generated Mon Nov 20 21:08:58 COT 2017
     */
    int insert(GeoInfoPos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_pos
     *
     * @mbg.generated Mon Nov 20 21:08:58 COT 2017
     */
    int insertSelective(GeoInfoPos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_pos
     *
     * @mbg.generated Mon Nov 20 21:08:58 COT 2017
     */
    List<GeoInfoPos> selectByExample(GeoInfoPosCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_pos
     *
     * @mbg.generated Mon Nov 20 21:08:58 COT 2017
     */
    GeoInfoPos selectByPrimaryKey(Integer idPos);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_pos
     *
     * @mbg.generated Mon Nov 20 21:08:58 COT 2017
     */
    int updateByExampleSelective(@Param("record") GeoInfoPos record, @Param("example") GeoInfoPosCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_pos
     *
     * @mbg.generated Mon Nov 20 21:08:58 COT 2017
     */
    int updateByExample(@Param("record") GeoInfoPos record, @Param("example") GeoInfoPosCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_pos
     *
     * @mbg.generated Mon Nov 20 21:08:58 COT 2017
     */
    int updateByPrimaryKeySelective(GeoInfoPos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_pos
     *
     * @mbg.generated Mon Nov 20 21:08:58 COT 2017
     */
    int updateByPrimaryKey(GeoInfoPos record);
}