package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.GeometriaLinea;
import pe.gob.miraflores.mobile.domain.mapaincidencias.GeometriaLineaCriteria;


public interface GeometriaLineaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_inicidencia_linea
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    long countByExample(GeometriaLineaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_inicidencia_linea
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int deleteByExample(GeometriaLineaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_inicidencia_linea
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int deleteByPrimaryKey(Integer idLinea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_inicidencia_linea
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int insert(GeometriaLinea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_inicidencia_linea
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int insertSelective(GeometriaLinea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_inicidencia_linea
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    List<GeometriaLinea> selectByExample(GeometriaLineaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_inicidencia_linea
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    GeometriaLinea selectByPrimaryKey(Integer idLinea);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_inicidencia_linea
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByExampleSelective(@Param("record") GeometriaLinea record, @Param("example") GeometriaLineaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_inicidencia_linea
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByExample(@Param("record") GeometriaLinea record, @Param("example") GeometriaLineaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_inicidencia_linea
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByPrimaryKeySelective(GeometriaLinea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_inicidencia_linea
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByPrimaryKey(GeometriaLinea record);
}