package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.ImagenIncidencia;
import pe.gob.miraflores.mobile.domain.mapaincidencias.ImagenIncidenciaCriteria;

public interface ImagenIncidenciaMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	long countByExample(ImagenIncidenciaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	int deleteByExample(ImagenIncidenciaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	int deleteByPrimaryKey(Integer idImg);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	int insert(ImagenIncidencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	int insertSelective(ImagenIncidencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	List<ImagenIncidencia> selectByExampleWithBLOBs(ImagenIncidenciaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	List<ImagenIncidencia> selectByExample(ImagenIncidenciaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	ImagenIncidencia selectByPrimaryKey(Integer idImg);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	int updateByExampleSelective(@Param("record") ImagenIncidencia record, @Param("example") ImagenIncidenciaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	int updateByExampleWithBLOBs(@Param("record") ImagenIncidencia record, @Param("example") ImagenIncidenciaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	int updateByExample(@Param("record") ImagenIncidencia record, @Param("example") ImagenIncidenciaCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	int updateByPrimaryKeySelective(ImagenIncidencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	int updateByPrimaryKeyWithBLOBs(ImagenIncidencia record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_img_incidencia
	 * @mbg.generated  Mon Jan 08 21:07:34 COT 2018
	 */
	int updateByPrimaryKey(ImagenIncidencia record);
	
	
	List<ImagenIncidencia> selectByExampleAlt(ImagenIncidenciaCriteria example);
}