package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciasGeometria;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciasGeometriaCriteria;

public interface MapaIncidenciasGeometriaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geomgeometria
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    long countByExample(MapaIncidenciasGeometriaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geomgeometria
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int deleteByExample(MapaIncidenciasGeometriaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geomgeometria
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int deleteByPrimaryKey(Integer idgeoreferencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geomgeometria
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int insert(MapaIncidenciasGeometria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geomgeometria
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int insertSelective(MapaIncidenciasGeometria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geomgeometria
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    List<MapaIncidenciasGeometria> selectByExample(MapaIncidenciasGeometriaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geomgeometria
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    MapaIncidenciasGeometria selectByPrimaryKey(Integer idgeoreferencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geomgeometria
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByExampleSelective(@Param("record") MapaIncidenciasGeometria record, @Param("example") MapaIncidenciasGeometriaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geomgeometria
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByExample(@Param("record") MapaIncidenciasGeometria record, @Param("example") MapaIncidenciasGeometriaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geomgeometria
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByPrimaryKeySelective(MapaIncidenciasGeometria record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geomgeometria
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByPrimaryKey(MapaIncidenciasGeometria record);
}