package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaMaestroTipo;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaMaestroTipoCriteria;

public interface MapaMaestroTipoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_maestro_tipo
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    long countByExample(MapaMaestroTipoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_maestro_tipo
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int deleteByExample(MapaMaestroTipoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_maestro_tipo
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int deleteByPrimaryKey(Integer codTipo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_maestro_tipo
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int insert(MapaMaestroTipo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_maestro_tipo
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int insertSelective(MapaMaestroTipo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_maestro_tipo
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    List<MapaMaestroTipo> selectByExample(MapaMaestroTipoCriteria example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_maestro_tipo
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    MapaMaestroTipo selectByPrimaryKey(Integer codTipo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_maestro_tipo
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByExampleSelective(@Param("record") MapaMaestroTipo record, @Param("example") MapaMaestroTipoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_maestro_tipo
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByExample(@Param("record") MapaMaestroTipo record, @Param("example") MapaMaestroTipoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_maestro_tipo
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByPrimaryKeySelective(MapaMaestroTipo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_maestro_tipo
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByPrimaryKey(MapaMaestroTipo record);
    
    //Consultar tipos ordenados por cod_tipo    
    List<MapaMaestroTipo> selectByExampleWithOrder(MapaMaestroTipoCriteria example);
    
}