package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaInvolucrado;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaInvolucradoCriteria;

public interface MapaInvolucradoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_involucrado
     *
     * @mbg.generated Tue Aug 01 21:17:50 COT 2017
     */
    long countByExample(MapaInvolucradoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_involucrado
     *
     * @mbg.generated Tue Aug 01 21:17:50 COT 2017
     */
    int deleteByExample(MapaInvolucradoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_involucrado
     *
     * @mbg.generated Tue Aug 01 21:17:50 COT 2017
     */
    int deleteByPrimaryKey(Integer codInvoluc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_involucrado
     *
     * @mbg.generated Tue Aug 01 21:17:50 COT 2017
     */
    int insert(MapaInvolucrado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_involucrado
     *
     * @mbg.generated Tue Aug 01 21:17:50 COT 2017
     */
    int insertSelective(MapaInvolucrado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_involucrado
     *
     * @mbg.generated Tue Aug 01 21:17:50 COT 2017
     */
    List<MapaInvolucrado> selectByExample(MapaInvolucradoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_involucrado
     *
     * @mbg.generated Tue Aug 01 21:17:50 COT 2017
     */
    MapaInvolucrado selectByPrimaryKey(Integer codInvoluc);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_involucrado
     *
     * @mbg.generated Tue Aug 01 21:17:50 COT 2017
     */
    int updateByExampleSelective(@Param("record") MapaInvolucrado record, @Param("example") MapaInvolucradoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_involucrado
     *
     * @mbg.generated Tue Aug 01 21:17:50 COT 2017
     */
    int updateByExample(@Param("record") MapaInvolucrado record, @Param("example") MapaInvolucradoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_involucrado
     *
     * @mbg.generated Tue Aug 01 21:17:50 COT 2017
     */
    int updateByPrimaryKeySelective(MapaInvolucrado record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_involucrado
     *
     * @mbg.generated Tue Aug 01 21:17:50 COT 2017
     */
    int updateByPrimaryKey(MapaInvolucrado record);
}