package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaEstadistica;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaEstadisticaCriteria;

public interface MapaEstadisticaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    long countByExample(MapaEstadisticaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    int deleteByExample(MapaEstadisticaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    int insert(MapaEstadistica record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    int insertSelective(MapaEstadistica record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    List<MapaEstadistica> selectByExample(MapaEstadisticaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    MapaEstadistica selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    int updateByExampleSelective(@Param("record") MapaEstadistica record, @Param("example") MapaEstadisticaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    int updateByExample(@Param("record") MapaEstadistica record, @Param("example") MapaEstadisticaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    int updateByPrimaryKeySelective(MapaEstadistica record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_estadistica
     *
     * @mbg.generated Thu Nov 16 14:03:03 COT 2017
     */
    int updateByPrimaryKey(MapaEstadistica record);
}