package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaSubcaso;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaSubcasoCriteria;

public interface MapaSubcasoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_subcaso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	long countByExample(MapaSubcasoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_subcaso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int deleteByExample(MapaSubcasoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_subcaso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int deleteByPrimaryKey(Integer codSubcaso);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_subcaso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int insert(MapaSubcaso record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_subcaso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int insertSelective(MapaSubcaso record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_subcaso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	List<MapaSubcaso> selectByExample(MapaSubcasoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_subcaso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	MapaSubcaso selectByPrimaryKey(Integer codSubcaso);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_subcaso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int updateByExampleSelective(@Param("record") MapaSubcaso record, @Param("example") MapaSubcasoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_subcaso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int updateByExample(@Param("record") MapaSubcaso record, @Param("example") MapaSubcasoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_subcaso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int updateByPrimaryKeySelective(MapaSubcaso record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_subcaso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int updateByPrimaryKey(MapaSubcaso record);
}