package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaGenerico;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaGenericoCriteria;


public interface MapaIncidenciaGenericoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_generico
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    long countByExample(MapaIncidenciaGenericoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_generico
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int deleteByExample(MapaIncidenciaGenericoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_generico
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_generico
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int insert(MapaIncidenciaGenerico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_generico
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int insertSelective(MapaIncidenciaGenerico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_generico
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    List<MapaIncidenciaGenerico> selectByExample(MapaIncidenciaGenericoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_generico
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    MapaIncidenciaGenerico selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_generico
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByExampleSelective(@Param("record") MapaIncidenciaGenerico record, @Param("example") MapaIncidenciaGenericoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_generico
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByExample(@Param("record") MapaIncidenciaGenerico record, @Param("example") MapaIncidenciaGenericoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_generico
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByPrimaryKeySelective(MapaIncidenciaGenerico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_generico
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByPrimaryKey(MapaIncidenciaGenerico record);
}