package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaRegistro;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaZonificacion;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaZonificacionCriteria;

public interface MapaZonificacionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.zonificacion
     *
     * @mbg.generated Wed Jan 24 11:19:43 COT 2018
     */
    long countByExample(MapaZonificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.zonificacion
     *
     * @mbg.generated Wed Jan 24 11:19:43 COT 2018
     */
    int deleteByExample(MapaZonificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.zonificacion
     *
     * @mbg.generated Wed Jan 24 11:19:43 COT 2018
     */
    int deleteByPrimaryKey(Integer codSubzona);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.zonificacion
     *
     * @mbg.generated Wed Jan 24 11:19:43 COT 2018
     */
    int insert(MapaZonificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.zonificacion
     *
     * @mbg.generated Wed Jan 24 11:19:43 COT 2018
     */
    int insertSelective(MapaZonificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.zonificacion
     *
     * @mbg.generated Wed Jan 24 11:19:43 COT 2018
     */
    List<MapaZonificacion> selectByExample(MapaZonificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.zonificacion
     *
     * @mbg.generated Wed Jan 24 11:19:43 COT 2018
     */
    MapaZonificacion selectByPrimaryKey(Integer codSubzona);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.zonificacion
     *
     * @mbg.generated Wed Jan 24 11:19:43 COT 2018
     */
    int updateByExampleSelective(@Param("record") MapaZonificacion record, @Param("example") MapaZonificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.zonificacion
     *
     * @mbg.generated Wed Jan 24 11:19:43 COT 2018
     */
    int updateByExample(@Param("record") MapaZonificacion record, @Param("example") MapaZonificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.zonificacion
     *
     * @mbg.generated Wed Jan 24 11:19:43 COT 2018
     */
    int updateByPrimaryKeySelective(MapaZonificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.zonificacion
     *
     * @mbg.generated Wed Jan 24 11:19:43 COT 2018
     */
    int updateByPrimaryKey(MapaZonificacion record);
    
    
    public List<Map<String, Object>> selectZonificacion(Map<String, Object> params);
    
}