package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaUnidad;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaUnidadCriteria;

public interface MapaUnidadMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_unidad
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	long countByExample(MapaUnidadCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_unidad
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int deleteByExample(MapaUnidadCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_unidad
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int deleteByPrimaryKey(Integer codUnidad);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_unidad
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int insert(MapaUnidad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_unidad
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int insertSelective(MapaUnidad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_unidad
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	List<MapaUnidad> selectByExample(MapaUnidadCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_unidad
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	MapaUnidad selectByPrimaryKey(Integer codUnidad);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_unidad
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int updateByExampleSelective(@Param("record") MapaUnidad record, @Param("example") MapaUnidadCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_unidad
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int updateByExample(@Param("record") MapaUnidad record, @Param("example") MapaUnidadCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_unidad
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int updateByPrimaryKeySelective(MapaUnidad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_unidad
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int updateByPrimaryKey(MapaUnidad record);
}