package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciasRegistro;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciasRegistroCriteria;

public interface MapaIncidenciasRegistroMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_incidencia_map
	 * @mbg.generated  Mon Jul 10 09:42:15 COT 2017
	 */
	long countByExample(MapaIncidenciasRegistroCriteria example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_incidencia_map
	 * @mbg.generated  Mon Jul 10 09:42:15 COT 2017
	 */
	int deleteByExample(MapaIncidenciasRegistroCriteria example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_incidencia_map
	 * @mbg.generated  Mon Jul 10 09:42:15 COT 2017
	 */
	int deleteByPrimaryKey(Integer idIncidencia);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_incidencia_map
	 * @mbg.generated  Mon Jul 10 09:42:15 COT 2017
	 */
	int insert(MapaIncidenciasRegistro record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_incidencia_map
	 * @mbg.generated  Mon Jul 10 09:42:15 COT 2017
	 */
	int insertSelective(MapaIncidenciasRegistro record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_incidencia_map
	 * @mbg.generated  Mon Jul 10 09:42:15 COT 2017
	 */
	List<MapaIncidenciasRegistro> selectByExample(MapaIncidenciasRegistroCriteria example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_incidencia_map
	 * @mbg.generated  Mon Jul 10 09:42:15 COT 2017
	 */
	MapaIncidenciasRegistro selectByPrimaryKey(Integer idIncidencia);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_incidencia_map
	 * @mbg.generated  Mon Jul 10 09:42:15 COT 2017
	 */
	int updateByExampleSelective(@Param("record") MapaIncidenciasRegistro record,
			@Param("example") MapaIncidenciasRegistroCriteria example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_incidencia_map
	 * @mbg.generated  Mon Jul 10 09:42:15 COT 2017
	 */
	int updateByExample(@Param("record") MapaIncidenciasRegistro record,
			@Param("example") MapaIncidenciasRegistroCriteria example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_incidencia_map
	 * @mbg.generated  Mon Jul 10 09:42:15 COT 2017
	 */
	int updateByPrimaryKeySelective(MapaIncidenciasRegistro record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_incidencia_map
	 * @mbg.generated  Mon Jul 10 09:42:15 COT 2017
	 */
	int updateByPrimaryKey(MapaIncidenciasRegistro record);
	
	// METODOS PERSONALIZADOS
    
	public List<MapaIncidenciasRegistro> listarIncidenciasConPaginacion(Map<String, Object> params);
	int countListarIncidenciasConPaginacion(Map<String, Object> params);
	public List<MapaIncidenciasRegistro> cierreCallesPorVencer(Map<String, Object> params);
	public List<MapaIncidenciasRegistro> cierreCallesPorIniciar(Map<String, Object> params);
	public List<MapaIncidenciasRegistro> listarIncidenciasGenericConPaginacion(Map<String, Object> params);
	public int countListarIncidenciasGenericConPaginacion(Map<String, Object> params);
	int updateByPrimaryKeySelectiveVoxiva(MapaIncidenciasRegistro record);
	public List<MapaIncidenciasRegistro> listarIncidenciasWazeService();
	public List<MapaIncidenciasRegistro> selectListWazeService(Map<String, Object> params);
	public List<MapaIncidenciasRegistro> selectVoxivaListMap(Map<String, Object> params);
	List<Map<String, Object>> selectBandejaIncidencias2();
	long getId();
}