package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaTelefono;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaTelefonoCriteria;

public interface MapaTelefonoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.telefono
     *
     * @mbg.generated Thu Jan 25 08:47:49 COT 2018
     */
    long countByExample(MapaTelefonoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.telefono
     *
     * @mbg.generated Thu Jan 25 08:47:49 COT 2018
     */
    int deleteByExample(MapaTelefonoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.telefono
     *
     * @mbg.generated Thu Jan 25 08:47:49 COT 2018
     */
    int deleteByPrimaryKey(String telefono);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.telefono
     *
     * @mbg.generated Thu Jan 25 08:47:49 COT 2018
     */
    int insert(MapaTelefono record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.telefono
     *
     * @mbg.generated Thu Jan 25 08:47:49 COT 2018
     */
    int insertSelective(MapaTelefono record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.telefono
     *
     * @mbg.generated Thu Jan 25 08:47:49 COT 2018
     */
    List<MapaTelefono> selectByExample(MapaTelefonoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.telefono
     *
     * @mbg.generated Thu Jan 25 08:47:49 COT 2018
     */
    MapaTelefono selectByPrimaryKey(String telefono);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.telefono
     *
     * @mbg.generated Thu Jan 25 08:47:49 COT 2018
     */
    int updateByExampleSelective(@Param("record") MapaTelefono record, @Param("example") MapaTelefonoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.telefono
     *
     * @mbg.generated Thu Jan 25 08:47:49 COT 2018
     */
    int updateByExample(@Param("record") MapaTelefono record, @Param("example") MapaTelefonoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.telefono
     *
     * @mbg.generated Thu Jan 25 08:47:49 COT 2018
     */
    int updateByPrimaryKeySelective(MapaTelefono record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.telefono
     *
     * @mbg.generated Thu Jan 25 08:47:49 COT 2018
     */
    int updateByPrimaryKey(MapaTelefono record);
}