package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaInterviniente;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaVehiculo;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaVehiculoCriteria;

public interface MapaVehiculoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_vehiculo
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    long countByExample(MapaVehiculoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_vehiculo
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int deleteByExample(MapaVehiculoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_vehiculo
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int deleteByPrimaryKey(Integer codVehic);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_vehiculo
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int insert(MapaVehiculo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_vehiculo
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int insertSelective(MapaVehiculo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_vehiculo
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    List<MapaVehiculo> selectByExample(MapaVehiculoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_vehiculo
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    MapaVehiculo selectByPrimaryKey(Integer codVehic);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_vehiculo
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int updateByExampleSelective(@Param("record") MapaVehiculo record, @Param("example") MapaVehiculoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_vehiculo
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int updateByExample(@Param("record") MapaVehiculo record, @Param("example") MapaVehiculoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_vehiculo
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int updateByPrimaryKeySelective(MapaVehiculo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_vehiculo
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int updateByPrimaryKey(MapaVehiculo record);
    
}