package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaAlerta;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaAlertaCriteria;

public interface MapaIncidenciaAlertaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_alerta
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    long countByExample(MapaIncidenciaAlertaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_alerta
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int deleteByExample(MapaIncidenciaAlertaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_alerta
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int deleteByPrimaryKey(Integer idIncidencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_alerta
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int insert(MapaIncidenciaAlerta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_alerta
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int insertSelective(MapaIncidenciaAlerta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_alerta
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    List<MapaIncidenciaAlerta> selectByExample(MapaIncidenciaAlertaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_alerta
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    MapaIncidenciaAlerta selectByPrimaryKey(Integer idIncidencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_alerta
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int updateByExampleSelective(@Param("record") MapaIncidenciaAlerta record, @Param("example") MapaIncidenciaAlertaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_alerta
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int updateByExample(@Param("record") MapaIncidenciaAlerta record, @Param("example") MapaIncidenciaAlertaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_alerta
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int updateByPrimaryKeySelective(MapaIncidenciaAlerta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_alerta
     *
     * @mbg.generated Wed Jul 19 10:45:21 COT 2017
     */
    int updateByPrimaryKey(MapaIncidenciaAlerta record);
}