package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaCaso;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaCasoCriteria;


public interface MapaCasoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	long countByExample(MapaCasoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int deleteByExample(MapaCasoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int deleteByPrimaryKey(Integer codCaso);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int insert(MapaCaso record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int insertSelective(MapaCaso record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	List<MapaCaso> selectByExample(MapaCasoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	MapaCaso selectByPrimaryKey(Integer codCaso);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int updateByExampleSelective(@Param("record") MapaCaso record, @Param("example") MapaCasoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int updateByExample(@Param("record") MapaCaso record, @Param("example") MapaCasoCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int updateByPrimaryKeySelective(MapaCaso record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mapa.geo_map_caso
	 * @mbg.generated  Mon Jul 10 10:48:37 COT 2017
	 */
	int updateByPrimaryKey(MapaCaso record);
}