package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaReg2;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaReg2Criteria;

public interface MapaIncidenciaReg2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_incidencia
     *
     * @mbg.generated Thu Jul 20 11:48:03 COT 2017
     */
    long countByExample(MapaIncidenciaReg2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_incidencia
     *
     * @mbg.generated Thu Jul 20 11:48:03 COT 2017
     */
    int deleteByExample(MapaIncidenciaReg2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_incidencia
     *
     * @mbg.generated Thu Jul 20 11:48:03 COT 2017
     */
    int deleteByPrimaryKey(Integer idIncidencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_incidencia
     *
     * @mbg.generated Thu Jul 20 11:48:03 COT 2017
     */
    int insert(MapaIncidenciaReg2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_incidencia
     *
     * @mbg.generated Thu Jul 20 11:48:03 COT 2017
     */
    int insertSelective(MapaIncidenciaReg2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_incidencia
     *
     * @mbg.generated Thu Jul 20 11:48:03 COT 2017
     */
    List<MapaIncidenciaReg2> selectByExample(MapaIncidenciaReg2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_incidencia
     *
     * @mbg.generated Thu Jul 20 11:48:03 COT 2017
     */
    MapaIncidenciaReg2 selectByPrimaryKey(Integer idIncidencia);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_incidencia
     *
     * @mbg.generated Thu Jul 20 11:48:03 COT 2017
     */
    int updateByExampleSelective(@Param("record") MapaIncidenciaReg2 record, @Param("example") MapaIncidenciaReg2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_incidencia
     *
     * @mbg.generated Thu Jul 20 11:48:03 COT 2017
     */
    int updateByExample(@Param("record") MapaIncidenciaReg2 record, @Param("example") MapaIncidenciaReg2Criteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_incidencia
     *
     * @mbg.generated Thu Jul 20 11:48:03 COT 2017
     */
    int updateByPrimaryKeySelective(MapaIncidenciaReg2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_incidencia
     *
     * @mbg.generated Thu Jul 20 11:48:03 COT 2017
     */
    int updateByPrimaryKey(MapaIncidenciaReg2 record);
}