package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaBitacora;
import pe.gob.miraflores.mobile.domain.mapaincidencias.MapaIncidenciaBitacoraCriteria;

public interface MapaIncidenciaBitacoraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_bitacora
     *
     * @mbg.generated Fri Oct 06 17:24:58 COT 2017
     */
    long countByExample(MapaIncidenciaBitacoraCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_bitacora
     *
     * @mbg.generated Fri Oct 06 17:24:58 COT 2017
     */
    int deleteByExample(MapaIncidenciaBitacoraCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_bitacora
     *
     * @mbg.generated Fri Oct 06 17:24:58 COT 2017
     */
    int deleteByPrimaryKey(Integer idBitacora);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_bitacora
     *
     * @mbg.generated Fri Oct 06 17:24:58 COT 2017
     */
    int insert(MapaIncidenciaBitacora record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_bitacora
     *
     * @mbg.generated Fri Oct 06 17:24:58 COT 2017
     */
    int insertSelective(MapaIncidenciaBitacora record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_bitacora
     *
     * @mbg.generated Fri Oct 06 17:24:58 COT 2017
     */
    List<MapaIncidenciaBitacora> selectByExample(MapaIncidenciaBitacoraCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_bitacora
     *
     * @mbg.generated Fri Oct 06 17:24:58 COT 2017
     */
    MapaIncidenciaBitacora selectByPrimaryKey(Integer idBitacora);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_bitacora
     *
     * @mbg.generated Fri Oct 06 17:24:58 COT 2017
     */
    int updateByExampleSelective(@Param("record") MapaIncidenciaBitacora record, @Param("example") MapaIncidenciaBitacoraCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_bitacora
     *
     * @mbg.generated Fri Oct 06 17:24:58 COT 2017
     */
    int updateByExample(@Param("record") MapaIncidenciaBitacora record, @Param("example") MapaIncidenciaBitacoraCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_bitacora
     *
     * @mbg.generated Fri Oct 06 17:24:58 COT 2017
     */
    int updateByPrimaryKeySelective(MapaIncidenciaBitacora record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_bitacora
     *
     * @mbg.generated Fri Oct 06 17:24:58 COT 2017
     */
    int updateByPrimaryKey(MapaIncidenciaBitacora record);
}