package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.mapaincidencias.PreInscripcionCierreCalle;
import pe.gob.miraflores.mobile.domain.mapaincidencias.PreInscripcionCierreCalleCriteria;


public interface PreInscripcionCierreCalleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    long countByExample(PreInscripcionCierreCalleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int deleteByExample(PreInscripcionCierreCalleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int insert(PreInscripcionCierreCalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int insertSelective(PreInscripcionCierreCalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    List<PreInscripcionCierreCalle> selectByExample(PreInscripcionCierreCalleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    PreInscripcionCierreCalle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByExampleSelective(@Param("record") PreInscripcionCierreCalle record, @Param("example") PreInscripcionCierreCalleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByExample(@Param("record") PreInscripcionCierreCalle record, @Param("example") PreInscripcionCierreCalleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByPrimaryKeySelective(PreInscripcionCierreCalle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.pre_inscripcion_cierre_calle
     *
     * @mbg.generated Fri Jul 07 21:46:28 COT 2017
     */
    int updateByPrimaryKey(PreInscripcionCierreCalle record);
    
    public List<PreInscripcionCierreCalle> bandejaPreRegistroCierreCalle(Map<String, Object> params);
    
}