package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.ReachFeed;
import pe.gob.miraflores.mobile.domain.mapaincidencias.ReachFeedCriteria;

public interface ReachFeedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.reach_feed
     *
     * @mbg.generated Thu Nov 09 10:25:31 COT 2017
     */
    long countByExample(ReachFeedCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.reach_feed
     *
     * @mbg.generated Thu Nov 09 10:25:31 COT 2017
     */
    int deleteByExample(ReachFeedCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.reach_feed
     *
     * @mbg.generated Thu Nov 09 10:25:31 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.reach_feed
     *
     * @mbg.generated Thu Nov 09 10:25:31 COT 2017
     */
    int insert(ReachFeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.reach_feed
     *
     * @mbg.generated Thu Nov 09 10:25:31 COT 2017
     */
    int insertSelective(ReachFeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.reach_feed
     *
     * @mbg.generated Thu Nov 09 10:25:31 COT 2017
     */
    List<ReachFeed> selectByExample(ReachFeedCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.reach_feed
     *
     * @mbg.generated Thu Nov 09 10:25:31 COT 2017
     */
    ReachFeed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.reach_feed
     *
     * @mbg.generated Thu Nov 09 10:25:31 COT 2017
     */
    int updateByExampleSelective(@Param("record") ReachFeed record, @Param("example") ReachFeedCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.reach_feed
     *
     * @mbg.generated Thu Nov 09 10:25:31 COT 2017
     */
    int updateByExample(@Param("record") ReachFeed record, @Param("example") ReachFeedCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.reach_feed
     *
     * @mbg.generated Thu Nov 09 10:25:31 COT 2017
     */
    int updateByPrimaryKeySelective(ReachFeed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.reach_feed
     *
     * @mbg.generated Thu Nov 09 10:25:31 COT 2017
     */
    int updateByPrimaryKey(ReachFeed record);
}