package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.SerenoRuta;
import pe.gob.miraflores.mobile.domain.mapaincidencias.SerenoRutaCriteria;

public interface SerenoRutaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_sereno_ruta
     *
     * @mbg.generated Mon Nov 27 12:03:56 COT 2017
     */
    long countByExample(SerenoRutaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_sereno_ruta
     *
     * @mbg.generated Mon Nov 27 12:03:56 COT 2017
     */
    int deleteByExample(SerenoRutaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_sereno_ruta
     *
     * @mbg.generated Mon Nov 27 12:03:56 COT 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_sereno_ruta
     *
     * @mbg.generated Mon Nov 27 12:03:56 COT 2017
     */
    int insert(SerenoRuta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_sereno_ruta
     *
     * @mbg.generated Mon Nov 27 12:03:56 COT 2017
     */
    int insertSelective(SerenoRuta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_sereno_ruta
     *
     * @mbg.generated Mon Nov 27 12:03:56 COT 2017
     */
    List<SerenoRuta> selectByExample(SerenoRutaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_sereno_ruta
     *
     * @mbg.generated Mon Nov 27 12:03:56 COT 2017
     */
    SerenoRuta selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_sereno_ruta
     *
     * @mbg.generated Mon Nov 27 12:03:56 COT 2017
     */
    int updateByExampleSelective(@Param("record") SerenoRuta record, @Param("example") SerenoRutaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_sereno_ruta
     *
     * @mbg.generated Mon Nov 27 12:03:56 COT 2017
     */
    int updateByExample(@Param("record") SerenoRuta record, @Param("example") SerenoRutaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_sereno_ruta
     *
     * @mbg.generated Mon Nov 27 12:03:56 COT 2017
     */
    int updateByPrimaryKeySelective(SerenoRuta record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_sereno_ruta
     *
     * @mbg.generated Mon Nov 27 12:03:56 COT 2017
     */
    int updateByPrimaryKey(SerenoRuta record);
    
    
    //Insertar registro con tipo geometria
    int insertSelectiveWithGeom(SerenoRuta record);
 
    public List<SerenoRuta> selectTetraPosition(Map<String, Object> params);
    
    public List<SerenoRuta> selectTetraPositionArray(Map<String, Object> params);
    
}