package pe.gob.miraflores.mobile.dao.mapaincidencias;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.mapaincidencias.Tipificacion;
import pe.gob.miraflores.mobile.domain.mapaincidencias.TipificacionCriteria;

public interface TipificacionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    long countByExample(TipificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    int deleteByExample(TipificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    int insert(Tipificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    int insertSelective(Tipificacion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    List<Tipificacion> selectByExample(TipificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    int updateByExampleSelective(@Param("record") Tipificacion record, @Param("example") TipificacionCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.tipificacion
     *
     * @mbg.generated Wed Nov 08 15:37:35 COT 2017
     */
    int updateByExample(@Param("record") Tipificacion record, @Param("example") TipificacionCriteria example);
}