package pe.gob.miraflores.mobile.domain.auditoriapeatonal;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AuditoriaPeatonalCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    public AuditoriaPeatonalCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdFormularioIsNull() {
            addCriterion("id_formulario is null");
            return (Criteria) this;
        }

        public Criteria andIdFormularioIsNotNull() {
            addCriterion("id_formulario is not null");
            return (Criteria) this;
        }

        public Criteria andIdFormularioEqualTo(Integer value) {
            addCriterion("id_formulario =", value, "idFormulario");
            return (Criteria) this;
        }

        public Criteria andIdFormularioNotEqualTo(Integer value) {
            addCriterion("id_formulario <>", value, "idFormulario");
            return (Criteria) this;
        }

        public Criteria andIdFormularioGreaterThan(Integer value) {
            addCriterion("id_formulario >", value, "idFormulario");
            return (Criteria) this;
        }

        public Criteria andIdFormularioGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_formulario >=", value, "idFormulario");
            return (Criteria) this;
        }

        public Criteria andIdFormularioLessThan(Integer value) {
            addCriterion("id_formulario <", value, "idFormulario");
            return (Criteria) this;
        }

        public Criteria andIdFormularioLessThanOrEqualTo(Integer value) {
            addCriterion("id_formulario <=", value, "idFormulario");
            return (Criteria) this;
        }

        public Criteria andIdFormularioIn(List<Integer> values) {
            addCriterion("id_formulario in", values, "idFormulario");
            return (Criteria) this;
        }

        public Criteria andIdFormularioNotIn(List<Integer> values) {
            addCriterion("id_formulario not in", values, "idFormulario");
            return (Criteria) this;
        }

        public Criteria andIdFormularioBetween(Integer value1, Integer value2) {
            addCriterion("id_formulario between", value1, value2, "idFormulario");
            return (Criteria) this;
        }

        public Criteria andIdFormularioNotBetween(Integer value1, Integer value2) {
            addCriterion("id_formulario not between", value1, value2, "idFormulario");
            return (Criteria) this;
        }

        public Criteria andNomViaIsNull() {
            addCriterion("nom_via is null");
            return (Criteria) this;
        }

        public Criteria andNomViaIsNotNull() {
            addCriterion("nom_via is not null");
            return (Criteria) this;
        }

        public Criteria andNomViaEqualTo(String value) {
            addCriterion("nom_via =", value, "nomVia");
            return (Criteria) this;
        }

        public Criteria andNomViaNotEqualTo(String value) {
            addCriterion("nom_via <>", value, "nomVia");
            return (Criteria) this;
        }

        public Criteria andNomViaGreaterThan(String value) {
            addCriterion("nom_via >", value, "nomVia");
            return (Criteria) this;
        }

        public Criteria andNomViaGreaterThanOrEqualTo(String value) {
            addCriterion("nom_via >=", value, "nomVia");
            return (Criteria) this;
        }

        public Criteria andNomViaLessThan(String value) {
            addCriterion("nom_via <", value, "nomVia");
            return (Criteria) this;
        }

        public Criteria andNomViaLessThanOrEqualTo(String value) {
            addCriterion("nom_via <=", value, "nomVia");
            return (Criteria) this;
        }

        public Criteria andNomViaLike(String value) {
            addCriterion("nom_via like", value, "nomVia");
            return (Criteria) this;
        }

        public Criteria andNomViaNotLike(String value) {
            addCriterion("nom_via not like", value, "nomVia");
            return (Criteria) this;
        }

        public Criteria andNomViaIn(List<String> values) {
            addCriterion("nom_via in", values, "nomVia");
            return (Criteria) this;
        }

        public Criteria andNomViaNotIn(List<String> values) {
            addCriterion("nom_via not in", values, "nomVia");
            return (Criteria) this;
        }

        public Criteria andNomViaBetween(String value1, String value2) {
            addCriterion("nom_via between", value1, value2, "nomVia");
            return (Criteria) this;
        }

        public Criteria andNomViaNotBetween(String value1, String value2) {
            addCriterion("nom_via not between", value1, value2, "nomVia");
            return (Criteria) this;
        }

        public Criteria andCodViaIsNull() {
            addCriterion("cod_via is null");
            return (Criteria) this;
        }

        public Criteria andCodViaIsNotNull() {
            addCriterion("cod_via is not null");
            return (Criteria) this;
        }

        public Criteria andCodViaEqualTo(Integer value) {
            addCriterion("cod_via =", value, "codVia");
            return (Criteria) this;
        }

        public Criteria andCodViaNotEqualTo(Integer value) {
            addCriterion("cod_via <>", value, "codVia");
            return (Criteria) this;
        }

        public Criteria andCodViaGreaterThan(Integer value) {
            addCriterion("cod_via >", value, "codVia");
            return (Criteria) this;
        }

        public Criteria andCodViaGreaterThanOrEqualTo(Integer value) {
            addCriterion("cod_via >=", value, "codVia");
            return (Criteria) this;
        }

        public Criteria andCodViaLessThan(Integer value) {
            addCriterion("cod_via <", value, "codVia");
            return (Criteria) this;
        }

        public Criteria andCodViaLessThanOrEqualTo(Integer value) {
            addCriterion("cod_via <=", value, "codVia");
            return (Criteria) this;
        }

        public Criteria andCodViaIn(List<Integer> values) {
            addCriterion("cod_via in", values, "codVia");
            return (Criteria) this;
        }

        public Criteria andCodViaNotIn(List<Integer> values) {
            addCriterion("cod_via not in", values, "codVia");
            return (Criteria) this;
        }

        public Criteria andCodViaBetween(Integer value1, Integer value2) {
            addCriterion("cod_via between", value1, value2, "codVia");
            return (Criteria) this;
        }

        public Criteria andCodViaNotBetween(Integer value1, Integer value2) {
            addCriterion("cod_via not between", value1, value2, "codVia");
            return (Criteria) this;
        }

        public Criteria andNumCuadraIsNull() {
            addCriterion("num_cuadra is null");
            return (Criteria) this;
        }

        public Criteria andNumCuadraIsNotNull() {
            addCriterion("num_cuadra is not null");
            return (Criteria) this;
        }

        public Criteria andNumCuadraEqualTo(Integer value) {
            addCriterion("num_cuadra =", value, "numCuadra");
            return (Criteria) this;
        }

        public Criteria andNumCuadraNotEqualTo(Integer value) {
            addCriterion("num_cuadra <>", value, "numCuadra");
            return (Criteria) this;
        }

        public Criteria andNumCuadraGreaterThan(Integer value) {
            addCriterion("num_cuadra >", value, "numCuadra");
            return (Criteria) this;
        }

        public Criteria andNumCuadraGreaterThanOrEqualTo(Integer value) {
            addCriterion("num_cuadra >=", value, "numCuadra");
            return (Criteria) this;
        }

        public Criteria andNumCuadraLessThan(Integer value) {
            addCriterion("num_cuadra <", value, "numCuadra");
            return (Criteria) this;
        }

        public Criteria andNumCuadraLessThanOrEqualTo(Integer value) {
            addCriterion("num_cuadra <=", value, "numCuadra");
            return (Criteria) this;
        }

        public Criteria andNumCuadraIn(List<Integer> values) {
            addCriterion("num_cuadra in", values, "numCuadra");
            return (Criteria) this;
        }

        public Criteria andNumCuadraNotIn(List<Integer> values) {
            addCriterion("num_cuadra not in", values, "numCuadra");
            return (Criteria) this;
        }

        public Criteria andNumCuadraBetween(Integer value1, Integer value2) {
            addCriterion("num_cuadra between", value1, value2, "numCuadra");
            return (Criteria) this;
        }

        public Criteria andNumCuadraNotBetween(Integer value1, Integer value2) {
            addCriterion("num_cuadra not between", value1, value2, "numCuadra");
            return (Criteria) this;
        }

        public Criteria andLadoIsNull() {
            addCriterion("lado is null");
            return (Criteria) this;
        }

        public Criteria andLadoIsNotNull() {
            addCriterion("lado is not null");
            return (Criteria) this;
        }

        public Criteria andLadoEqualTo(String value) {
            addCriterion("lado =", value, "lado");
            return (Criteria) this;
        }

        public Criteria andLadoNotEqualTo(String value) {
            addCriterion("lado <>", value, "lado");
            return (Criteria) this;
        }

        public Criteria andLadoGreaterThan(String value) {
            addCriterion("lado >", value, "lado");
            return (Criteria) this;
        }

        public Criteria andLadoGreaterThanOrEqualTo(String value) {
            addCriterion("lado >=", value, "lado");
            return (Criteria) this;
        }

        public Criteria andLadoLessThan(String value) {
            addCriterion("lado <", value, "lado");
            return (Criteria) this;
        }

        public Criteria andLadoLessThanOrEqualTo(String value) {
            addCriterion("lado <=", value, "lado");
            return (Criteria) this;
        }

        public Criteria andLadoLike(String value) {
            addCriterion("lado like", value, "lado");
            return (Criteria) this;
        }

        public Criteria andLadoNotLike(String value) {
            addCriterion("lado not like", value, "lado");
            return (Criteria) this;
        }

        public Criteria andLadoIn(List<String> values) {
            addCriterion("lado in", values, "lado");
            return (Criteria) this;
        }

        public Criteria andLadoNotIn(List<String> values) {
            addCriterion("lado not in", values, "lado");
            return (Criteria) this;
        }

        public Criteria andLadoBetween(String value1, String value2) {
            addCriterion("lado between", value1, value2, "lado");
            return (Criteria) this;
        }

        public Criteria andLadoNotBetween(String value1, String value2) {
            addCriterion("lado not between", value1, value2, "lado");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaIsNull() {
            addCriterion("id_categoria is null");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaIsNotNull() {
            addCriterion("id_categoria is not null");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaEqualTo(Integer value) {
            addCriterion("id_categoria =", value, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaNotEqualTo(Integer value) {
            addCriterion("id_categoria <>", value, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaGreaterThan(Integer value) {
            addCriterion("id_categoria >", value, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaGreaterThanOrEqualTo(Integer value) {
            addCriterion("id_categoria >=", value, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaLessThan(Integer value) {
            addCriterion("id_categoria <", value, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaLessThanOrEqualTo(Integer value) {
            addCriterion("id_categoria <=", value, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaIn(List<Integer> values) {
            addCriterion("id_categoria in", values, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaNotIn(List<Integer> values) {
            addCriterion("id_categoria not in", values, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaBetween(Integer value1, Integer value2) {
            addCriterion("id_categoria between", value1, value2, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andIdCategoriaNotBetween(Integer value1, Integer value2) {
            addCriterion("id_categoria not between", value1, value2, "idCategoria");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNull() {
            addCriterion("descripcion is null");
            return (Criteria) this;
        }

        public Criteria andDescripcionIsNotNull() {
            addCriterion("descripcion is not null");
            return (Criteria) this;
        }

        public Criteria andDescripcionEqualTo(String value) {
            addCriterion("descripcion =", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotEqualTo(String value) {
            addCriterion("descripcion <>", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThan(String value) {
            addCriterion("descripcion >", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionGreaterThanOrEqualTo(String value) {
            addCriterion("descripcion >=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThan(String value) {
            addCriterion("descripcion <", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLessThanOrEqualTo(String value) {
            addCriterion("descripcion <=", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionLike(String value) {
            addCriterion("descripcion like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotLike(String value) {
            addCriterion("descripcion not like", value, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionIn(List<String> values) {
            addCriterion("descripcion in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotIn(List<String> values) {
            addCriterion("descripcion not in", values, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionBetween(String value1, String value2) {
            addCriterion("descripcion between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andDescripcionNotBetween(String value1, String value2) {
            addCriterion("descripcion not between", value1, value2, "descripcion");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaIsNull() {
            addCriterion("solucion_rapida is null");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaIsNotNull() {
            addCriterion("solucion_rapida is not null");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaEqualTo(String value) {
            addCriterion("solucion_rapida =", value, "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaNotEqualTo(String value) {
            addCriterion("solucion_rapida <>", value, "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaGreaterThan(String value) {
            addCriterion("solucion_rapida >", value, "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaGreaterThanOrEqualTo(String value) {
            addCriterion("solucion_rapida >=", value, "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaLessThan(String value) {
            addCriterion("solucion_rapida <", value, "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaLessThanOrEqualTo(String value) {
            addCriterion("solucion_rapida <=", value, "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaLike(String value) {
            addCriterion("solucion_rapida like", value, "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaNotLike(String value) {
            addCriterion("solucion_rapida not like", value, "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaIn(List<String> values) {
            addCriterion("solucion_rapida in", values, "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaNotIn(List<String> values) {
            addCriterion("solucion_rapida not in", values, "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaBetween(String value1, String value2) {
            addCriterion("solucion_rapida between", value1, value2, "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaNotBetween(String value1, String value2) {
            addCriterion("solucion_rapida not between", value1, value2, "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andNombreFotoIsNull() {
            addCriterion("nombre_foto is null");
            return (Criteria) this;
        }

        public Criteria andNombreFotoIsNotNull() {
            addCriterion("nombre_foto is not null");
            return (Criteria) this;
        }

        public Criteria andNombreFotoEqualTo(String value) {
            addCriterion("nombre_foto =", value, "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andNombreFotoNotEqualTo(String value) {
            addCriterion("nombre_foto <>", value, "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andNombreFotoGreaterThan(String value) {
            addCriterion("nombre_foto >", value, "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andNombreFotoGreaterThanOrEqualTo(String value) {
            addCriterion("nombre_foto >=", value, "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andNombreFotoLessThan(String value) {
            addCriterion("nombre_foto <", value, "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andNombreFotoLessThanOrEqualTo(String value) {
            addCriterion("nombre_foto <=", value, "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andNombreFotoLike(String value) {
            addCriterion("nombre_foto like", value, "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andNombreFotoNotLike(String value) {
            addCriterion("nombre_foto not like", value, "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andNombreFotoIn(List<String> values) {
            addCriterion("nombre_foto in", values, "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andNombreFotoNotIn(List<String> values) {
            addCriterion("nombre_foto not in", values, "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andNombreFotoBetween(String value1, String value2) {
            addCriterion("nombre_foto between", value1, value2, "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andNombreFotoNotBetween(String value1, String value2) {
            addCriterion("nombre_foto not between", value1, value2, "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoIsNull() {
            addCriterion("url_foto is null");
            return (Criteria) this;
        }

        public Criteria andUrlFotoIsNotNull() {
            addCriterion("url_foto is not null");
            return (Criteria) this;
        }

        public Criteria andUrlFotoEqualTo(String value) {
            addCriterion("url_foto =", value, "urlFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoNotEqualTo(String value) {
            addCriterion("url_foto <>", value, "urlFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoGreaterThan(String value) {
            addCriterion("url_foto >", value, "urlFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoGreaterThanOrEqualTo(String value) {
            addCriterion("url_foto >=", value, "urlFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoLessThan(String value) {
            addCriterion("url_foto <", value, "urlFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoLessThanOrEqualTo(String value) {
            addCriterion("url_foto <=", value, "urlFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoLike(String value) {
            addCriterion("url_foto like", value, "urlFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoNotLike(String value) {
            addCriterion("url_foto not like", value, "urlFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoIn(List<String> values) {
            addCriterion("url_foto in", values, "urlFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoNotIn(List<String> values) {
            addCriterion("url_foto not in", values, "urlFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoBetween(String value1, String value2) {
            addCriterion("url_foto between", value1, value2, "urlFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoNotBetween(String value1, String value2) {
            addCriterion("url_foto not between", value1, value2, "urlFoto");
            return (Criteria) this;
        }

        public Criteria andSubZonaIsNull() {
            addCriterion("sub_zona is null");
            return (Criteria) this;
        }

        public Criteria andSubZonaIsNotNull() {
            addCriterion("sub_zona is not null");
            return (Criteria) this;
        }

        public Criteria andSubZonaEqualTo(Integer value) {
            addCriterion("sub_zona =", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotEqualTo(Integer value) {
            addCriterion("sub_zona <>", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaGreaterThan(Integer value) {
            addCriterion("sub_zona >", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaGreaterThanOrEqualTo(Integer value) {
            addCriterion("sub_zona >=", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLessThan(Integer value) {
            addCriterion("sub_zona <", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLessThanOrEqualTo(Integer value) {
            addCriterion("sub_zona <=", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaIn(List<Integer> values) {
            addCriterion("sub_zona in", values, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotIn(List<Integer> values) {
            addCriterion("sub_zona not in", values, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaBetween(Integer value1, Integer value2) {
            addCriterion("sub_zona between", value1, value2, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotBetween(Integer value1, Integer value2) {
            addCriterion("sub_zona not between", value1, value2, "subZona");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNull() {
            addCriterion("estado is null");
            return (Criteria) this;
        }

        public Criteria andEstadoIsNotNull() {
            addCriterion("estado is not null");
            return (Criteria) this;
        }

        public Criteria andEstadoEqualTo(String value) {
            addCriterion("estado =", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotEqualTo(String value) {
            addCriterion("estado <>", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThan(String value) {
            addCriterion("estado >", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoGreaterThanOrEqualTo(String value) {
            addCriterion("estado >=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThan(String value) {
            addCriterion("estado <", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLessThanOrEqualTo(String value) {
            addCriterion("estado <=", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoLike(String value) {
            addCriterion("estado like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotLike(String value) {
            addCriterion("estado not like", value, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoIn(List<String> values) {
            addCriterion("estado in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotIn(List<String> values) {
            addCriterion("estado not in", values, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoBetween(String value1, String value2) {
            addCriterion("estado between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andEstadoNotBetween(String value1, String value2) {
            addCriterion("estado not between", value1, value2, "estado");
            return (Criteria) this;
        }

        public Criteria andFechaRegistraIsNull() {
            addCriterion("fecha_registra is null");
            return (Criteria) this;
        }

        public Criteria andFechaRegistraIsNotNull() {
            addCriterion("fecha_registra is not null");
            return (Criteria) this;
        }

        public Criteria andFechaRegistraEqualTo(Date value) {
            addCriterion("fecha_registra =", value, "fechaRegistra");
            return (Criteria) this;
        }

        public Criteria andFechaRegistraNotEqualTo(Date value) {
            addCriterion("fecha_registra <>", value, "fechaRegistra");
            return (Criteria) this;
        }

        public Criteria andFechaRegistraGreaterThan(Date value) {
            addCriterion("fecha_registra >", value, "fechaRegistra");
            return (Criteria) this;
        }

        public Criteria andFechaRegistraGreaterThanOrEqualTo(Date value) {
            addCriterion("fecha_registra >=", value, "fechaRegistra");
            return (Criteria) this;
        }

        public Criteria andFechaRegistraLessThan(Date value) {
            addCriterion("fecha_registra <", value, "fechaRegistra");
            return (Criteria) this;
        }

        public Criteria andFechaRegistraLessThanOrEqualTo(Date value) {
            addCriterion("fecha_registra <=", value, "fechaRegistra");
            return (Criteria) this;
        }

        public Criteria andFechaRegistraIn(List<Date> values) {
            addCriterion("fecha_registra in", values, "fechaRegistra");
            return (Criteria) this;
        }

        public Criteria andFechaRegistraNotIn(List<Date> values) {
            addCriterion("fecha_registra not in", values, "fechaRegistra");
            return (Criteria) this;
        }

        public Criteria andFechaRegistraBetween(Date value1, Date value2) {
            addCriterion("fecha_registra between", value1, value2, "fechaRegistra");
            return (Criteria) this;
        }

        public Criteria andFechaRegistraNotBetween(Date value1, Date value2) {
            addCriterion("fecha_registra not between", value1, value2, "fechaRegistra");
            return (Criteria) this;
        }

        public Criteria andNomViaLikeInsensitive(String value) {
            addCriterion("upper(nom_via) like", value.toUpperCase(), "nomVia");
            return (Criteria) this;
        }

        public Criteria andLadoLikeInsensitive(String value) {
            addCriterion("upper(lado) like", value.toUpperCase(), "lado");
            return (Criteria) this;
        }

        public Criteria andDescripcionLikeInsensitive(String value) {
            addCriterion("upper(descripcion) like", value.toUpperCase(), "descripcion");
            return (Criteria) this;
        }

        public Criteria andSolucionRapidaLikeInsensitive(String value) {
            addCriterion("upper(solucion_rapida) like", value.toUpperCase(), "solucionRapida");
            return (Criteria) this;
        }

        public Criteria andNombreFotoLikeInsensitive(String value) {
            addCriterion("upper(nombre_foto) like", value.toUpperCase(), "nombreFoto");
            return (Criteria) this;
        }

        public Criteria andUrlFotoLikeInsensitive(String value) {
            addCriterion("upper(url_foto) like", value.toUpperCase(), "urlFoto");
            return (Criteria) this;
        }

        public Criteria andEstadoLikeInsensitive(String value) {
            addCriterion("upper(estado) like", value.toUpperCase(), "estado");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 10 11:38:24 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.ape_formulario
     *
     * @mbg.generated Mon Jul 10 11:38:24 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}