package pe.gob.miraflores.mobile.dao.seguridad;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.seguridad.RolHistorico;
import pe.gob.miraflores.mobile.domain.seguridad.RolHistoricoCriteria;

public interface RolHistoricoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_rol_hist
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    long countByExample(RolHistoricoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_rol_hist
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int deleteByExample(RolHistoricoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_rol_hist
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int insert(RolHistorico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_rol_hist
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int insertSelective(RolHistorico record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_rol_hist
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    List<RolHistorico> selectByExample(RolHistoricoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_rol_hist
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int updateByExampleSelective(@Param("record") RolHistorico record, @Param("example") RolHistoricoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_rol_hist
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int updateByExample(@Param("record") RolHistorico record, @Param("example") RolHistoricoCriteria example);
}