package pe.gob.miraflores.mobile.dao.seguridad;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.seguridad.UsuarioLogin;
import pe.gob.miraflores.mobile.domain.seguridad.UsuarioLogin;
import pe.gob.miraflores.mobile.domain.seguridad.UsuarioLoginCriteria;

public interface UsuarioLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    long countByExample(UsuarioLoginCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int deleteByExample(UsuarioLoginCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int deleteByPrimaryKey(Integer ideUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int insert(UsuarioLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int insertSelective(UsuarioLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    List<UsuarioLogin> selectByExample(UsuarioLoginCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    UsuarioLogin selectByPrimaryKey(Integer ideUsuario);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int updateByExampleSelective(@Param("record") UsuarioLogin record, @Param("example") UsuarioLoginCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int updateByExample(@Param("record") UsuarioLogin record, @Param("example") UsuarioLoginCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int updateByPrimaryKeySelective(UsuarioLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    int updateByPrimaryKey(UsuarioLogin record);
    
    List<UsuarioLogin> getUsuariosRegistroCCNotificacion(Map<String, Object> params);
    
    int resetRol(Map<String, Object> params);
    
}