package pe.gob.miraflores.mobile.domain.infovigilante;

import java.util.ArrayList;
import java.util.List;

public class GeoInfoVigilanteCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    public GeoInfoVigilanteCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoIsNull() {
            addCriterion("nombre_completo is null");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoIsNotNull() {
            addCriterion("nombre_completo is not null");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoEqualTo(String value) {
            addCriterion("nombre_completo =", value, "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoNotEqualTo(String value) {
            addCriterion("nombre_completo <>", value, "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoGreaterThan(String value) {
            addCriterion("nombre_completo >", value, "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoGreaterThanOrEqualTo(String value) {
            addCriterion("nombre_completo >=", value, "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoLessThan(String value) {
            addCriterion("nombre_completo <", value, "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoLessThanOrEqualTo(String value) {
            addCriterion("nombre_completo <=", value, "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoLike(String value) {
            addCriterion("nombre_completo like", value, "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoNotLike(String value) {
            addCriterion("nombre_completo not like", value, "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoIn(List<String> values) {
            addCriterion("nombre_completo in", values, "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoNotIn(List<String> values) {
            addCriterion("nombre_completo not in", values, "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoBetween(String value1, String value2) {
            addCriterion("nombre_completo between", value1, value2, "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoNotBetween(String value1, String value2) {
            addCriterion("nombre_completo not between", value1, value2, "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andDniIsNull() {
            addCriterion("dni is null");
            return (Criteria) this;
        }

        public Criteria andDniIsNotNull() {
            addCriterion("dni is not null");
            return (Criteria) this;
        }

        public Criteria andDniEqualTo(String value) {
            addCriterion("dni =", value, "dni");
            return (Criteria) this;
        }

        public Criteria andDniNotEqualTo(String value) {
            addCriterion("dni <>", value, "dni");
            return (Criteria) this;
        }

        public Criteria andDniGreaterThan(String value) {
            addCriterion("dni >", value, "dni");
            return (Criteria) this;
        }

        public Criteria andDniGreaterThanOrEqualTo(String value) {
            addCriterion("dni >=", value, "dni");
            return (Criteria) this;
        }

        public Criteria andDniLessThan(String value) {
            addCriterion("dni <", value, "dni");
            return (Criteria) this;
        }

        public Criteria andDniLessThanOrEqualTo(String value) {
            addCriterion("dni <=", value, "dni");
            return (Criteria) this;
        }

        public Criteria andDniLike(String value) {
            addCriterion("dni like", value, "dni");
            return (Criteria) this;
        }

        public Criteria andDniNotLike(String value) {
            addCriterion("dni not like", value, "dni");
            return (Criteria) this;
        }

        public Criteria andDniIn(List<String> values) {
            addCriterion("dni in", values, "dni");
            return (Criteria) this;
        }

        public Criteria andDniNotIn(List<String> values) {
            addCriterion("dni not in", values, "dni");
            return (Criteria) this;
        }

        public Criteria andDniBetween(String value1, String value2) {
            addCriterion("dni between", value1, value2, "dni");
            return (Criteria) this;
        }

        public Criteria andDniNotBetween(String value1, String value2) {
            addCriterion("dni not between", value1, value2, "dni");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioIsNull() {
            addCriterion("prestacion_servicio is null");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioIsNotNull() {
            addCriterion("prestacion_servicio is not null");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioEqualTo(String value) {
            addCriterion("prestacion_servicio =", value, "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioNotEqualTo(String value) {
            addCriterion("prestacion_servicio <>", value, "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioGreaterThan(String value) {
            addCriterion("prestacion_servicio >", value, "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioGreaterThanOrEqualTo(String value) {
            addCriterion("prestacion_servicio >=", value, "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioLessThan(String value) {
            addCriterion("prestacion_servicio <", value, "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioLessThanOrEqualTo(String value) {
            addCriterion("prestacion_servicio <=", value, "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioLike(String value) {
            addCriterion("prestacion_servicio like", value, "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioNotLike(String value) {
            addCriterion("prestacion_servicio not like", value, "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioIn(List<String> values) {
            addCriterion("prestacion_servicio in", values, "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioNotIn(List<String> values) {
            addCriterion("prestacion_servicio not in", values, "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioBetween(String value1, String value2) {
            addCriterion("prestacion_servicio between", value1, value2, "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioNotBetween(String value1, String value2) {
            addCriterion("prestacion_servicio not between", value1, value2, "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andTelefonoIsNull() {
            addCriterion("telefono is null");
            return (Criteria) this;
        }

        public Criteria andTelefonoIsNotNull() {
            addCriterion("telefono is not null");
            return (Criteria) this;
        }

        public Criteria andTelefonoEqualTo(String value) {
            addCriterion("telefono =", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotEqualTo(String value) {
            addCriterion("telefono <>", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoGreaterThan(String value) {
            addCriterion("telefono >", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoGreaterThanOrEqualTo(String value) {
            addCriterion("telefono >=", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLessThan(String value) {
            addCriterion("telefono <", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLessThanOrEqualTo(String value) {
            addCriterion("telefono <=", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoLike(String value) {
            addCriterion("telefono like", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotLike(String value) {
            addCriterion("telefono not like", value, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoIn(List<String> values) {
            addCriterion("telefono in", values, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotIn(List<String> values) {
            addCriterion("telefono not in", values, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoBetween(String value1, String value2) {
            addCriterion("telefono between", value1, value2, "telefono");
            return (Criteria) this;
        }

        public Criteria andTelefonoNotBetween(String value1, String value2) {
            addCriterion("telefono not between", value1, value2, "telefono");
            return (Criteria) this;
        }

        public Criteria andCargoIsNull() {
            addCriterion("cargo is null");
            return (Criteria) this;
        }

        public Criteria andCargoIsNotNull() {
            addCriterion("cargo is not null");
            return (Criteria) this;
        }

        public Criteria andCargoEqualTo(String value) {
            addCriterion("cargo =", value, "cargo");
            return (Criteria) this;
        }

        public Criteria andCargoNotEqualTo(String value) {
            addCriterion("cargo <>", value, "cargo");
            return (Criteria) this;
        }

        public Criteria andCargoGreaterThan(String value) {
            addCriterion("cargo >", value, "cargo");
            return (Criteria) this;
        }

        public Criteria andCargoGreaterThanOrEqualTo(String value) {
            addCriterion("cargo >=", value, "cargo");
            return (Criteria) this;
        }

        public Criteria andCargoLessThan(String value) {
            addCriterion("cargo <", value, "cargo");
            return (Criteria) this;
        }

        public Criteria andCargoLessThanOrEqualTo(String value) {
            addCriterion("cargo <=", value, "cargo");
            return (Criteria) this;
        }

        public Criteria andCargoLike(String value) {
            addCriterion("cargo like", value, "cargo");
            return (Criteria) this;
        }

        public Criteria andCargoNotLike(String value) {
            addCriterion("cargo not like", value, "cargo");
            return (Criteria) this;
        }

        public Criteria andCargoIn(List<String> values) {
            addCriterion("cargo in", values, "cargo");
            return (Criteria) this;
        }

        public Criteria andCargoNotIn(List<String> values) {
            addCriterion("cargo not in", values, "cargo");
            return (Criteria) this;
        }

        public Criteria andCargoBetween(String value1, String value2) {
            addCriterion("cargo between", value1, value2, "cargo");
            return (Criteria) this;
        }

        public Criteria andCargoNotBetween(String value1, String value2) {
            addCriterion("cargo not between", value1, value2, "cargo");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andSubZonaIsNull() {
            addCriterion("sub_zona is null");
            return (Criteria) this;
        }

        public Criteria andSubZonaIsNotNull() {
            addCriterion("sub_zona is not null");
            return (Criteria) this;
        }

        public Criteria andSubZonaEqualTo(String value) {
            addCriterion("sub_zona =", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotEqualTo(String value) {
            addCriterion("sub_zona <>", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaGreaterThan(String value) {
            addCriterion("sub_zona >", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaGreaterThanOrEqualTo(String value) {
            addCriterion("sub_zona >=", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLessThan(String value) {
            addCriterion("sub_zona <", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLessThanOrEqualTo(String value) {
            addCriterion("sub_zona <=", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaLike(String value) {
            addCriterion("sub_zona like", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotLike(String value) {
            addCriterion("sub_zona not like", value, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaIn(List<String> values) {
            addCriterion("sub_zona in", values, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotIn(List<String> values) {
            addCriterion("sub_zona not in", values, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaBetween(String value1, String value2) {
            addCriterion("sub_zona between", value1, value2, "subZona");
            return (Criteria) this;
        }

        public Criteria andSubZonaNotBetween(String value1, String value2) {
            addCriterion("sub_zona not between", value1, value2, "subZona");
            return (Criteria) this;
        }

        public Criteria andTurnoIsNull() {
            addCriterion("turno is null");
            return (Criteria) this;
        }

        public Criteria andTurnoIsNotNull() {
            addCriterion("turno is not null");
            return (Criteria) this;
        }

        public Criteria andTurnoEqualTo(String value) {
            addCriterion("turno =", value, "turno");
            return (Criteria) this;
        }

        public Criteria andTurnoNotEqualTo(String value) {
            addCriterion("turno <>", value, "turno");
            return (Criteria) this;
        }

        public Criteria andTurnoGreaterThan(String value) {
            addCriterion("turno >", value, "turno");
            return (Criteria) this;
        }

        public Criteria andTurnoGreaterThanOrEqualTo(String value) {
            addCriterion("turno >=", value, "turno");
            return (Criteria) this;
        }

        public Criteria andTurnoLessThan(String value) {
            addCriterion("turno <", value, "turno");
            return (Criteria) this;
        }

        public Criteria andTurnoLessThanOrEqualTo(String value) {
            addCriterion("turno <=", value, "turno");
            return (Criteria) this;
        }

        public Criteria andTurnoLike(String value) {
            addCriterion("turno like", value, "turno");
            return (Criteria) this;
        }

        public Criteria andTurnoNotLike(String value) {
            addCriterion("turno not like", value, "turno");
            return (Criteria) this;
        }

        public Criteria andTurnoIn(List<String> values) {
            addCriterion("turno in", values, "turno");
            return (Criteria) this;
        }

        public Criteria andTurnoNotIn(List<String> values) {
            addCriterion("turno not in", values, "turno");
            return (Criteria) this;
        }

        public Criteria andTurnoBetween(String value1, String value2) {
            addCriterion("turno between", value1, value2, "turno");
            return (Criteria) this;
        }

        public Criteria andTurnoNotBetween(String value1, String value2) {
            addCriterion("turno not between", value1, value2, "turno");
            return (Criteria) this;
        }

        public Criteria andCordenadasIsNull() {
            addCriterion("cordenadas is null");
            return (Criteria) this;
        }

        public Criteria andCordenadasIsNotNull() {
            addCriterion("cordenadas is not null");
            return (Criteria) this;
        }

        public Criteria andCordenadasEqualTo(String value) {
            addCriterion("cordenadas =", value, "cordenadas");
            return (Criteria) this;
        }

        public Criteria andCordenadasNotEqualTo(String value) {
            addCriterion("cordenadas <>", value, "cordenadas");
            return (Criteria) this;
        }

        public Criteria andCordenadasGreaterThan(String value) {
            addCriterion("cordenadas >", value, "cordenadas");
            return (Criteria) this;
        }

        public Criteria andCordenadasGreaterThanOrEqualTo(String value) {
            addCriterion("cordenadas >=", value, "cordenadas");
            return (Criteria) this;
        }

        public Criteria andCordenadasLessThan(String value) {
            addCriterion("cordenadas <", value, "cordenadas");
            return (Criteria) this;
        }

        public Criteria andCordenadasLessThanOrEqualTo(String value) {
            addCriterion("cordenadas <=", value, "cordenadas");
            return (Criteria) this;
        }

        public Criteria andCordenadasLike(String value) {
            addCriterion("cordenadas like", value, "cordenadas");
            return (Criteria) this;
        }

        public Criteria andCordenadasNotLike(String value) {
            addCriterion("cordenadas not like", value, "cordenadas");
            return (Criteria) this;
        }

        public Criteria andCordenadasIn(List<String> values) {
            addCriterion("cordenadas in", values, "cordenadas");
            return (Criteria) this;
        }

        public Criteria andCordenadasNotIn(List<String> values) {
            addCriterion("cordenadas not in", values, "cordenadas");
            return (Criteria) this;
        }

        public Criteria andCordenadasBetween(String value1, String value2) {
            addCriterion("cordenadas between", value1, value2, "cordenadas");
            return (Criteria) this;
        }

        public Criteria andCordenadasNotBetween(String value1, String value2) {
            addCriterion("cordenadas not between", value1, value2, "cordenadas");
            return (Criteria) this;
        }

        public Criteria andNombreCompletoLikeInsensitive(String value) {
            addCriterion("upper(nombre_completo) like", value.toUpperCase(), "nombreCompleto");
            return (Criteria) this;
        }

        public Criteria andDniLikeInsensitive(String value) {
            addCriterion("upper(dni) like", value.toUpperCase(), "dni");
            return (Criteria) this;
        }

        public Criteria andPrestacionServicioLikeInsensitive(String value) {
            addCriterion("upper(prestacion_servicio) like", value.toUpperCase(), "prestacionServicio");
            return (Criteria) this;
        }

        public Criteria andTelefonoLikeInsensitive(String value) {
            addCriterion("upper(telefono) like", value.toUpperCase(), "telefono");
            return (Criteria) this;
        }

        public Criteria andCargoLikeInsensitive(String value) {
            addCriterion("upper(cargo) like", value.toUpperCase(), "cargo");
            return (Criteria) this;
        }

        public Criteria andAreaLikeInsensitive(String value) {
            addCriterion("upper(area) like", value.toUpperCase(), "area");
            return (Criteria) this;
        }

        public Criteria andSubZonaLikeInsensitive(String value) {
            addCriterion("upper(sub_zona) like", value.toUpperCase(), "subZona");
            return (Criteria) this;
        }

        public Criteria andTurnoLikeInsensitive(String value) {
            addCriterion("upper(turno) like", value.toUpperCase(), "turno");
            return (Criteria) this;
        }

        public Criteria andCordenadasLikeInsensitive(String value) {
            addCriterion("upper(cordenadas) like", value.toUpperCase(), "cordenadas");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 10 12:16:21 COT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mapa.geo_info_vigilantes
     *
     * @mbg.generated Mon Jul 10 12:16:21 COT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}