package pe.gob.miraflores.mobile.catastro.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import pe.gob.miraflores.mobile.domain.catastro.Distrito;
import pe.gob.miraflores.mobile.domain.catastro.DistritoCriteria;

public interface DistritoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test.distritos
     *
     * @mbggenerated Wed Dec 23 16:09:20 COT 2015
     */
    int countByExample(DistritoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test.distritos
     *
     * @mbggenerated Wed Dec 23 16:09:20 COT 2015
     */
    int deleteByExample(DistritoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test.distritos
     *
     * @mbggenerated Wed Dec 23 16:09:20 COT 2015
     */
    int deleteByPrimaryKey(Integer distritoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test.distritos
     *
     * @mbggenerated Wed Dec 23 16:09:20 COT 2015
     */
    int insert(Distrito record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test.distritos
     *
     * @mbggenerated Wed Dec 23 16:09:20 COT 2015
     */
    int insertSelective(Distrito record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test.distritos
     *
     * @mbggenerated Wed Dec 23 16:09:20 COT 2015
     */
    List<Distrito> selectByExample(DistritoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test.distritos
     *
     * @mbggenerated Wed Dec 23 16:09:20 COT 2015
     */
    Distrito selectByPrimaryKey(Integer distritoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test.distritos
     *
     * @mbggenerated Wed Dec 23 16:09:20 COT 2015
     */
    int updateByExampleSelective(@Param("record") Distrito record, @Param("example") DistritoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test.distritos
     *
     * @mbggenerated Wed Dec 23 16:09:20 COT 2015
     */
    int updateByExample(@Param("record") Distrito record, @Param("example") DistritoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test.distritos
     *
     * @mbggenerated Wed Dec 23 16:09:20 COT 2015
     */
    int updateByPrimaryKeySelective(Distrito record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test.distritos
     *
     * @mbggenerated Wed Dec 23 16:09:20 COT 2015
     */
    int updateByPrimaryKey(Distrito record);
    
    List<Distrito> obtenerDistritoPorCentroide(Map<String, Object> params);
    
}