package pe.gob.miraflores.mobile.catastro.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import pe.gob.miraflores.mobile.domain.catastro.ZonaCatastro;
import pe.gob.miraflores.mobile.domain.catastro.ZonaCatastroCriteria;

public interface ZonaCatastroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catastro.zonas
     *
     * @mbggenerated Thu Aug 04 15:39:20 COT 2016
     */
    int countByExample(ZonaCatastroCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catastro.zonas
     *
     * @mbggenerated Thu Aug 04 15:39:20 COT 2016
     */
    int deleteByExample(ZonaCatastroCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catastro.zonas
     *
     * @mbggenerated Thu Aug 04 15:39:20 COT 2016
     */
    int deleteByPrimaryKey(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catastro.zonas
     *
     * @mbggenerated Thu Aug 04 15:39:20 COT 2016
     */
    int insert(ZonaCatastro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catastro.zonas
     *
     * @mbggenerated Thu Aug 04 15:39:20 COT 2016
     */
    int insertSelective(ZonaCatastro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catastro.zonas
     *
     * @mbggenerated Thu Aug 04 15:39:20 COT 2016
     */
    List<ZonaCatastro> selectByExample(ZonaCatastroCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catastro.zonas
     *
     * @mbggenerated Thu Aug 04 15:39:20 COT 2016
     */
    ZonaCatastro selectByPrimaryKey(Integer gid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catastro.zonas
     *
     * @mbggenerated Thu Aug 04 15:39:20 COT 2016
     */
    int updateByExampleSelective(@Param("record") ZonaCatastro record, @Param("example") ZonaCatastroCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catastro.zonas
     *
     * @mbggenerated Thu Aug 04 15:39:20 COT 2016
     */
    int updateByExample(@Param("record") ZonaCatastro record, @Param("example") ZonaCatastroCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catastro.zonas
     *
     * @mbggenerated Thu Aug 04 15:39:20 COT 2016
     */
    int updateByPrimaryKeySelective(ZonaCatastro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table catastro.zonas
     *
     * @mbggenerated Thu Aug 04 15:39:20 COT 2016
     */
    int updateByPrimaryKey(ZonaCatastro record);
    
    public Map<String, Object> selectSectorZonaByCordenada(Map<String, Object> punto);
    
    public List<Map<String, Object>> selectPoligonoZona();
    
}