package pe.gob.miraflores.mobile.domain.seguridad;

import java.util.Date;

public class Opcion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_opcion.id_opcion
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    private Integer idOpcion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_opcion.nombre
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_opcion.definicion
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    private String definicion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_opcion.fec_registra
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    private Date fecRegistra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_opcion.fec_modifica
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    private Date fecModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_opcion.des_usu_registra
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    private String desUsuRegistra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_opcion.des_usu_modifica
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    private String desUsuModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_opcion.des_ip_registra
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    private String desIpRegistra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_opcion.des_ip_modifica
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    private String desIpModifica;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_opcion.id_opcion
     *
     * @return the value of mapa.geo_map_opcion.id_opcion
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public Integer getIdOpcion() {
        return idOpcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_opcion.id_opcion
     *
     * @param idOpcion the value for mapa.geo_map_opcion.id_opcion
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public void setIdOpcion(Integer idOpcion) {
        this.idOpcion = idOpcion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_opcion.nombre
     *
     * @return the value of mapa.geo_map_opcion.nombre
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_opcion.nombre
     *
     * @param nombre the value for mapa.geo_map_opcion.nombre
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_opcion.definicion
     *
     * @return the value of mapa.geo_map_opcion.definicion
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public String getDefinicion() {
        return definicion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_opcion.definicion
     *
     * @param definicion the value for mapa.geo_map_opcion.definicion
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public void setDefinicion(String definicion) {
        this.definicion = definicion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_opcion.fec_registra
     *
     * @return the value of mapa.geo_map_opcion.fec_registra
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public Date getFecRegistra() {
        return fecRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_opcion.fec_registra
     *
     * @param fecRegistra the value for mapa.geo_map_opcion.fec_registra
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public void setFecRegistra(Date fecRegistra) {
        this.fecRegistra = fecRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_opcion.fec_modifica
     *
     * @return the value of mapa.geo_map_opcion.fec_modifica
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public Date getFecModifica() {
        return fecModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_opcion.fec_modifica
     *
     * @param fecModifica the value for mapa.geo_map_opcion.fec_modifica
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public void setFecModifica(Date fecModifica) {
        this.fecModifica = fecModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_opcion.des_usu_registra
     *
     * @return the value of mapa.geo_map_opcion.des_usu_registra
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public String getDesUsuRegistra() {
        return desUsuRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_opcion.des_usu_registra
     *
     * @param desUsuRegistra the value for mapa.geo_map_opcion.des_usu_registra
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public void setDesUsuRegistra(String desUsuRegistra) {
        this.desUsuRegistra = desUsuRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_opcion.des_usu_modifica
     *
     * @return the value of mapa.geo_map_opcion.des_usu_modifica
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public String getDesUsuModifica() {
        return desUsuModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_opcion.des_usu_modifica
     *
     * @param desUsuModifica the value for mapa.geo_map_opcion.des_usu_modifica
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public void setDesUsuModifica(String desUsuModifica) {
        this.desUsuModifica = desUsuModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_opcion.des_ip_registra
     *
     * @return the value of mapa.geo_map_opcion.des_ip_registra
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public String getDesIpRegistra() {
        return desIpRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_opcion.des_ip_registra
     *
     * @param desIpRegistra the value for mapa.geo_map_opcion.des_ip_registra
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public void setDesIpRegistra(String desIpRegistra) {
        this.desIpRegistra = desIpRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_opcion.des_ip_modifica
     *
     * @return the value of mapa.geo_map_opcion.des_ip_modifica
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public String getDesIpModifica() {
        return desIpModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_opcion.des_ip_modifica
     *
     * @param desIpModifica the value for mapa.geo_map_opcion.des_ip_modifica
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    public void setDesIpModifica(String desIpModifica) {
        this.desIpModifica = desIpModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_opcion
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Opcion other = (Opcion) that;
        return (this.getIdOpcion() == null ? other.getIdOpcion() == null : this.getIdOpcion().equals(other.getIdOpcion()))
            && (this.getNombre() == null ? other.getNombre() == null : this.getNombre().equals(other.getNombre()))
            && (this.getDefinicion() == null ? other.getDefinicion() == null : this.getDefinicion().equals(other.getDefinicion()))
            && (this.getFecRegistra() == null ? other.getFecRegistra() == null : this.getFecRegistra().equals(other.getFecRegistra()))
            && (this.getFecModifica() == null ? other.getFecModifica() == null : this.getFecModifica().equals(other.getFecModifica()))
            && (this.getDesUsuRegistra() == null ? other.getDesUsuRegistra() == null : this.getDesUsuRegistra().equals(other.getDesUsuRegistra()))
            && (this.getDesUsuModifica() == null ? other.getDesUsuModifica() == null : this.getDesUsuModifica().equals(other.getDesUsuModifica()))
            && (this.getDesIpRegistra() == null ? other.getDesIpRegistra() == null : this.getDesIpRegistra().equals(other.getDesIpRegistra()))
            && (this.getDesIpModifica() == null ? other.getDesIpModifica() == null : this.getDesIpModifica().equals(other.getDesIpModifica()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_opcion
     *
     * @mbg.generated Sat Jul 08 20:02:48 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdOpcion() == null) ? 0 : getIdOpcion().hashCode());
        result = prime * result + ((getNombre() == null) ? 0 : getNombre().hashCode());
        result = prime * result + ((getDefinicion() == null) ? 0 : getDefinicion().hashCode());
        result = prime * result + ((getFecRegistra() == null) ? 0 : getFecRegistra().hashCode());
        result = prime * result + ((getFecModifica() == null) ? 0 : getFecModifica().hashCode());
        result = prime * result + ((getDesUsuRegistra() == null) ? 0 : getDesUsuRegistra().hashCode());
        result = prime * result + ((getDesUsuModifica() == null) ? 0 : getDesUsuModifica().hashCode());
        result = prime * result + ((getDesIpRegistra() == null) ? 0 : getDesIpRegistra().hashCode());
        result = prime * result + ((getDesIpModifica() == null) ? 0 : getDesIpModifica().hashCode());
        return result;
    }
}