package pe.gob.miraflores.mobile.domain.seguridad;

import java.util.Date;
import java.util.List;

public class UsuarioLogin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.ide_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private Integer ideUsuario;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.ide_estado
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private Integer ideEstado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.des_login_user
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String desLoginUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.clv_clave_user
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String clvClaveUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.ide_rol
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private Integer ideRol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.ide_persona
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private Integer idePersona;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.fec_registra
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private Date fecRegistra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.fec_modifica
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private Date fecModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.des_usu_registra
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String desUsuRegistra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.des_usu_modifica
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String desUsuModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.des_ip_registra
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String desIpRegistra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.des_ip_modifica
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String desIpModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.in_cuenta_expirada
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String inCuentaExpirada;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.in_cuenta_bloqueada
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String inCuentaBloqueada;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.in_credencial_expirada
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String inCredencialExpirada;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.in_habilitado
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String inHabilitado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.des_parametro1
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String desParametro1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.des_ruta_signpfx
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String desRutaSignpfx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.des_ruta_signimage
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String desRutaSignimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.des_nombre_completo
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String desNombreCompleto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.email
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.dni
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String dni;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.flg_usr
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private String flgUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.area
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private Integer area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mapa.geo_map_usuario.ide_rol_rol
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    private Integer ideRolRol;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.ide_usuario
     *
     * @return the value of mapa.geo_map_usuario.ide_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public Integer getIdeUsuario() {
        return ideUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.ide_usuario
     *
     * @param ideUsuario the value for mapa.geo_map_usuario.ide_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setIdeUsuario(Integer ideUsuario) {
        this.ideUsuario = ideUsuario;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.ide_estado
     *
     * @return the value of mapa.geo_map_usuario.ide_estado
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public Integer getIdeEstado() {
        return ideEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.ide_estado
     *
     * @param ideEstado the value for mapa.geo_map_usuario.ide_estado
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setIdeEstado(Integer ideEstado) {
        this.ideEstado = ideEstado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.des_login_user
     *
     * @return the value of mapa.geo_map_usuario.des_login_user
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getDesLoginUser() {
        return desLoginUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.des_login_user
     *
     * @param desLoginUser the value for mapa.geo_map_usuario.des_login_user
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setDesLoginUser(String desLoginUser) {
        this.desLoginUser = desLoginUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.clv_clave_user
     *
     * @return the value of mapa.geo_map_usuario.clv_clave_user
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getClvClaveUser() {
        return clvClaveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.clv_clave_user
     *
     * @param clvClaveUser the value for mapa.geo_map_usuario.clv_clave_user
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setClvClaveUser(String clvClaveUser) {
        this.clvClaveUser = clvClaveUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.ide_rol
     *
     * @return the value of mapa.geo_map_usuario.ide_rol
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public Integer getIdeRol() {
        return ideRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.ide_rol
     *
     * @param ideRol the value for mapa.geo_map_usuario.ide_rol
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setIdeRol(Integer ideRol) {
        this.ideRol = ideRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.ide_persona
     *
     * @return the value of mapa.geo_map_usuario.ide_persona
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public Integer getIdePersona() {
        return idePersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.ide_persona
     *
     * @param idePersona the value for mapa.geo_map_usuario.ide_persona
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setIdePersona(Integer idePersona) {
        this.idePersona = idePersona;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.fec_registra
     *
     * @return the value of mapa.geo_map_usuario.fec_registra
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public Date getFecRegistra() {
        return fecRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.fec_registra
     *
     * @param fecRegistra the value for mapa.geo_map_usuario.fec_registra
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setFecRegistra(Date fecRegistra) {
        this.fecRegistra = fecRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.fec_modifica
     *
     * @return the value of mapa.geo_map_usuario.fec_modifica
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public Date getFecModifica() {
        return fecModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.fec_modifica
     *
     * @param fecModifica the value for mapa.geo_map_usuario.fec_modifica
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setFecModifica(Date fecModifica) {
        this.fecModifica = fecModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.des_usu_registra
     *
     * @return the value of mapa.geo_map_usuario.des_usu_registra
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getDesUsuRegistra() {
        return desUsuRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.des_usu_registra
     *
     * @param desUsuRegistra the value for mapa.geo_map_usuario.des_usu_registra
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setDesUsuRegistra(String desUsuRegistra) {
        this.desUsuRegistra = desUsuRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.des_usu_modifica
     *
     * @return the value of mapa.geo_map_usuario.des_usu_modifica
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getDesUsuModifica() {
        return desUsuModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.des_usu_modifica
     *
     * @param desUsuModifica the value for mapa.geo_map_usuario.des_usu_modifica
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setDesUsuModifica(String desUsuModifica) {
        this.desUsuModifica = desUsuModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.des_ip_registra
     *
     * @return the value of mapa.geo_map_usuario.des_ip_registra
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getDesIpRegistra() {
        return desIpRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.des_ip_registra
     *
     * @param desIpRegistra the value for mapa.geo_map_usuario.des_ip_registra
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setDesIpRegistra(String desIpRegistra) {
        this.desIpRegistra = desIpRegistra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.des_ip_modifica
     *
     * @return the value of mapa.geo_map_usuario.des_ip_modifica
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getDesIpModifica() {
        return desIpModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.des_ip_modifica
     *
     * @param desIpModifica the value for mapa.geo_map_usuario.des_ip_modifica
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setDesIpModifica(String desIpModifica) {
        this.desIpModifica = desIpModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.in_cuenta_expirada
     *
     * @return the value of mapa.geo_map_usuario.in_cuenta_expirada
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getInCuentaExpirada() {
        return inCuentaExpirada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.in_cuenta_expirada
     *
     * @param inCuentaExpirada the value for mapa.geo_map_usuario.in_cuenta_expirada
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setInCuentaExpirada(String inCuentaExpirada) {
        this.inCuentaExpirada = inCuentaExpirada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.in_cuenta_bloqueada
     *
     * @return the value of mapa.geo_map_usuario.in_cuenta_bloqueada
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getInCuentaBloqueada() {
        return inCuentaBloqueada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.in_cuenta_bloqueada
     *
     * @param inCuentaBloqueada the value for mapa.geo_map_usuario.in_cuenta_bloqueada
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setInCuentaBloqueada(String inCuentaBloqueada) {
        this.inCuentaBloqueada = inCuentaBloqueada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.in_credencial_expirada
     *
     * @return the value of mapa.geo_map_usuario.in_credencial_expirada
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getInCredencialExpirada() {
        return inCredencialExpirada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.in_credencial_expirada
     *
     * @param inCredencialExpirada the value for mapa.geo_map_usuario.in_credencial_expirada
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setInCredencialExpirada(String inCredencialExpirada) {
        this.inCredencialExpirada = inCredencialExpirada;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.in_habilitado
     *
     * @return the value of mapa.geo_map_usuario.in_habilitado
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getInHabilitado() {
        return inHabilitado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.in_habilitado
     *
     * @param inHabilitado the value for mapa.geo_map_usuario.in_habilitado
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setInHabilitado(String inHabilitado) {
        this.inHabilitado = inHabilitado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.des_parametro1
     *
     * @return the value of mapa.geo_map_usuario.des_parametro1
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getDesParametro1() {
        return desParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.des_parametro1
     *
     * @param desParametro1 the value for mapa.geo_map_usuario.des_parametro1
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setDesParametro1(String desParametro1) {
        this.desParametro1 = desParametro1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.des_ruta_signpfx
     *
     * @return the value of mapa.geo_map_usuario.des_ruta_signpfx
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getDesRutaSignpfx() {
        return desRutaSignpfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.des_ruta_signpfx
     *
     * @param desRutaSignpfx the value for mapa.geo_map_usuario.des_ruta_signpfx
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setDesRutaSignpfx(String desRutaSignpfx) {
        this.desRutaSignpfx = desRutaSignpfx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.des_ruta_signimage
     *
     * @return the value of mapa.geo_map_usuario.des_ruta_signimage
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getDesRutaSignimage() {
        return desRutaSignimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.des_ruta_signimage
     *
     * @param desRutaSignimage the value for mapa.geo_map_usuario.des_ruta_signimage
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setDesRutaSignimage(String desRutaSignimage) {
        this.desRutaSignimage = desRutaSignimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.des_nombre_completo
     *
     * @return the value of mapa.geo_map_usuario.des_nombre_completo
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getDesNombreCompleto() {
        return desNombreCompleto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.des_nombre_completo
     *
     * @param desNombreCompleto the value for mapa.geo_map_usuario.des_nombre_completo
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setDesNombreCompleto(String desNombreCompleto) {
        this.desNombreCompleto = desNombreCompleto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.email
     *
     * @return the value of mapa.geo_map_usuario.email
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.email
     *
     * @param email the value for mapa.geo_map_usuario.email
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.dni
     *
     * @return the value of mapa.geo_map_usuario.dni
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getDni() {
        return dni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.dni
     *
     * @param dni the value for mapa.geo_map_usuario.dni
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setDni(String dni) {
        this.dni = dni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.flg_usr
     *
     * @return the value of mapa.geo_map_usuario.flg_usr
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public String getFlgUsr() {
        return flgUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.flg_usr
     *
     * @param flgUsr the value for mapa.geo_map_usuario.flg_usr
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setFlgUsr(String flgUsr) {
        this.flgUsr = flgUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.area
     *
     * @return the value of mapa.geo_map_usuario.area
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public Integer getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.area
     *
     * @param area the value for mapa.geo_map_usuario.area
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mapa.geo_map_usuario.ide_rol_rol
     *
     * @return the value of mapa.geo_map_usuario.ide_rol_rol
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public Integer getIdeRolRol() {
        return ideRolRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mapa.geo_map_usuario.ide_rol_rol
     *
     * @param ideRolRol the value for mapa.geo_map_usuario.ide_rol_rol
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    public void setIdeRolRol(Integer ideRolRol) {
        this.ideRolRol = ideRolRol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UsuarioLogin other = (UsuarioLogin) that;
        return (this.getIdeUsuario() == null ? other.getIdeUsuario() == null : this.getIdeUsuario().equals(other.getIdeUsuario()))
            && (this.getIdeEstado() == null ? other.getIdeEstado() == null : this.getIdeEstado().equals(other.getIdeEstado()))
            && (this.getDesLoginUser() == null ? other.getDesLoginUser() == null : this.getDesLoginUser().equals(other.getDesLoginUser()))
            && (this.getClvClaveUser() == null ? other.getClvClaveUser() == null : this.getClvClaveUser().equals(other.getClvClaveUser()))
            && (this.getIdeRol() == null ? other.getIdeRol() == null : this.getIdeRol().equals(other.getIdeRol()))
            && (this.getIdePersona() == null ? other.getIdePersona() == null : this.getIdePersona().equals(other.getIdePersona()))
            && (this.getFecRegistra() == null ? other.getFecRegistra() == null : this.getFecRegistra().equals(other.getFecRegistra()))
            && (this.getFecModifica() == null ? other.getFecModifica() == null : this.getFecModifica().equals(other.getFecModifica()))
            && (this.getDesUsuRegistra() == null ? other.getDesUsuRegistra() == null : this.getDesUsuRegistra().equals(other.getDesUsuRegistra()))
            && (this.getDesUsuModifica() == null ? other.getDesUsuModifica() == null : this.getDesUsuModifica().equals(other.getDesUsuModifica()))
            && (this.getDesIpRegistra() == null ? other.getDesIpRegistra() == null : this.getDesIpRegistra().equals(other.getDesIpRegistra()))
            && (this.getDesIpModifica() == null ? other.getDesIpModifica() == null : this.getDesIpModifica().equals(other.getDesIpModifica()))
            && (this.getInCuentaExpirada() == null ? other.getInCuentaExpirada() == null : this.getInCuentaExpirada().equals(other.getInCuentaExpirada()))
            && (this.getInCuentaBloqueada() == null ? other.getInCuentaBloqueada() == null : this.getInCuentaBloqueada().equals(other.getInCuentaBloqueada()))
            && (this.getInCredencialExpirada() == null ? other.getInCredencialExpirada() == null : this.getInCredencialExpirada().equals(other.getInCredencialExpirada()))
            && (this.getInHabilitado() == null ? other.getInHabilitado() == null : this.getInHabilitado().equals(other.getInHabilitado()))
            && (this.getDesParametro1() == null ? other.getDesParametro1() == null : this.getDesParametro1().equals(other.getDesParametro1()))
            && (this.getDesRutaSignpfx() == null ? other.getDesRutaSignpfx() == null : this.getDesRutaSignpfx().equals(other.getDesRutaSignpfx()))
            && (this.getDesRutaSignimage() == null ? other.getDesRutaSignimage() == null : this.getDesRutaSignimage().equals(other.getDesRutaSignimage()))
            && (this.getDesNombreCompleto() == null ? other.getDesNombreCompleto() == null : this.getDesNombreCompleto().equals(other.getDesNombreCompleto()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getDni() == null ? other.getDni() == null : this.getDni().equals(other.getDni()))
            && (this.getFlgUsr() == null ? other.getFlgUsr() == null : this.getFlgUsr().equals(other.getFlgUsr()))
            && (this.getArea() == null ? other.getArea() == null : this.getArea().equals(other.getArea()))
            && (this.getIdeRolRol() == null ? other.getIdeRolRol() == null : this.getIdeRolRol().equals(other.getIdeRolRol()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mapa.geo_map_usuario
     *
     * @mbg.generated Fri Oct 27 11:46:54 COT 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getIdeUsuario() == null) ? 0 : getIdeUsuario().hashCode());
        result = prime * result + ((getIdeEstado() == null) ? 0 : getIdeEstado().hashCode());
        result = prime * result + ((getDesLoginUser() == null) ? 0 : getDesLoginUser().hashCode());
        result = prime * result + ((getClvClaveUser() == null) ? 0 : getClvClaveUser().hashCode());
        result = prime * result + ((getIdeRol() == null) ? 0 : getIdeRol().hashCode());
        result = prime * result + ((getIdePersona() == null) ? 0 : getIdePersona().hashCode());
        result = prime * result + ((getFecRegistra() == null) ? 0 : getFecRegistra().hashCode());
        result = prime * result + ((getFecModifica() == null) ? 0 : getFecModifica().hashCode());
        result = prime * result + ((getDesUsuRegistra() == null) ? 0 : getDesUsuRegistra().hashCode());
        result = prime * result + ((getDesUsuModifica() == null) ? 0 : getDesUsuModifica().hashCode());
        result = prime * result + ((getDesIpRegistra() == null) ? 0 : getDesIpRegistra().hashCode());
        result = prime * result + ((getDesIpModifica() == null) ? 0 : getDesIpModifica().hashCode());
        result = prime * result + ((getInCuentaExpirada() == null) ? 0 : getInCuentaExpirada().hashCode());
        result = prime * result + ((getInCuentaBloqueada() == null) ? 0 : getInCuentaBloqueada().hashCode());
        result = prime * result + ((getInCredencialExpirada() == null) ? 0 : getInCredencialExpirada().hashCode());
        result = prime * result + ((getInHabilitado() == null) ? 0 : getInHabilitado().hashCode());
        result = prime * result + ((getDesParametro1() == null) ? 0 : getDesParametro1().hashCode());
        result = prime * result + ((getDesRutaSignpfx() == null) ? 0 : getDesRutaSignpfx().hashCode());
        result = prime * result + ((getDesRutaSignimage() == null) ? 0 : getDesRutaSignimage().hashCode());
        result = prime * result + ((getDesNombreCompleto() == null) ? 0 : getDesNombreCompleto().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getDni() == null) ? 0 : getDni().hashCode());
        result = prime * result + ((getFlgUsr() == null) ? 0 : getFlgUsr().hashCode());
        result = prime * result + ((getArea() == null) ? 0 : getArea().hashCode());
        result = prime * result + ((getIdeRolRol() == null) ? 0 : getIdeRolRol().hashCode());
        return result;
    }
    
    
    private List<UsuarioOpcion> opciones;
	
	private String opcWaze;
	
	private String opcVoxiva;
	
	private String opcRtransito;
	
	private String opcRpolicia;
	
	private String opcRserenazgo;
	
	private String opcRfiscalizacion;
	
	private String opcRapagado;
	
	private String opcRotros;
	
	private String opcVig1;
	
	private String opcVig2;
	
	private String opcVig3;
	
	private String opcEstacionamientos;
	
	private String opcCambistas;
	
	private String opcReach;
	
	private String opcPos;
	
	private String descRolRol;

	public List<UsuarioOpcion> getOpciones() {
		return opciones;
	}

	public String getOpcWaze() {
		return opcWaze;
	}

	public void setOpcWaze(String opcWaze) {
		this.opcWaze = opcWaze;
	}

	public String getOpcVoxiva() {
		return opcVoxiva;
	}

	public void setOpcVoxiva(String opcVoxiva) {
		this.opcVoxiva = opcVoxiva;
	}

	public String getOpcRtransito() {
		return opcRtransito;
	}

	public void setOpcRtransito(String opcRtransito) {
		this.opcRtransito = opcRtransito;
	}

	public String getOpcRpolicia() {
		return opcRpolicia;
	}

	public void setOpcRpolicia(String opcRpolicia) {
		this.opcRpolicia = opcRpolicia;
	}

	public String getOpcRserenazgo() {
		return opcRserenazgo;
	}

	public void setOpcRserenazgo(String opcRserenazgo) {
		this.opcRserenazgo = opcRserenazgo;
	}

	public String getOpcRfiscalizacion() {
		return opcRfiscalizacion;
	}

	public void setOpcRfiscalizacion(String opcRfiscalizacion) {
		this.opcRfiscalizacion = opcRfiscalizacion;
	}

	public String getOpcRapagado() {
		return opcRapagado;
	}

	public void setOpcRapagado(String opcRapagado) {
		this.opcRapagado = opcRapagado;
	}

	public String getOpcRotros() {
		return opcRotros;
	}

	public void setOpcRotros(String opcRotros) {
		this.opcRotros = opcRotros;
	}

	public String getOpcVig1() {
		return opcVig1;
	}

	public void setOpcVig1(String opcVig1) {
		this.opcVig1 = opcVig1;
	}

	public String getOpcVig2() {
		return opcVig2;
	}

	public void setOpcVig2(String opcVig2) {
		this.opcVig2 = opcVig2;
	}

	public String getOpcVig3() {
		return opcVig3;
	}

	public void setOpcVig3(String opcVig3) {
		this.opcVig3 = opcVig3;
	}

	public String getOpcEstacionamientos() {
		return opcEstacionamientos;
	}

	public void setOpcEstacionamientos(String opcEstacionamientos) {
		this.opcEstacionamientos = opcEstacionamientos;
	}

	public String getOpcCambistas() {
		return opcCambistas;
	}

	public void setOpcCambistas(String opcCambistas) {
		this.opcCambistas = opcCambistas;
	}

	public void setOpciones(List<UsuarioOpcion> opciones) {
		this.opciones = opciones;
	}

	public String getDescRolRol() {
		return descRolRol;
	}

	public void setDescRolRol(String descRolRol) {
		this.descRolRol = descRolRol;
	}

	public String getOpcReach() {
		return opcReach;
	}

	public void setOpcReach(String opcReach) {
		this.opcReach = opcReach;
	}

	public String getOpcPos() {
		return opcPos;
	}

	public void setOpcPos(String opcPos) {
		this.opcPos = opcPos;
	}
	
	//Nuevos campos auxiliares
	
	public List<Integer> ArrIdeUsuario;

	public List<Integer> getArrIdeUsuario() {
		return ArrIdeUsuario;
	}

	public void setArrIdeUsuario(List<Integer> arrIdeUsuario) {
		ArrIdeUsuario = arrIdeUsuario;
	}
	
	
	
}